//! Pinned bake-configuration constants.
//!
//! Per the engine convention every tunable lives here as a `pub const`, with no
//! wrapper. Most of these are the **load-bearing determinism pins** the plan
//! calls out (the coloring seed, the global pixels-per-em, the distance range):
//! changing one changes the byte content of every generated `.bfont`, so the
//! `.bfont` header records the generator version + seed (see [`crate::atlas`]).

/// Generator version stamped into the `.bfont` header. Bump on any change that
/// alters generated bytes so a stale asset is detected at load (Decision T2-E).
pub const GENERATOR_VERSION: u32 = 1;

/// `.bfont` magic: ASCII `"BFNT"` little-endian.
pub const BFONT_MAGIC: u32 = u32::from_le_bytes(*b"BFNT");

/// Global rasterization scale in pixels-per-em. EVERY glyph is rasterized at
/// this one scale, which makes `texels_per_em` global and the shader's single
/// `screenPxRange` uniform valid (§T2c range mapping). 48 px/em is the plan's
/// ASCII/Latin-1 default.
pub const PIXELS_PER_EM: f32 = 48.0;

/// MTSDF distance range in **texels** (the pxrange the shader divides by). The
/// owner-locked atlas kind is MTSDF, so the range is 6 (range-4 is the MSDF
/// fill-only variant, not used here). Bound to em units by
/// `range_em = DISTANCE_RANGE_TEXELS / PIXELS_PER_EM`.
pub const DISTANCE_RANGE_TEXELS: f32 = 6.0;

/// Deterministic edge-coloring seed (Decision T2-E). Pinned so the scalar
/// reference goldens are byte-reproducible; recorded in the `.bfont` header.
pub const EDGE_COLORING_SEED: u64 = 0x9E37_79B9_7F4A_7C15;

/// Corner predicate cutoff in radians (`maxAngle`, msdfgen canonical default).
/// A join flatter than this is NOT a corner; sharper IS. The cross-product
/// threshold used at runtime is `sin(MAX_CORNER_ANGLE_RAD)` (§T2a).
pub const MAX_CORNER_ANGLE_RAD: f32 = 3.0;

/// Number of evenly-spaced Newton seeds for the cubic nearest-point search
/// (msdfgen's fixed search count). Multiple seeds avoid the S-curve local
/// minimum (§T2a cubic).
pub const CUBIC_NEWTON_SEEDS: usize = 4;

/// Newton refinement iterations per seed for the cubic solver.
pub const CUBIC_NEWTON_ITERS: usize = 8;

/// Inter-glyph + outer-border spacing in texels, ≥ `DISTANCE_RANGE_TEXELS / 2`
/// to prevent bilinear neighbor bleed across packed glyphs (§T3).
pub const ATLAS_PADDING_TEXELS: u32 = 4;

/// Default `notdef` glyph occupies slot 0 in every per-font glyph table.
pub const NOTDEF_SLOT: u16 = 0;

/// ASCII fast-path bound for the codepoint map: `cp < 128` resolves via a
/// direct array, larger codepoints via sorted binary search.
pub const ASCII_FAST_PATH_LIMIT: u32 = 128;
