// Pillar B increment B2: the per-instance TRS interpolation compute PRE-PASS
// (`interp_instances.comp.hlsl`).
//
// One invocation per instance. Each thread reads a `TransformPair` (the previous +
// current simulation-substep TRS of one entity) at binding 0, interpolates it at the
// frame-wide `alpha` (the fixed-timestep overstep fraction, in [0, 1)), composes the
// result into the 3×4 ROW-MAJOR model affine, and writes the 48-byte `InstanceModelCol`
// record at binding 1. The consumer (the gbuffer VS) reads that record UNCHANGED — this
// pass simply refreshes the model column each frame from the interpolated pose instead
// of the raw current pose.
//
// The INTERPOLATION MATH BODY (`interp_trs`) is MACHINE-GENERATED by
// `boyko_shaderdsl::emit::emit_hlsl_transform_interp()` — the eDSL whose `f32` Eval
// backend IS the CPU oracle (its composed rows byte-match
// `boyko_render::InstanceModelCol::from_global` for the interpolated TRS). It is spliced
// between the `// === GENERATED interp_trs BEGIN/END ===` sentinels below. A hand-edit
// of that span — which would silently diverge the GPU interpolation from the host oracle
// — fails the `interp_edsl_sync` test in CI. To regenerate + re-splice:
//   cargo run -p boyko_shaderdsl --features emit --bin emit_field   (adds interp_trs)
// then re-DXC this file (the `interp_edsl_sync` test re-DXCs it and byte-compares).
//
// The B3 increment WIRES this pass into the frame (the descriptor sets + the dispatch);
// this file + its `.spv` are the B2 deliverable (shader + goldens only).
//
// Compiled offline (hermetic build) with:
//   dxc.exe -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3 \
//       interp_instances.comp.hlsl -Fo interp_instances.comp.spv

// One decomposed transform: position, rotation (unit quaternion, xyzw — the engine's
// glTF/GPU convention), and per-axis scale. All-`float4` packing (xyz + one pad lane per
// vector) keeps the record 16-byte aligned and std430-straddle-free: `pos` at byte 0,
// `rot` at 16, `scale` at 32 — a 48-byte TRS. The `.w` pad of `pos`/`scale` is unused.
struct Trs {
    float4 pos;    // xyz = translation, w = pad
    float4 rot;    // xyzw = unit quaternion (x, y, z, w)
    float4 scale;  // xyz = per-axis scale, w = pad
};

// One previous → current pair (the B1 packer's output, the B3 dispatch's input). 96 B:
// `prev` at byte 0, `curr` at 48. The host `TransformPair` mirror (in boyko_shaderdsl /
// boyko_render) pins this layout with const asserts.
struct TransformPair {
    Trs prev;
    Trs curr;
};

// The 3×4 ROW-MAJOR model affine `interp_trs` returns — byte-identical to
// `boyko_render::InstanceModelCol` (`rows[i] = [linear_row_i.xyz | translation_i]`, 48 B).
struct InterpModel {
    float4 row0;
    float4 row1;
    float4 row2;
};

// binding 0: the per-instance previous/current TRS pairs (read-only input, B1's output).
StructuredBuffer<TransformPair> Pairs : register(t0);

// binding 1: the per-instance 48-byte model affine (RW output). The gbuffer VS reads this
// buffer UNCHANGED as its `InstanceModelCol` instance column.
RWStructuredBuffer<InterpModel> ModelOut : register(u1);

// The interp push constants: the instance count (bounds guard) + the frame-wide overstep
// fraction alpha in [0, 1). Mirrors the host `InterpInstancesPush`.
struct InterpInstancesPush {
    uint  count;
    float alpha;
};
[[vk::push_constant]] InterpInstancesPush pc;

// === GENERATED interp_trs BEGIN === (boyko_shaderdsl::emit::emit_hlsl_transform_interp)
InterpModel interp_trs(TransformPair pair, float alpha) {
    float t0 = pair.curr.pos.x - pair.prev.pos.x;
    float t1 = t0 * alpha;
    float t2 = pair.prev.pos.x + t1;
    float t3 = pair.curr.pos.y - pair.prev.pos.y;
    float t4 = t3 * alpha;
    float t5 = pair.prev.pos.y + t4;
    float t6 = pair.curr.pos.z - pair.prev.pos.z;
    float t7 = t6 * alpha;
    float t8 = pair.prev.pos.z + t7;
    float t9 = pair.curr.scale.x - pair.prev.scale.x;
    float t10 = t9 * alpha;
    float t11 = pair.prev.scale.x + t10;
    float t12 = pair.curr.scale.y - pair.prev.scale.y;
    float t13 = t12 * alpha;
    float t14 = pair.prev.scale.y + t13;
    float t15 = pair.curr.scale.z - pair.prev.scale.z;
    float t16 = t15 * alpha;
    float t17 = pair.prev.scale.z + t16;
    float t18 = pair.prev.rot.x * pair.curr.rot.x;
    float t19 = pair.prev.rot.y * pair.curr.rot.y;
    float t20 = t18 + t19;
    float t21 = pair.prev.rot.z * pair.curr.rot.z;
    float t22 = t20 + t21;
    float t23 = pair.prev.rot.w * pair.curr.rot.w;
    float t24 = t22 + t23;
    float t25 = -1.0;
    float t26 = (t24 < 0.0) ? t25 : 1.0;
    float t27 = pair.curr.rot.x * t26;
    float t28 = pair.curr.rot.y * t26;
    float t29 = pair.curr.rot.z * t26;
    float t30 = pair.curr.rot.w * t26;
    float t31 = t24 * t26;
    float t32 = acos(t31);
    float t33 = sin(t32);
    float t34 = 1.0 - alpha;
    float t35 = t34 * t32;
    float t36 = sin(t35);
    float t37 = t36 / t33;
    float t38 = alpha * t32;
    float t39 = sin(t38);
    float t40 = t39 / t33;
    float t41 = 1.0 - alpha;
    float t42 = (t31 > 0.9995) ? t41 : t37;
    float t43 = (t31 > 0.9995) ? alpha : t40;
    float t44 = pair.prev.rot.x * t42;
    float t45 = t27 * t43;
    float t46 = t44 + t45;
    float t47 = pair.prev.rot.y * t42;
    float t48 = t28 * t43;
    float t49 = t47 + t48;
    float t50 = pair.prev.rot.z * t42;
    float t51 = t29 * t43;
    float t52 = t50 + t51;
    float t53 = pair.prev.rot.w * t42;
    float t54 = t30 * t43;
    float t55 = t53 + t54;
    float t56 = t46 * t46;
    float t57 = t49 * t49;
    float t58 = t56 + t57;
    float t59 = t52 * t52;
    float t60 = t58 + t59;
    float t61 = t55 * t55;
    float t62 = t60 + t61;
    float t63 = sqrt(t62);
    float t64 = 1.0 / t63;
    float t65 = t46 * t64;
    float t66 = t49 * t64;
    float t67 = t52 * t64;
    float t68 = t55 * t64;
    float t69 = (pair.prev.rot.x == t27 && pair.prev.rot.y == t28 && pair.prev.rot.z == t29 && pair.prev.rot.w == t30) ? pair.prev.rot.x : t65;
    float t70 = (pair.prev.rot.x == t27 && pair.prev.rot.y == t28 && pair.prev.rot.z == t29 && pair.prev.rot.w == t30) ? pair.prev.rot.y : t66;
    float t71 = (pair.prev.rot.x == t27 && pair.prev.rot.y == t28 && pair.prev.rot.z == t29 && pair.prev.rot.w == t30) ? pair.prev.rot.z : t67;
    float t72 = (pair.prev.rot.x == t27 && pair.prev.rot.y == t28 && pair.prev.rot.z == t29 && pair.prev.rot.w == t30) ? pair.prev.rot.w : t68;
    float t73 = t69 * t69;
    float t74 = t70 * t70;
    float t75 = t71 * t71;
    float t76 = t69 * t70;
    float t77 = t69 * t71;
    float t78 = t70 * t71;
    float t79 = t72 * t69;
    float t80 = t72 * t70;
    float t81 = t72 * t71;
    float t82 = t74 + t75;
    float t83 = 2.0 * t82;
    float t84 = 1.0 - t83;
    float t85 = t76 - t81;
    float t86 = 2.0 * t85;
    float t87 = t77 + t80;
    float t88 = 2.0 * t87;
    float t89 = t76 + t81;
    float t90 = 2.0 * t89;
    float t91 = t73 + t75;
    float t92 = 2.0 * t91;
    float t93 = 1.0 - t92;
    float t94 = t78 - t79;
    float t95 = 2.0 * t94;
    float t96 = t77 - t80;
    float t97 = 2.0 * t96;
    float t98 = t78 + t79;
    float t99 = 2.0 * t98;
    float t100 = t73 + t74;
    float t101 = 2.0 * t100;
    float t102 = 1.0 - t101;
    float t103 = t84 * t11;
    float t104 = t86 * t14;
    float t105 = t88 * t17;
    float t106 = t90 * t11;
    float t107 = t93 * t14;
    float t108 = t95 * t17;
    float t109 = t97 * t11;
    float t110 = t99 * t14;
    float t111 = t102 * t17;
    InterpModel m;
    m.row0 = float4(t103, t104, t105, t2);
    m.row1 = float4(t106, t107, t108, t5);
    m.row2 = float4(t109, t110, t111, t8);
    return m;
}
// === GENERATED interp_trs END ===

[numthreads(64, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {
    uint i = tid.x;
    if (i >= pc.count) {
        return;
    }
    ModelOut[i] = interp_trs(Pairs[i], pc.alpha);
}
