// particle_draw.fs -- the GPU particle system's FRAGMENT half
// (`docs/PARTICLES-PLAN.md` Rev 4, algorithm A5). Unlit, additive, bindless-textured.
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. This stage
// carries NO generated span: it is one modulate and one sample, with no leaf-class math.
//
// # Additive is a PIPELINE state, not shader code
//
// The blend is `BlendState::ADDITIVE` on the pipeline (plan D7) with `depth_write = OFF` and
// `depth_test = ON`, so opaque geometry still occludes. Additive is commutative and, under the
// 8-bit saturation `lit` imposes, `sat(sat(x)+y) = min(1, x+y)` is order-independent -- which is
// why P0 ships UNSORTED, provably (plan D10).
//
// # Bindless, so ONE draw covers every effect
//
// `tex_index` is an index into the shared runtime-sized `Texture2D[]` table (the SAME layout
// object `gbuffer_mrt.fs.hlsl` binds at set 1), which is what closes R11 structurally: there is
// no per-effect batch key and no per-texture draw split. Slot 0 is the reserved error-texture
// slot, so an UNTEXTURED effect leaves `tex_index` at 0 and the sample is skipped entirely --
// the same `!= 0` gate every other bindless consumer in this tree uses.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T ps_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_draw.fs.hlsl -Fo particle_draw.fs.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (1, 0, SAMPLED_IMAGE[])  Texture2D gTextures[]      read (FRAGMENT)
//   (1, 1, SAMPLER)          SamplerState gTexSampler   read (FRAGMENT)
//
//   Set 0 is the VERTEX half's (`p_render` @0, `Camera` @1) -- declared there, unread here.
//
// # Push constants
//
//   NONE in this stage. The 72-byte range the VS declares is VERTEX-only.

[[vk::binding(0, 1)]] Texture2D gTextures[] : register(t0, space1);
[[vk::binding(1, 1)]] SamplerState gTexSampler : register(s0, space1);

// Must stay byte-identical to `particle_draw.vs.hlsl`'s `VsOut` -- the two are one interface.
struct VsOut {
    float4 position  : SV_Position;
    float2 uv        : TEXCOORD0;
    nointerpolation float4 color : COLOR0;
    nointerpolation uint tex_index : TEXIDX;
};

float4 main(VsOut input) : SV_Target {
    float4 c = input.color;
    if (input.tex_index != 0u) {
        c = c * gTextures[NonUniformResourceIndex(input.tex_index)].Sample(gTexSampler, input.uv);
    }
    return c;
}
