// particle_sim.comp -- the GPU particle system's HOT LOOP
// (`docs/PARTICLES-PLAN.md` Rev 4, algorithm A4 / decisions D3, D5). `DispatchIndirect`, 256
// threads, O(alive_count_cur).
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. The
// `// === GENERATED <name> BEGIN/END ===` spans are MACHINE-EMITTED from `boyko_shaderdsl`'s
// generic leaf bodies; a hand-edit of any of them fails
// `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # The wave-level atomic mechanism -- the plan's NORMATIVE block, symbol for symbol
//
//   w_count = WaveActiveCountBits(survives)      // survivors in THIS wave        (per-wave)
//   w_lane  = WavePrefixCountBits(survives)      // this lane's rank among them   (per-lane)
//   if (WaveIsFirstLane())
//       w_base_raw = InterlockedAdd(alive_count_next, w_count)     // returns the OLD value
//   w_base  = WaveReadLaneFirst(w_base_raw)      // the wave's LIST reservation base
//   idx     = w_base + w_lane                    // this lane's LIST position
//
// and, on the additive class's own RENDER counter (`p_draw_args`'s `instanceCount`, at the byte
// offset the generator was fed):
//
//   r_base  = WaveReadLaneFirst(InterlockedAdd(additive.instanceCount, r_count))
//   r_pos   = r_base + r_lane
//
// EXACTNESS: reservations from one `InterlockedAdd` counter are contiguous and disjoint, so the
// multiset of `(base, count)` pairs partitions `[0, sum)` exactly and the counter's final value is
// the sum -- independent of the order in which waves retire, because integer addition is
// commutative. That is why NO `InterlockedMax` and no mirror is needed (plan M1), and plan gate
// #14 asserts this module carries ZERO `OpAtomicUMax`.
//
// P0 is ADDITIVE-ONLY, so the blend-class select is a compile-time constant and `r_count`/`r_lane`
// are exactly `w_count`/`w_lane`. They are spelled as their own names anyway: P2's alpha class
// makes them different numbers, and the seam is where the reader needs to see it.
//
// # The atomic budget, per WAVE (plan D5)
//
//   all dying                     -> 1     (dead_count)
//   all surviving, one class      -> 2     (alive_count_next, additive.instanceCount)
//   mixed survive/die             -> 3     (+ dead_count)
//
// At 1M survivors that is ~62 500 ops ~= 32 us, against ~0.5 ms for the naive per-lane form.
//
// The `-D SDF_COLLIDE_STATS` module DELIBERATELY EXCEEDS that budget -- 1-2 more per wave per
// substep, i.e. 3-5 per wave at the plan's steady state -- and its manifest row states the
// exception rather than the census being widened to accommodate it: a census that forbids the
// instrument is a census that forbids measuring itself, and a widened bound would stop gating the
// two modules that ship.
//
// # Two counters, not one (plan N3c)
//
// The LIST count lives in `p_counters` (whose frame terminal is an undrained compute write, so
// next frame's kickoff gets a real RAW) and the RENDER counts in `p_draw_args` (whose terminal is
// the indirect fetch, so next frame's kickoff gets a real WAR). `ResSync` cannot express both on
// one resource. They are also genuinely different numbers the moment a second blend class exists.
//
// # The substep loop is WAVE-UNIFORM
//
// `pc.steps` is a push constant, already clamped ONCE on the host (plan M3), so every lane runs
// the same trip count and the loop never diverges. The `min` below is the F25 HANG GUARD against
// a corrupt push constant and nothing else -- it cannot bind on a well-formed frame.
//
// # No `OpFDiv` in this module
//
// Plan gate #14 requires the `particle_rot_advance` span to carry no divide. DXC inlines every
// helper into `%main`, so a per-function opcode scan of the artifact is UNREACHABLE -- there is
// one `OpFunction` header. The decidable form of that requirement is therefore MODULE-WIDE, and
// this module is written to satisfy it: the age normalization multiplies by the reciprocal
// lifetime `particle_emit` stored at spawn, and the group/index math is integer.
//
// The claim is about the BASE artifact. The `-D SDF_COLLIDE` variant `#include`s the frozen
// `sdf_field.hlsli`, whose `smin`/`sd_capsule` carry divides of their own; those are the FIELD's
// bytes, byte-shared with the marcher and the host oracle, and re-spelling them here to dodge an
// opcode count would fork the determinism contract that header exists to hold. Everything the
// PARTICLE side adds under that define is multiply-only -- which is the decidable claim
// `particle_edsl_sync` pins for the variant.
//
// # The `-D SDF_COLLIDE` variant (rung P1, plan D9)
//
// Off by default and STRUCTURALLY absent: with the define undefined DXC never sees the field
// binding, the include, the response leaf or the in-loop block, so the base `.spv` is byte-frozen
// and there is no dark tax to measure (plan F24). Armed, each substep either SKIPS the field or
// evaluates it once:
//
//   travel_l = length(vel) * dt * FIELD_LIPSCHITZ_L      // the most the field value can drop
//   if (cached_d - travel_l > radius_l)  cached_d -= travel_l;          // no evaluation
//   else                                 d = field_distance(pos);       // one evaluation
//                                        if (d < radius) resolve;
//                                        cached_d = d;
//
// # Why the Lipschitz constant MULTIPLIES the travel rather than dividing it
//
// `FIELD_LIPSCHITZ_L` is the worst-case |grad| of `field_distance` (`sdf_field.hlsli`: the IQ
// polynomial smin's blend peaks at sqrt(2) where two unit-gradient fields meet at 90 degrees).
// From |grad f| <= L: f(p + s) >= f(p) - L*s. So a move of `s` world units can cost up to `L*s`
// of REPORTED distance, and the conservative decrement is `travel * L`. Equivalently, in the
// euclidean units the header states its own rule in ("a cone-trace consumer divides the reported
// distance by L"), the test is `cached_d/L - travel > radius`; both sides are scaled by L here so
// every per-substep operation stays a multiply.
//
// Plan D9's one-line pseudocode writes the reciprocal form (`speed*timestep/L`). The two agree
// EXACTLY at L == 1 -- hard-CSG scenes, which is every fixture today -- and diverge only where a
// smooth (k > 0) edit makes the field super-Lipschitz, where the reciprocal form OVER-estimates
// the clearance and can skip a substep in which contact happened. This module implements the
// conservative direction, because the alternative is a tunneling class that no image gate sees.
//
// # The `-D SDF_COLLIDE_STATS` variant (rung P1b) -- the SKIP-RATE INSTRUMENT
//
// Gate #17 measured that the `ZONE_PARTICLE_SIM` armed-vs-disarmed delta, which the plan had named
// as the skip-rate instrument, is DOMINATED by a kernel-level term of the OPPOSITE SIGN at 4-6x the
// row's resolution: at 65 536 alive a strict superset of work runs 20.3% FASTER, and the isolated
// module swap alone is -5.6%. So the skip rate is not recoverable from a timing difference, and
// this variant counts it on the device instead.
//
// It is a THIRD COMPILED MODULE and not a runtime flag, for F24's measured reason (the VB-SV0
// inline detour cost +75% with its feature OFF and no byte gate could see it) and D1's `-D`
// precedent: a runtime-gated atomic span would be paid on every disarmed frame. With the define
// undefined DXC never sees the census, so BOTH shipping modules stay byte-frozen.
//
// The census is D5's wave aggregation VERBATIM -- one ballot taken where the wave is converged,
// folded to ONE `InterlockedAdd` by ONE lane -- and it reads the branch's OWN predicate, emitted
// from one generator input so the two spellings cannot drift.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_sim.comp.hlsl -Fo particle_sim.comp.spv
//   (SDF_COLLIDE variant: add `-D SDF_COLLIDE=1` -Fo particle_sim_sdf.comp.spv)
//   (SDF_COLLIDE_STATS variant: add `-D SDF_COLLIDE=1 -D SDF_COLLIDE_STATS=1` -Fo particle_sim_stats.comp.spv)
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 0, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_counters     read+write (atomic)
//   (0, 2, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_draw_args    read+write (atomic)
//   (0, 3, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_dead         write
//   (0, 4, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_alive_read   read
//   (0, 5, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_alive_write  write
//   (0, 6, STORAGE_BUFFER)  RWStructuredBuffer<ParticleSim>     p_particle     read+write
//   (0, 7, STORAGE_BUFFER)  RWStructuredBuffer<ParticleRender>  p_render       write
//   (0, 9, STORAGE_BUFFER)  StructuredBuffer<EffectParamsGpu>   p_effects      read
//   (0, 10, STORAGE_BUFFER) StructuredBuffer<uint>             Buf            read  [SDF_COLLIDE only]
//
// # Push constants (8 B) -- UNCHANGED by the variant
//
//   [0,4)  uint  steps    -- the host-clamped substep count (plan M3); ONE number, two consumers
//   [4,8)  float timestep -- `ParticleClock`'s CONSTANT dt (plan D6)
//
// The collision tuning is NOT pushed: `collision_radius`, `restitution` and `friction` are
// PER-EFFECT (plan D2's `EffectParamsGpu` already carries all three), so they arrive through the
// row the sim already fetched and the two pipelines share one push range and one layout.

struct SimPush {
    uint  steps;
    float timestep;
};
[[vk::push_constant]] SimPush pc;

// The per-effect row (plan D2, 128 B). `damping` and the rotation multiplier are
// HOST-PRECOMPUTED against the CONSTANT `ParticleClock` timestep (plan D6), which is what
// deletes `exp2` and all trig from the device. `rot_mul_cos`/`rot_mul_sin` are an f32 PAIR,
// not snorm16 (plan K1: a quantized multiplier's magnitude error is a per-effect CONSTANT
// that compounds as (1+d)^n to ~1% over 640 steps; at f32 it is <= 1 ULP).
struct EffectParamsGpu {
    float3 gravity;      float damping;
    float  rot_mul_cos;  float rot_mul_sin;
    uint2  _r0;
    uint4  color_keys;
    uint2  color_times;  uint2 size_keys;
    float  lifetime_min; float lifetime_max; float speed_min; float speed_max;
    float  size_base;    float cone_cos;     float _r1;       float _r2;
    uint   tex_index;    uint  blend_class;  uint  flags;     float collision_radius;
    float  restitution;  float friction;     uint  emitter_shape; uint _r3;
};

// The sim's working set (plan D2, 48 B, AoS). `size0_invlife` packs the spawn size and the
// RECIPROCAL total lifetime as two binary16 halves -- emit pays the one divide, once per
// particle, so the per-frame sim is divide-free. `effect_flags` packs `u16 effect_index |
// u16 flags`. `cached_field_d` is rung P1's Lipschitz cache: seeded 0 at spawn (so the first
// substep always evaluates the field) and maintained by the sim's `-D SDF_COLLIDE` arm --
// untouched, and never read, by the base compile.
struct ParticleSim {
    float3 position; float life_remaining;
    float3 velocity; float cached_field_d;
    uint   color_rgba8;
    uint   size0_invlife;
    uint   effect_flags;
    uint   rot_cs;
};

// The draw's working set (plan D2, 32 B, AoS). Written by the sim at the CLASS-DENSE render
// index; read by the VS at `pc.index_base + pc.index_step * SV_InstanceID`. Ramp resolution
// happens ONCE per particle in the sim rather than 4x per particle in the VS.
struct ParticleRender {
    float3 position; float size;
    uint   color_rgba8;
    uint   rot_cs;
    uint   tex_index;
    uint   flags;
};

[[vk::binding(0, 0)]] RWStructuredBuffer<uint>              p_counters    : register(u0);
[[vk::binding(2, 0)]] RWStructuredBuffer<uint>              p_draw_args   : register(u2);
[[vk::binding(3, 0)]] RWStructuredBuffer<uint>              p_dead        : register(u3);
[[vk::binding(4, 0)]] RWStructuredBuffer<uint>              p_alive_read  : register(u4);
[[vk::binding(5, 0)]] RWStructuredBuffer<uint>              p_alive_write : register(u5);
[[vk::binding(6, 0)]] RWStructuredBuffer<ParticleSim>       p_particle    : register(u6);
[[vk::binding(7, 0)]] RWStructuredBuffer<ParticleRender>    p_render      : register(u7);
[[vk::binding(9, 0)]] StructuredBuffer<EffectParamsGpu>     p_effects     : register(t9);

#ifdef SDF_COLLIDE
// Rung P1 (plan D9). `sdf_field.hlsli`'s INCLUDE CONTRACT requires `Buf` to be declared and in
// scope BEFORE the include -- the field eval reads the packed edit-list header out of it. This
// pass is a strict FIELD-CONSUMER: it CALLS `field_distance`/`sdf_normal` read-only and never
// edits, exactly as `sdf_mesh_shadow.comp.hlsl` does, and it binds the list at the same binding
// number that pass gives its own `Buf`.
//
// The buffer is the engine's ONE edit list -- boot-static and read-only for the whole present loop
// (the same contract the marcher relies on), which is why it needs no framegraph `ResId`, no seed
// row and no barrier, and why arming this variant moves no derived barrier stream.
[[vk::binding(10, 0)]] StructuredBuffer<uint> Buf : register(t0);
#include "sdf_field.hlsli"
#endif

// `ParticleCounters` (plan D2) is one 64-byte line addressed as `uint` WORDS -- a typed
// record cannot be the destination of `InterlockedAdd`. Every index below is a GENERATOR
// INPUT (`emit_particles.rs`), never typed here, so it cannot drift from the host struct.
static const uint CTR_ALIVE_CUR  = 0u;
static const uint CTR_ALIVE_NEXT = 1u;
static const uint CTR_DEAD_COUNT = 2u;
static const uint CTR_DEAD_BASE  = 3u;
static const uint CTR_EMIT_BASE  = 4u;
static const uint CTR_REAL_EMIT  = 5u;
static const uint CTR_CLAMPED    = 6u;

// The additive class's RENDER counter, at the word the generator derived from
// `PARTICLE_ADDITIVE_INSTANCE_COUNT_OFFSET` (4 bytes) -- plan gate #8. The `InterlockedAdd` on it
// yields BOTH this lane's render position and, at retirement, the class's final instance count.
static const uint DRAW_ADDITIVE_INSTANCE_WORD = 1u;

#ifdef SDF_COLLIDE_STATS
// Rung P1b's three census words, at the indices the generator derived from
// `offset_of!(ParticleCounters, ...) / 4`. They were CARVED OUT OF THE PAD of the same 64-byte
// counter line, so no shipping counter moved to make room.
//
// Declared INSIDE the define on purpose: with `SDF_COLLIDE_STATS` undefined DXC never sees these
// three names, which is the same structural absence that keeps `particle_sim.comp.spv` and
// `particle_sim_sdf.comp.spv` byte-frozen across this rung.
//
// They ACCUMULATE from boot and are never cleared -- `particle_kickoff` is ONE module for all three
// sim variants and does not know about them. That is deliberate: the quantity is a RATIO, which is
// frame-count independent, and a per-frame reset would put a writer for a measurement word into a
// shipping shader.
static const uint CTR_WAVES_EVALUATED = 7u;
static const uint CTR_WAVES_SKIPPED   = 8u;
static const uint CTR_LANES_EVALUATED = 9u;
#endif

// `PARTICLE_SUBSTEP_CEILING` (plan M3). The HOST already clamped; this is the F25 hang guard.
static const uint SUBSTEP_CEILING = 64u;

// === GENERATED particle_integrate BEGIN ===
// One explicit-Euler substep (`boyko_shaderdsl::particle::particle_integrate_body`). `damping` is
// host-precomputed against the constant timestep (plan D6), which is what deletes `exp2` here.
void particle_integrate(inout float3 pos, inout float3 vel, inout float life,
                        float3 gravity, float damping, float dt) {
    vel = (vel + gravity * dt) * damping;
    pos = pos + vel * dt;
    life = life - dt;
}
// === GENERATED particle_integrate END ===

// === GENERATED particle_rot_advance BEGIN ===
// The rotation advance (`boyko_shaderdsl::particle::particle_rot_advance_body`): a complex
// multiply against the host-precomputed `(cos w*dt, sin w*dt)` f32 pair, re-quantized to snorm16
// with NO renormalization and NO divide (plan M7/K1).
uint particle_rot_advance(uint rot_cs, float mul_cos, float mul_sin) {
    uint cb = rot_cs + 32768u;
    float rc = ((float)(cb & 65535u) - 32768.0) * 3.051851e-5;
    uint sb = (rot_cs >> 16u) + 32768u;
    float rs = ((float)(sb & 65535u) - 32768.0) * 3.051851e-5;
    float nc = rc * mul_cos - rs * mul_sin;
    float ns = rc * mul_sin + rs * mul_cos;
    float qc = min(max(nc, -1.0), 1.0) * 32767.0 + 65536.5;
    float qs = min(max(ns, -1.0), 1.0) * 32767.0 + 65536.5;
    return ((uint)qc & 65535u) | (((uint)qs & 65535u) << 16u);
}
// === GENERATED particle_rot_advance END ===

// === GENERATED particle_curve_eval BEGIN ===
// The branch-free 4-key ramp over two packed binary16 pairs
// (`boyko_shaderdsl::particle::particle_curve_eval_body`). Evaluated ONCE per particle here
// rather than 4x per particle in the VS -- the larger half of D2's two-record win.
float particle_curve_eval(uint keys_lo, uint keys_hi, float t) {
    float k0 = f16tof32(keys_lo & 65535u);
    float k1 = f16tof32(keys_lo >> 16u);
    float k2 = f16tof32(keys_hi & 65535u);
    float k3 = f16tof32(keys_hi >> 16u);
    float u = clamp(t, 0.0, 1.0) * 3.0;
    float w0 = clamp(u, 0.0, 1.0);
    float w1 = clamp(u - 1.0, 0.0, 1.0);
    float w2 = clamp(u - 2.0, 0.0, 1.0);
    float v0 = lerp(k0, k1, w0);
    float v1 = lerp(v0, k2, w1);
    return lerp(v1, k3, w2);
}
// === GENERATED particle_curve_eval END ===

#ifdef SDF_COLLIDE
// === GENERATED particle_sdf_response BEGIN ===
// Rung P1's contact resolution (`boyko_shaderdsl::particle::particle_sdf_response_body`): plan
// D9's `p += n*(radius - d)` and `v' = (v - v_n)(1 - friction) - v_n*restitution`, where `v_n` is
// the velocity's INWARD component along the field normal. Pure multiply/add plus the one `dot`
// rung E3 added for it, and the `min(., 0.0)` SIGN GATE: on a re-contact frame the particle is
// already moving outward, and un-gated the `-v_n*restitution` term would flip that back inward --
// at restitution 1, a particle inside the shell could never escape. Branchless, one instruction,
// on the rare `d < radius` arm only.
void particle_sdf_response(inout float3 pos, inout float3 vel, float3 normal,
                           float d, float radius, float restitution, float friction) {
    float vn = min(dot(vel, normal), 0.0);
    float3 v_n = normal * vn;
    pos = pos + normal * (radius - d);
    vel = (vel - v_n) * (1.0 - friction) - v_n * restitution;
}
// === GENERATED particle_sdf_response END ===
#endif

[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {
    uint i = tid.x;
    // The SAME field kickoff sized this dispatch from -- one value read twice, never two
    // derivations that have to be kept in agreement. Lanes past it retire BEFORE any wave
    // intrinsic, so they contribute to no ballot.
    if (i >= p_counters[CTR_ALIVE_CUR]) { return; }

    uint slot = p_alive_read[i];
    ParticleSim p = p_particle[slot];
    EffectParamsGpu e = p_effects[p.effect_flags & 65535u];

    float3 pos  = p.position;
    float3 vel  = p.velocity;
    float  life = p.life_remaining;
    uint   rot  = p.rot_cs;

    uint steps = min(pc.steps, SUBSTEP_CEILING);
#ifdef SDF_COLLIDE
    // The Lipschitz cache rides the record's `.w` lane (plan D2). `particle_emit` seeds it 0, so a
    // particle's FIRST substep always evaluates the field and the cache is never read stale.
    float cached_d = p.cached_field_d;
    float radius   = e.collision_radius;
    // The skip test `cached_d/L - travel > radius`, with BOTH sides scaled by L once, here,
    // outside the loop -- `radius` and L are constants for this particle's whole step sequence, so
    // the per-substep work is a multiply and a compare (see the header for the bound's derivation).
    float radius_l = radius * FIELD_LIPSCHITZ_L;
#endif
    [loop]
    for (uint s = 0u; s < steps; ++s) {
        particle_integrate(pos, vel, life, e.gravity, e.damping, pc.timestep);
        rot = particle_rot_advance(rot, e.rot_mul_cos, e.rot_mul_sin);
#ifdef SDF_COLLIDE
        // `particle_integrate` advanced the position by EXACTLY `vel * dt` (the post-damping
        // velocity it just wrote), so this is the displacement itself, not an estimate of it.
        float travel_l = length(vel) * pc.timestep * FIELD_LIPSCHITZ_L;
#ifdef SDF_COLLIDE_STATS
        // RUNG P1b'S SKIP-RATE CENSUS -- the instrument gate #17 proved a timing delta cannot be.
        //
        // D5's wave aggregation, VERBATIM: one ballot, folded to ONE `InterlockedAdd` by ONE lane,
        // with the `> 0u` guard that keeps the count minimal -- the same three moves the retirement
        // block below makes.
        //
        // ⚠️ PRECONDITION: EXACTLY ONE SUBSTEP PER DISPATCH. The wave is converged HERE only on the
        // FIRST iteration. From the second on, this point is reached from the previous iteration's
        // DIVERGENT skip branch, and Vulkan guarantees no reconvergence at a merge block without
        // `VK_KHR_shader_maximal_reconvergence` -- so a still-split wave would elect one leader PER
        // DIVERGENT GROUP and count the same wave-substep more than once, which destroys the
        // denominator `waves_skipped + waves_evaluated` is supposed to be.
        //
        // (Wave-uniform trip count and pre-ballot retirement of out-of-range lanes are both true
        // and NEITHER covers this: uniform iteration counts say nothing about whether the lanes
        // are executing that iteration together.)
        //
        // The host REFUSES to record a census frame at `steps != 1`
        // (`gpu_scene::particle::assert_one_substep_for_the_census`), so this precondition is
        // enforced rather than assumed.
        //
        // Read at WAVE granularity, and the two wave counters are EXCLUSIVE: the skip is a divergent
        // branch, so a wave whose lanes disagree executes BOTH sides and PAID the walk. It therefore
        // counts as EVALUATED, never as both, which is what makes `skipped + evaluated` the
        // wave-substep total and the skip rate a ratio that needs no fourth counter.
        //
        // `lanes_evaluated` is the per-LANE numerator beside it. The gap between the two rates is
        // exactly the wave's incoherence -- the quantity the plan says a per-lane figure hides.
        //
        // The predicate is the branch's OWN, emitted from one generator input (`SDF_SKIP_TEST`):
        // a census counting a decision the shader did not make would be worse than no census.
        uint eval_lanes = WaveActiveCountBits(!(cached_d - travel_l > radius_l));
        if (WaveIsFirstLane()) {
            if (eval_lanes > 0u) {
                InterlockedAdd(p_counters[CTR_WAVES_EVALUATED], 1u);
                InterlockedAdd(p_counters[CTR_LANES_EVALUATED], eval_lanes);
            } else {
                InterlockedAdd(p_counters[CTR_WAVES_SKIPPED], 1u);
            }
        }
#endif
        if (cached_d - travel_l > radius_l) {
            // THE SKIP. The Lipschitz bound proves the collision shell cannot have been reached,
            // so this LANE evaluates no field this substep.
            //
            // THE SAVING IS REALIZED PER WAVE, NOT PER LANE, and the distinction is the whole
            // measurement: this is a DIVERGENT branch, so a wave whose lanes disagree executes
            // BOTH sides and every lane in it pays the ~240-flop edit-list walk. One near particle
            // costs its wave the entire saving. The cache therefore pays off exactly to the degree
            // that nearness is wave-COHERENT -- which the alive-list gather makes the common case
            // (neighbouring list entries are particles spawned together, hence spatially close),
            // but which is a property of the scene and not of this code. A skip rate quoted per
            // lane would overstate the win by the wave's incoherence -- MEASURED at rung P1b:
            // 42.1% per wave against 63.2% per lane on the lab fixture.
            //
            // READ IT OFF THE `-D SDF_COLLIDE_STATS` CENSUS ABOVE, never off a timing delta. This
            // line used to name the `ZONE_PARTICLE_SIM` armed-vs-disarmed delta; gate #17 measured
            // that delta to be dominated by a kernel-level term of the OPPOSITE SIGN at 4-6x the
            // row's own resolution, so it cannot see this branch at all.
            cached_d = cached_d - travel_l;
        } else {
            float d = field_distance(pos);
            if (d < radius) {
                // `sdf_normal` is the frozen central-difference gradient -- SIX more field
                // evaluations, and the reason it is inside the contact branch rather than beside
                // the distance fetch.
                float3 n = sdf_normal(pos);
                particle_sdf_response(pos, vel, n, d, radius, e.restitution, e.friction);
            }
            // The PRE-response value, exactly as plan D9 caches it: after a resolve the particle
            // sits ON the shell, so the next substep must re-evaluate rather than trust a bound
            // taken from where it used to be.
            cached_d = d;
        }
#endif
    }

    bool survives = (life > 0.0);

    // Every wave quantity is computed BEFORE either branch, so the ballots see the full set of
    // in-range lanes exactly as the plan's NORMATIVE block describes them.
    uint w_count = WaveActiveCountBits(survives);
    uint w_lane  = WavePrefixCountBits(survives);
    uint d_count = WaveActiveCountBits(!survives);
    uint d_lane  = WavePrefixCountBits(!survives);
    // P0 is additive-only: the class predicate is the compile-time `true`, so the RENDER
    // reservation is the LIST reservation's twin. P2 gives them different predicates.
    uint r_count = w_count;
    uint r_lane  = w_lane;

    uint w_base_raw = 0u;
    uint r_base_raw = 0u;
    uint d_base_raw = 0u;
    if (WaveIsFirstLane()) {
        // The `> 0u` guards are what keep an all-surviving wave at TWO atomics and an all-dying
        // wave at ONE (plan D5's budget), rather than three unconditional ones.
        if (w_count > 0u) {
            InterlockedAdd(p_counters[CTR_ALIVE_NEXT], w_count, w_base_raw);
            InterlockedAdd(p_draw_args[DRAW_ADDITIVE_INSTANCE_WORD], r_count, r_base_raw);
        }
        if (d_count > 0u) {
            InterlockedAdd(p_counters[CTR_DEAD_COUNT], d_count, d_base_raw);
        }
    }
    // Broadcast OUTSIDE the leader branch -- every lane needs the reservation base.
    uint w_base = WaveReadLaneFirst(w_base_raw);
    uint r_base = WaveReadLaneFirst(r_base_raw);
    uint d_base = WaveReadLaneFirst(d_base_raw);

    if (!survives) {
        // The dying path returns the slot to the free list at its wave-aggregated position.
        p_dead[d_base + d_lane] = slot;
        return;
    }

    p.position       = pos;
    p.velocity       = vel;
    p.life_remaining = life;
    p.rot_cs         = rot;
#ifdef SDF_COLLIDE
    // The cache is per-particle STATE, not a scratch value: carrying it across the frame edge is
    // what lets a distant particle skip the field for many frames, not merely many substeps.
    p.cached_field_d = cached_d;
#endif
    p_particle[slot] = p;

    float size0    = f16tof32(p.size0_invlife & 65535u);
    float inv_life = f16tof32(p.size0_invlife >> 16u);
    // Normalized age in [0,1]. `inv_life` is the RECIPROCAL emit stored at spawn, so this is a
    // multiply and this module stays free of `OpFDiv` (see the header).
    float age  = 1.0 - life * inv_life;
    float size = size0 * particle_curve_eval(e.size_keys.x, e.size_keys.y, age);

    // The LIST position (shared by both blend classes -- this is what makes an alpha leak
    // structurally impossible, plan M2) and the class-dense RENDER position.
    uint idx   = w_base + w_lane;
    uint r_pos = r_base + r_lane;

    p_alive_write[idx] = slot;

    ParticleRender r;
    r.position    = pos;
    r.size        = size;
    r.color_rgba8 = p.color_rgba8;
    r.rot_cs      = rot;
    r.tex_index   = e.tex_index;
    r.flags       = p.effect_flags >> 16u;
    p_render[r_pos] = r;
}
