// particle_sort_hist.comp -- rung P2 item 3's 256-BIN HISTOGRAM, dispatch 1 of 3
// (`docs/PARTICLES-PLAN.md` Rev 4, decision D10). `DispatchIndirect`, 256 threads.
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. Hand-edits
// fail `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # THE SUBJECT IS THE ALPHA CLASS ONLY, and that is structural rather than an optimisation
//
// The additive class is COMMUTATIVE -- `ONE/ONE` under the 8-bit saturation `lit` imposes gives
// `sat(sat(x) + y) = min(1, x + y)`, which is order-independent (plan D10, research fact R5) -- so
// it needs no sort and is not given one. This pass never touches `p_render[0, additive.count)`.
// The alpha class occupies `p_render[capacity - alpha.count, capacity)`, class-dense and
// DESCENDING (rank `i` at `capacity - 1 - i`), which is what the sim's mirrored render index wrote.
//
// # Why this dispatch is sized from the SIM's indirect block
//
// The element count is `alpha.instanceCount`, which the SIM produces -- so `particle_kickoff`, one
// pass earlier, cannot have written a group count for it. Rather than add a fourth dispatch to
// compute one (plan D10 says THREE), this pass and the scatter re-fetch the SIM's own
// `VkDispatchIndirectCommand`: `ceil(alive_count_cur / 256)` groups. That is exact enough by
// construction, because `alpha.instanceCount <= alive_count_next <= alive_count_cur` -- the M2
// identity -- so the block always covers the class, and the surplus lanes retire on the `i < count`
// test below. It also costs NO new barrier: the sim already read that block this frame, so the
// derived stream is unmoved.
//
// # The atomic budget: at most ONE global `InterlockedAdd` per lane, and typically far fewer
//
// The per-element increments are LDS (`gs_bins`), never global. Exactly one global atomic is issued
// per OCCUPIED bin per group -- at most 256 for a group of 256 elements, and in a real
// scene a few dozen, because neighbouring alive-list entries are particles spawned together and
// therefore at similar depths. This is D5's aggregation applied to a histogram: the shape it
// deletes is one global atomic per element.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_sort_hist.comp.hlsl -Fo particle_sort_hist.comp.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 2,  STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_draw_args   read
//   (0, 7,  STORAGE_BUFFER)  RWStructuredBuffer<ParticleRender>  p_render      read
//   (0, 12, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_sort_bins   read+write (atomic)
//
// # Push constants (16 B)
//
//   [0,12)   float3 cam_eye  -- `ViewUniform::camera_pos`, the SAME eye the draw's DEPTH_LINEAR
//                              arm encodes depth from; the key is a function of it
//   [12,16)  uint   capacity -- CAP, the boot-frozen pool size (plan D14); the alpha class's
//                              mirror `capacity - 1 - i`

struct SortPush {
    float3 cam_eye;
    uint   capacity;
};
[[vk::push_constant]] SortPush pc;

// The draw's working set (plan D2, 32 B, AoS). Written by the sim at the CLASS-DENSE render
// index; read by the VS at `pc.index_base + pc.index_step * SV_InstanceID`. Ramp resolution
// happens ONCE per particle in the sim rather than 4x per particle in the VS.
struct ParticleRender {
    float3 position; float size;
    uint   color_rgba8;
    uint   rot_cs;
    uint   tex_index;
    uint   flags;
};

[[vk::binding(2, 0)]]  RWStructuredBuffer<uint>           p_draw_args : register(u2);
[[vk::binding(7, 0)]]  RWStructuredBuffer<ParticleRender> p_render    : register(u7);
[[vk::binding(12, 0)]] RWStructuredBuffer<uint>           p_sort_bins : register(u12);

// The radix's 512-word scratch, ONE allocation in TWO halves (plan D10's `histogram ->
// 256-bin scan -> scatter`):
//
//   [0, SORT_BINS)                 the HISTOGRAM -- accumulated by `particle_sort_hist`,
//                                  consumed AND RE-ZEROED by `particle_sort_scan`;
//   [SORT_OFFSET_BASE, +SORT_BINS) the running OFFSETS -- written by the scan, consumed
//                                  by the scatter's per-group reservations.
//
// TWO halves and not one array because the scatter DESTROYS what it consumes (each
// reservation advances its bin's offset), so there would be nothing left to zero for the
// next frame. The scan zeroing the histogram half in the same dispatch that reads it is
// what keeps `particle_kickoff` -- one module for every arming -- byte-frozen across this
// rung: no shipping shader learned that the sort exists.
static const uint  SORT_BINS         = 256u;
static const uint  SORT_BIN_MAX      = 255u;
static const float SORT_BIN_MAX_F    = 255.0;
static const uint  SORT_OFFSET_BASE  = 256u;

// The key's range constants. `SORT_INV_LOG_SPAN` is the HOST-computed reciprocal of the
// octave span, so the device multiplies (plan gate #14's no-divide discipline).
static const float SORT_NEAR         = 0.125;
static const float SORT_LOG_NEAR     = -3.0;
static const float SORT_INV_LOG_SPAN = 0.06666667;

// The ALPHA class's live instance count, at the word the generator derived from
// `PARTICLE_ALPHA_INSTANCE_COUNT_OFFSET` (28 bytes) -- plan gate #8. It is the sim's own
// returning `InterlockedAdd` result and therefore the exact length of the range this pass
// sorts.
static const uint  DRAW_ALPHA_INSTANCE_WORD = 7u;

// One bin per lane -- the group width IS the bin count (see the generator's `SORT_BINS` doc), so
// the zero-fill, the accumulate and the flush below are each exactly one element per lane.
groupshared uint gs_bins[SORT_BINS];

// === GENERATED particle_sort_key BEGIN ===
// The 8-bit quantized log-depth key, printed from ONE generator input into this module and into
// `particle_sort_scatter.comp.hlsl`. A key that differed between the two would size a bin from one
// population and fill it from another -- an overrun of that bin's reservation into its neighbour's,
// with a plausible image and no validation message.
uint particle_sort_key(float3 pos, float3 cam_eye) {
    // The EUCLIDEAN camera distance -- the same metric `-D DEPTH_LINEAR`'s depth encode uses, and
    // the only one that is correct for a billboard whose plane faces the camera (a view-space z
    // would order two particles on one sphere around the eye differently, though they occlude
    // identically).
    float d = length(cam_eye - pos);
    // Affine in log2 over [SORT_NEAR, SORT_NEAR * 2^SORT_LOG_SPAN], saturated at both ends. The
    // `max` is what makes `log2` TOTAL, in both of the ways it can fail to be: a particle at the
    // eye's exact position would give log2(0) = -inf, and a NaN position would give NaN. DXC
    // lowers this `max` to `NMax`, whose documented behaviour on a NaN operand is to return the
    // OTHER one -- so a NaN distance becomes SORT_NEAR here and the particle sorts as the nearest
    // (drawn last) rather than poisoning the quantizer. That is the benign direction of a
    // primitive this tree has been bitten by, and it is stated because it is not obvious which
    // direction it takes.
    float t = saturate((log2(max(d, SORT_NEAR)) - SORT_LOG_NEAR) * SORT_INV_LOG_SPAN);
    // INVERTED (see the generator's SORT_KEY_FN doc): bin 0 is the farthest, so ascending order is
    // back-to-front. `+ 0.5` rounds to nearest; `t` is saturated, so the product is in [0, 255.5]
    // and the truncating cast cannot leave the bin range.
    return SORT_BIN_MAX - (uint)(t * SORT_BIN_MAX_F + 0.5);
}
// === GENERATED particle_sort_key END ===

[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID, uint lane : SV_GroupIndex) {
    // EVERY lane of the group reaches both barriers: the range test is an `if` BLOCK and not an
    // early `return`, because a `return` above a `GroupMemoryBarrierWithGroupSync` is undefined and
    // typically a device hang (the same shape `particle_emit`'s cooperative prefix load carries).
    gs_bins[lane] = 0u;
    GroupMemoryBarrierWithGroupSync();

    // The class's live length, CLAMPED ONCE (F25: `robustBufferAccess` is OFF, so an
    // out-of-range fetch is undefined behaviour rather than a zero). Every index below is
    // derived from `count`, so this one `min` is the whole pass's bound: `i < count` then
    // implies `capacity - 1 - i` is in `[capacity - count, capacity)`, which is exactly the
    // range the sim's mirrored write filled.
    uint count = min(p_draw_args[DRAW_ALPHA_INSTANCE_WORD], pc.capacity);

    uint i = tid.x;
    if (i < count) {
        // Rank `i` of the class, at the mirrored slot the sim wrote it to.
        float3 pos = p_render[pc.capacity - 1u - i].position;
        InterlockedAdd(gs_bins[particle_sort_key(pos, pc.cam_eye)], 1u);
    }
    GroupMemoryBarrierWithGroupSync();

    // The FLUSH: one global atomic per occupied bin. The `> 0u` guard is what makes the count
    // proportional to the group's DISTINCT keys rather than to the bin count -- the same guard the
    // sim's retirement block uses for the same reason.
    if (gs_bins[lane] > 0u) {
        InterlockedAdd(p_sort_bins[lane], gs_bins[lane]);
    }
}
