// particle_sort_scatter.comp -- rung P2 item 3's PERMUTATION, dispatch 3 of 3
// (`docs/PARTICLES-PLAN.md` Rev 4, decision D10). `DispatchIndirect`, 256 threads.
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. Hand-edits
// fail `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # What it writes, and why the DRAW does not change
//
// It copies each alpha render record from `p_render` to `p_render_sorted` at its sorted rank, using
// the SAME mirror the sim wrote the class with: rank `r` lands at `capacity - 1 - r`. So the ALPHA
// draw's push pair is still `(capacity - 1, -1)` -- byte-identical to the unsorted arming -- and the
// only thing that changes when the sort is armed is WHICH BUFFER binding 0 of the draw's set 0
// names. D10's "no shader variant" therefore survives this rung untouched: the VS was not
// recompiled, respecialized or given an indirection.
//
// # The scatter is FFX-shaped: per-group bases, never one global atomic per element
//
// Three LDS phases and ONE global atomic per occupied bin per group:
//
//   1. `gs_count[key]++`             -- this group's population per bin            (LDS atomics)
//   2. `InterlockedAdd(offset[b], gs_count[b], gs_base[b])`  for occupied `b` only (GLOBAL, <= 256)
//   3. `gs_rank[key]++`              -- this element's rank within its group's bin (LDS atomics)
//   dst_rank = gs_base[key] + rank
//
// Phase 2 is where the ordering is decided and it is the only global traffic: a group RESERVES a
// contiguous run of each bin it occupies, then fills that run from LDS. The naive form -- one
// `InterlockedAdd` per element on its bin -- is the ~0.5 ms/frame-at-1M shape plan D5 deletes
// everywhere else in this subsystem, and it is deleted here for the same reason.
//
// The record is loaded ONCE, into a register, and serves all three phases plus the store. The key
// is computed once from it. So the per-element traffic is exactly `32 B read + 32 B written`.
//
// # Stability, stated rather than assumed
//
// The permutation is stable WITHIN a group and unspecified ACROSS groups (a group's base depends on
// the order the groups reached phase 2). That is not a defect and cannot become one: two elements
// that share a bin share a quantized depth, so an 8-bit key does not distinguish them and no order
// between them is the right one. The property the sort owes -- and the one the monotonicity
// readback checks -- is that the KEYS are non-decreasing in rank, which holds regardless.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_sort_scatter.comp.hlsl -Fo particle_sort_scatter.comp.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 2,  STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_draw_args      read
//   (0, 7,  STORAGE_BUFFER)  RWStructuredBuffer<ParticleRender>  p_render         read
//   (0, 11, STORAGE_BUFFER)  RWStructuredBuffer<ParticleRender>  p_render_sorted  write
//   (0, 12, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_sort_bins      read+write (atomic)
//
// # Push constants (16 B) -- the SAME block `particle_sort_hist` declares
//
//   [0,12)   float3 cam_eye  -- one eye for both passes, or the two would bin differently
//   [12,16)  uint   capacity -- CAP (plan D14)

struct SortPush {
    float3 cam_eye;
    uint   capacity;
};
[[vk::push_constant]] SortPush pc;

// The draw's working set (plan D2, 32 B, AoS). Written by the sim at the CLASS-DENSE render
// index; read by the VS at `pc.index_base + pc.index_step * SV_InstanceID`. Ramp resolution
// happens ONCE per particle in the sim rather than 4x per particle in the VS.
struct ParticleRender {
    float3 position; float size;
    uint   color_rgba8;
    uint   rot_cs;
    uint   tex_index;
    uint   flags;
};

[[vk::binding(2, 0)]]  RWStructuredBuffer<uint>           p_draw_args     : register(u2);
[[vk::binding(7, 0)]]  RWStructuredBuffer<ParticleRender> p_render        : register(u7);
[[vk::binding(11, 0)]] RWStructuredBuffer<ParticleRender> p_render_sorted : register(u11);
[[vk::binding(12, 0)]] RWStructuredBuffer<uint>           p_sort_bins     : register(u12);

// The radix's 512-word scratch, ONE allocation in TWO halves (plan D10's `histogram ->
// 256-bin scan -> scatter`):
//
//   [0, SORT_BINS)                 the HISTOGRAM -- accumulated by `particle_sort_hist`,
//                                  consumed AND RE-ZEROED by `particle_sort_scan`;
//   [SORT_OFFSET_BASE, +SORT_BINS) the running OFFSETS -- written by the scan, consumed
//                                  by the scatter's per-group reservations.
//
// TWO halves and not one array because the scatter DESTROYS what it consumes (each
// reservation advances its bin's offset), so there would be nothing left to zero for the
// next frame. The scan zeroing the histogram half in the same dispatch that reads it is
// what keeps `particle_kickoff` -- one module for every arming -- byte-frozen across this
// rung: no shipping shader learned that the sort exists.
static const uint  SORT_BINS         = 256u;
static const uint  SORT_BIN_MAX      = 255u;
static const float SORT_BIN_MAX_F    = 255.0;
static const uint  SORT_OFFSET_BASE  = 256u;

// The key's range constants. `SORT_INV_LOG_SPAN` is the HOST-computed reciprocal of the
// octave span, so the device multiplies (plan gate #14's no-divide discipline).
static const float SORT_NEAR         = 0.125;
static const float SORT_LOG_NEAR     = -3.0;
static const float SORT_INV_LOG_SPAN = 0.06666667;

// The ALPHA class's live instance count, at the word the generator derived from
// `PARTICLE_ALPHA_INSTANCE_COUNT_OFFSET` (28 bytes) -- plan gate #8. It is the sim's own
// returning `InterlockedAdd` result and therefore the exact length of the range this pass
// sorts.
static const uint  DRAW_ALPHA_INSTANCE_WORD = 7u;

// One bin per lane, three arrays (see the header's three phases). 3 KB of LDS on a 256-lane
// group -- well inside the 32 KB budget, and the reason the phases are separate arrays rather than
// one reused array is that phase 3 needs `gs_base` to still be live while it counts.
groupshared uint gs_count[SORT_BINS];
groupshared uint gs_base[SORT_BINS];
groupshared uint gs_rank[SORT_BINS];

// === GENERATED particle_sort_key BEGIN ===
// The SAME text `particle_sort_hist.comp.hlsl` carries, printed from one generator input -- see
// that file's copy for why the two must be one spelling.
uint particle_sort_key(float3 pos, float3 cam_eye) {
    // The EUCLIDEAN camera distance -- the same metric `-D DEPTH_LINEAR`'s depth encode uses, and
    // the only one that is correct for a billboard whose plane faces the camera (a view-space z
    // would order two particles on one sphere around the eye differently, though they occlude
    // identically).
    float d = length(cam_eye - pos);
    // Affine in log2 over [SORT_NEAR, SORT_NEAR * 2^SORT_LOG_SPAN], saturated at both ends. The
    // `max` is what makes `log2` TOTAL, in both of the ways it can fail to be: a particle at the
    // eye's exact position would give log2(0) = -inf, and a NaN position would give NaN. DXC
    // lowers this `max` to `NMax`, whose documented behaviour on a NaN operand is to return the
    // OTHER one -- so a NaN distance becomes SORT_NEAR here and the particle sorts as the nearest
    // (drawn last) rather than poisoning the quantizer. That is the benign direction of a
    // primitive this tree has been bitten by, and it is stated because it is not obvious which
    // direction it takes.
    float t = saturate((log2(max(d, SORT_NEAR)) - SORT_LOG_NEAR) * SORT_INV_LOG_SPAN);
    // INVERTED (see the generator's SORT_KEY_FN doc): bin 0 is the farthest, so ascending order is
    // back-to-front. `+ 0.5` rounds to nearest; `t` is saturated, so the product is in [0, 255.5]
    // and the truncating cast cannot leave the bin range.
    return SORT_BIN_MAX - (uint)(t * SORT_BIN_MAX_F + 0.5);
}
// === GENERATED particle_sort_key END ===

[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID, uint lane : SV_GroupIndex) {
    gs_count[lane] = 0u;
    GroupMemoryBarrierWithGroupSync();

    // The class's live length, CLAMPED ONCE (F25: `robustBufferAccess` is OFF, so an
    // out-of-range fetch is undefined behaviour rather than a zero). Every index below is
    // derived from `count`, so this one `min` is the whole pass's bound: `i < count` then
    // implies `capacity - 1 - i` is in `[capacity - count, capacity)`, which is exactly the
    // range the sim's mirrored write filled.
    uint count = min(p_draw_args[DRAW_ALPHA_INSTANCE_WORD], pc.capacity);

    uint i = tid.x;
    bool live = (i < count);
    // Zero-initialized so the `live == false` lanes carry a defined record through the barriers
    // below; they store nothing, so the value is never observed.
    ParticleRender r = (ParticleRender)0;
    uint key = 0u;
    if (live) {
        // ONE load. The record then serves phase 1, phase 3 and the store, so the pass reads
        // `p_render` exactly once per element (see the header's traffic line).
        r   = p_render[pc.capacity - 1u - i];
        key = particle_sort_key(r.position, pc.cam_eye);
        InterlockedAdd(gs_count[key], 1u);
    }
    GroupMemoryBarrierWithGroupSync();

    // PHASE 2 -- the only global traffic. `> 0u` keeps it proportional to the group's DISTINCT
    // keys; the returning value is where this group's run of bin `lane` starts.
    uint my_count = gs_count[lane];
    uint my_base  = 0u;
    if (my_count > 0u) {
        InterlockedAdd(p_sort_bins[SORT_OFFSET_BASE + lane], my_count, my_base);
    }
    gs_base[lane] = my_base;
    gs_rank[lane] = 0u;
    GroupMemoryBarrierWithGroupSync();

    if (live) {
        // PHASE 3 -- this element's rank inside its group's run, from an LDS atomic.
        uint rank;
        InterlockedAdd(gs_rank[key], 1u, rank);
        // The F25 guard, on the MIRROR and not on the source, for the sim's own asymmetric reason:
        // over `uint` a rank past `capacity` makes `capacity - 1 - rank` UNDERFLOW to ~0xFFFFFFFF,
        // an unbounded out-of-range store with `robustBufferAccess` OFF. It can only be reached if
        // the bins already disagree with `alpha.instanceCount`, i.e. if the M2 identity is broken.
        uint dst_rank = min(gs_base[key] + rank, pc.capacity - 1u);
        p_render_sorted[pc.capacity - 1u - dst_rank] = r;
    }
}
