// particle_draw.vs -- the GPU particle system's BILLBOARD EXPANSION
// (`docs/PARTICLES-PLAN.md` Rev 4, algorithm A5). One `DrawIndexedIndirect`, 4 vertices and 6
// indices per instance.
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. The
// `// === GENERATED particle_billboard_corner BEGIN/END ===` span is MACHINE-EMITTED; a hand-edit
// fails `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # The render index is a PUSH-CONSTANT AFFINE, not `firstInstance`
//
// `firstInstance` MUST be 0 (F5b: `drawIndirectFirstInstance` is not enabled on this device and a
// nonzero value there is a silent corruption class), so the two blend classes P2 adds cannot be
// distinguished by it. Instead the VS computes `pc.index_base + pc.index_step * SV_InstanceID`:
// `(0, +1)` for additive -- the IDENTITY at P0, i.e. a strictly sequential read with no
// indirection -- and `(CAP-1, -1)` for P2's alpha class, which walks the same buffer from the
// far end. One pipeline, two push values, no shader variant.
//
// # No trig, no renormalization (plan M7)
//
// The rotation arrives as a stored `(cos, sin)` snorm16 pair the sim advanced by complex
// multiplication, so the corner placement is pure multiply/add. R9 is closed by construction:
// `instanceCount` is the sim's live survivor count, never CAP.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T vs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_draw.vs.hlsl -Fo particle_draw.vs.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 0, STORAGE_BUFFER)  StructuredBuffer<ParticleRender>  p_render  read  (VERTEX)
//   (0, 1, UNIFORM_BUFFER)  cbuffer Camera                              read  (VERTEX)
//   (1, *, ...)                                               the bindless texture set the
//                                                             FRAGMENT half declares
//
// # Push constants (72 B, VERTEX stage; the graphics range is separate from the shared COMPUTE one)
//
//   [0,64)   float4x4 view_proj   -- the path's own view-projection rows
//   [64,68)  uint     index_base  -- 0 at P0 (additive); CAP-1 for P2's alpha slot
//   [68,72)  int      index_step  -- +1 at P0 (additive); -1 for P2's alpha slot

struct ParticleDrawPush {
    float4x4 view_proj;
    uint     index_base;
    int      index_step;
};
[[vk::push_constant]] ParticleDrawPush pc;

// The draw's working set (plan D2, 32 B, AoS). Written by the sim at the CLASS-DENSE render
// index; read by the VS at `pc.index_base + pc.index_step * SV_InstanceID`. Ramp resolution
// happens ONCE per particle in the sim rather than 4x per particle in the VS.
struct ParticleRender {
    float3 position; float size;
    uint   color_rgba8;
    uint   rot_cs;
    uint   tex_index;
    uint   flags;
};

[[vk::binding(0, 0)]] StructuredBuffer<ParticleRender> p_render : register(t0);

// binding 1: the extent/camera UNIFORM block -- the SAME 80-byte shape every other consumer
// declares. This pass reads `cam_right`/`cam_up` (the billboard basis) and nothing else.
[[vk::binding(1, 0)]] cbuffer Camera {
    uint   count;
    uint   img_w_raw;
    uint   img_h_raw;
    uint   camera_mode;
    float4 cam_eye;
    float4 cam_forward;
    float4 cam_right;
    float4 cam_up;
};

// The RGBA8 -> UNORM scale. A constant EXPRESSION, folded by DXC, so no divide reaches the module.
static const float UNORM_SCALE = 1.0 / 255.0;

struct VsOut {
    float4 position  : SV_Position;
    float2 uv        : TEXCOORD0;
    nointerpolation float4 color : COLOR0;
    nointerpolation uint tex_index : TEXIDX;
};

// === GENERATED particle_billboard_corner BEGIN ===
// The corner placement (`boyko_shaderdsl::particle::particle_billboard_corner_body`): decode the
// stored `(cos, sin)` pair, rotate and scale the corner offset, ride the camera basis.
void particle_billboard_corner(float3 center, float3 cam_right, float3 cam_up,
                               float cx, float cy, float size, uint rot_cs,
                               out float3 world_pos) {
    uint cb = rot_cs + 32768u;
    float rc = ((float)(cb & 65535u) - 32768.0) * 3.051851e-5;
    uint sb = (rot_cs >> 16u) + 32768u;
    float rs = ((float)(sb & 65535u) - 32768.0) * 3.051851e-5;
    float rx = (cx * rc - cy * rs) * size;
    float ry = (cx * rs + cy * rc) * size;
    world_pos = center + cam_right * rx + cam_up * ry;
}
// === GENERATED particle_billboard_corner END ===

VsOut main(uint vid : SV_VertexID, uint iid : SV_InstanceID) {
    // The affine render index. At P0 this is the identity `0 + 1 * iid`, so the read is exactly
    // sequential and the record stream is consumed at ~80% cache-line utilization (plan D2).
    uint r_index = uint((int)pc.index_base + pc.index_step * (int)iid);
    ParticleRender r = p_render[r_index];

    // The quad corner, from the 6-index / 4-vertex index buffer's vertex ids: bit 0 selects +x,
    // bit 1 selects +y, so the four vertices are the corners of a unit quad centred on the
    // particle. The offsets are the leaf's INPUT, which keeps the vertex-id convention here and
    // out of the generated span.
    float cx = ((vid & 1u) != 0u) ?  0.5 : -0.5;
    float cy = ((vid & 2u) != 0u) ?  0.5 : -0.5;

    float3 world;
    particle_billboard_corner(r.position, cam_right.xyz, cam_up.xyz, cx, cy, r.size, r.rot_cs,
                              world);

    VsOut o;
    o.position = mul(pc.view_proj, float4(world, 1.0));
    // `cy` runs +y UP in world space while `v` runs DOWN in texture space, hence the flip.
    o.uv = float2(cx + 0.5, 0.5 - cy);
    // The packed RGBA8 the sim resolved, unpacked once per vertex. A record DECODE, in the same
    // class as the index arithmetic above -- no ramp math survives into this stage.
    o.color = float4((float)( r.color_rgba8        & 255u),
                     (float)((r.color_rgba8 >>  8u) & 255u),
                     (float)((r.color_rgba8 >> 16u) & 255u),
                     (float)((r.color_rgba8 >> 24u) & 255u)) * UNORM_SCALE;
    o.tex_index = r.tex_index;
    return o;
}
