// particle_emit.comp -- the GPU particle system's SPAWN pass
// (`docs/PARTICLES-PLAN.md` Rev 4, algorithm A3 / decision D8). `DispatchIndirect`, 256 threads.
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. The
// `// === GENERATED <name> BEGIN/END ===` spans are MACHINE-EMITTED from `boyko_shaderdsl`'s
// generic leaf bodies; a hand-edit of any of them fails
// `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # ZERO global atomics, and why that is structural
//
// The one-thread kickoff already pre-decremented `dead_count` and pre-incremented
// `alive_count_cur`, publishing `dead_base` and `emit_append_base`. So lane `gid` computes BOTH
// of its indices arithmetically -- `slot = p_dead[dead_base + gid]`, `pos = emit_append_base +
// gid` -- and this pass performs no `InterlockedAdd` of any kind. Plan gate #14 asserts the
// committed module carries zero atomic opcodes, so a future edit that reaches for one reds here.
//
// # The prefix orders LANES ONLY (D8)
//
// `first_spawn` is a CPU prefix sum over the frame's emitters; the binary search below maps
// `gid -> emitter index` and nothing else. The slot comes from the dead list and the list
// position from the append base -- three independent indexings, none assuming structure in
// another. That is what makes the pass correct against a SHUFFLED `p_dead`, which is the state
// the dead stack is in from frame 2 onward.
//
// # No dead-stack race
//
// Emit only READS `p_dead`; only the sim pushes to it, in a later pass with a derived barrier
// between. The classic concurrent push/pop race is structurally impossible here (plan D3).
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_emit.comp.hlsl -Fo particle_emit.comp.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 0, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_counters    read
//   (0, 3, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_dead        read
//   (0, 4, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_alive_read  write
//   (0, 6, STORAGE_BUFFER)  RWStructuredBuffer<ParticleSim>     p_particle    write
//   (0, 8, STORAGE_BUFFER)  StructuredBuffer<EmitRequestGpu>    p_emit_req    read
//   (0, 9, STORAGE_BUFFER)  StructuredBuffer<EffectParamsGpu>   p_effects     read
//
// # Push constants (8 B)
//
//   [0,4)  uint emitter_count -- <= MAX_EMITTERS, the host's release-present clamp (plan D15)
//   [4,8)  uint frame_index   -- the per-frame half of the spawn seed; the per-emitter half is
//                               `EmitRequestGpu::rng_seed`, a CONSTANT (plan D2)

struct EmitPush {
    uint emitter_count;
    uint frame_index;
};
[[vk::push_constant]] EmitPush pc;

// The per-emitter spawn request (plan D2, 64 B). `first_spawn` is the CPU prefix sum (D8).
struct EmitRequestGpu {
    float3 origin;  uint effect_index;
    float3 basis_x; uint spawn_count;
    float3 basis_y; uint first_spawn;
    float3 basis_z; uint rng_seed;
};

// The per-effect row (plan D2, 128 B). `damping` and the rotation multiplier are
// HOST-PRECOMPUTED against the CONSTANT `ParticleClock` timestep (plan D6), which is what
// deletes `exp2` and all trig from the device. `rot_mul_cos`/`rot_mul_sin` are an f32 PAIR,
// not snorm16 (plan K1: a quantized multiplier's magnitude error is a per-effect CONSTANT
// that compounds as (1+d)^n to ~1% over 640 steps; at f32 it is <= 1 ULP).
struct EffectParamsGpu {
    float3 gravity;      float damping;
    float  rot_mul_cos;  float rot_mul_sin;
    uint2  _r0;
    uint4  color_keys;
    uint2  color_times;  uint2 size_keys;
    float  lifetime_min; float lifetime_max; float speed_min; float speed_max;
    float  size_base;    float cone_cos;     float _r1;       float _r2;
    uint   tex_index;    uint  blend_class;  uint  flags;     float collision_radius;
    float  restitution;  float friction;     uint  emitter_shape; uint _r3;
};

// The sim's working set (plan D2, 48 B, AoS). `size0_invlife` packs the spawn size and the
// RECIPROCAL total lifetime as two binary16 halves -- emit pays the one divide, once per
// particle, so the per-frame sim is divide-free. `effect_flags` packs `u16 effect_index |
// u16 flags`. `cached_field_d` is rung P1's Lipschitz cache: seeded 0 at spawn (so the first
// substep always evaluates the field) and maintained by the sim's `-D SDF_COLLIDE` arm --
// untouched, and never read, by the base compile.
struct ParticleSim {
    float3 position; float life_remaining;
    float3 velocity; float cached_field_d;
    uint   color_rgba8;
    uint   size0_invlife;
    uint   effect_flags;
    uint   rot_cs;
};

[[vk::binding(0, 0)]] RWStructuredBuffer<uint>              p_counters   : register(u0);
[[vk::binding(3, 0)]] RWStructuredBuffer<uint>              p_dead       : register(u3);
[[vk::binding(4, 0)]] RWStructuredBuffer<uint>              p_alive_read : register(u4);
[[vk::binding(6, 0)]] RWStructuredBuffer<ParticleSim>       p_particle   : register(u6);
[[vk::binding(8, 0)]] StructuredBuffer<EmitRequestGpu>      p_emit_req   : register(t8);
[[vk::binding(9, 0)]] StructuredBuffer<EffectParamsGpu>     p_effects    : register(t9);

// `ParticleCounters` (plan D2) is one 64-byte line addressed as `uint` WORDS -- a typed
// record cannot be the destination of `InterlockedAdd`. Every index below is a GENERATOR
// INPUT (`emit_particles.rs`), never typed here, so it cannot drift from the host struct.
static const uint CTR_ALIVE_CUR  = 0u;
static const uint CTR_ALIVE_NEXT = 1u;
static const uint CTR_DEAD_COUNT = 2u;
static const uint CTR_DEAD_BASE  = 3u;
static const uint CTR_EMIT_BASE  = 4u;
static const uint CTR_REAL_EMIT  = 5u;
static const uint CTR_CLAMPED    = 6u;

// The `first_spawn` prefix lives in LDS for the search: one coalesced 1 KB load, one barrier,
// then eight LDS reads per lane instead of eight global ones.
static const uint MAX_EMITTERS   = 256u;
static const uint SEARCH_STEPS   = 8u;
static const uint SEARCH_HALF    = 128u;
static const uint SPAWN_SENTINEL = 4294967295u;

// The stored `(cos, sin)` pattern for zero rotation: `cos = +1` quantizes to 32767, `sin = 0` to
// 0 (plan D2's `rot_cs`). Every particle spawns unrotated.
static const uint ROT_IDENTITY = 32767u;

groupshared uint gs_first_spawn[MAX_EMITTERS];

// === GENERATED particle_rng BEGIN ===
// The 32-bit PCG hash (`boyko_shaderdsl::particle::particle_rng_body`). Bit-exact by
// construction: pure integer arithmetic, identical on the CPU oracle and the device.
uint particle_rng(uint state) {
    uint s = state * 747796405u + 2891336453u;
    uint shift = (s >> 28u) + 4u;
    uint word = ((s >> shift) ^ s) * 277803737u;
    return (word >> 22u) ^ word;
}
// === GENERATED particle_rng END ===

// === GENERATED particle_spawn_state BEGIN ===
// The trig-free, divide-free cone sample + speed/lifetime draw
// (`boyko_shaderdsl::particle::particle_spawn_state_body`): an elliptical grid mapping from the
// unit square onto the disc, then a Lambert azimuthal equal-area lift onto the cap `z >= cone_cos`
// whose unit length is an ALGEBRAIC identity rather than a normalization.
void particle_spawn_state(float3 basis_x, float3 basis_y, float3 basis_z,
                          float cone_cos, float speed_min, float speed_max,
                          float life_min, float life_max,
                          uint r_dir_x, uint r_dir_y, uint r_speed, uint r_life,
                          out float3 velocity, out float life) {
    float ux = (float)(r_dir_x >> 8u) * 5.9604645e-8;
    float uy = (float)(r_dir_y >> 8u) * 5.9604645e-8;
    float us = (float)(r_speed >> 8u) * 5.9604645e-8;
    float ul = (float)(r_life >> 8u) * 5.9604645e-8;
    float a = ux * 2.0 - 1.0;
    float b = uy * 2.0 - 1.0;
    float px = a * sqrt(1.0 - 0.5 * b * b);
    float py = b * sqrt(1.0 - 0.5 * a * a);
    float cap = 2.0 - 2.0 * cone_cos;
    float q = (px * px + py * py) * cap;
    float sr = sqrt(max(1.0 - 0.25 * q, 0.0)) * sqrt(cap);
    float sx = sr * px;
    float sy = sr * py;
    float dz = 1.0 - 0.5 * q;
    float speed = lerp(speed_min, speed_max, us);
    velocity = (basis_x * sx + basis_y * sy + basis_z * dz) * speed;
    life = lerp(life_min, life_max, ul);
}
// === GENERATED particle_spawn_state END ===

[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID, uint lane : SV_GroupIndex) {
    // The cooperative prefix load. EVERY lane of the group reaches the barrier -- the range guard
    // is BELOW it, because a `return` above a `GroupMemoryBarrierWithGroupSync` is undefined and
    // typically a device hang.
    //
    // The out-of-range arm reads `p_emit_req[lane]` eagerly if DXC lowers the ternary to a select
    // rather than a branch. That is IN BOUNDS: the request buffer holds MAX_EMITTERS entries and
    // `lane < MAX_EMITTERS` by the group width, so an eager load reads an indeterminate VALUE at a
    // valid address and the select discards it. (Group width == MAX_EMITTERS is what makes the
    // one-entry-per-lane load exact; both are generator inputs.)
    gs_first_spawn[lane] = (lane < pc.emitter_count) ? p_emit_req[lane].first_spawn
                                                     : SPAWN_SENTINEL;
    GroupMemoryBarrierWithGroupSync();

    uint gid = tid.x;
    if (gid >= p_counters[CTR_REAL_EMIT]) { return; }

    // The 8-step BRANCHLESS binary search for the last emitter whose `first_spawn <= gid`.
    // `gs_first_spawn[0]` is 0 for a non-empty frame (a prefix sum starts at 0), so `lo` always
    // lands on a real emitter; the sentinel makes every slot past `emitter_count` unselectable.
    // `lo + (SEARCH_HALF >> s)` sums to MAX_EMITTERS-1 over the whole descent, so the probe index
    // is in range at every step and needs no bound test.
    uint lo = 0u;
    [unroll]
    for (uint s = 0u; s < SEARCH_STEPS; ++s) {
        uint probe = lo + (SEARCH_HALF >> s);
        lo = (gs_first_spawn[probe] <= gid) ? probe : lo;
    }

    EmitRequestGpu req = p_emit_req[lo];
    // `effect_index` is host-clamped below MAX_EFFECTS, which is the effect table's element count.
    EffectParamsGpu e = p_effects[req.effect_index];

    // The two independent indexings kickoff published (plan D8). Neither assumes anything about
    // the other, and neither assumes anything about the ORDER of the dead list.
    uint slot = p_dead[p_counters[CTR_DEAD_BASE] + gid];
    uint pos  = p_counters[CTR_EMIT_BASE] + gid;

    // The spawn seed mixes the emitter's CONSTANT `rng_seed`, the lane, and the frame -- so two
    // emitters spawning at the same lane on the same frame decorrelate, and one emitter's lane
    // decorrelates across frames. The chain then supplies four decorrelated words.
    uint r0 = particle_rng(req.rng_seed ^ gid ^ pc.frame_index);
    uint r1 = particle_rng(r0);
    uint r2 = particle_rng(r1);
    uint r3 = particle_rng(r2);

    float3 velocity;
    float  life;
    particle_spawn_state(req.basis_x, req.basis_y, req.basis_z, e.cone_cos,
                         e.speed_min, e.speed_max, e.lifetime_min, e.lifetime_max,
                         r0, r1, r2, r3, velocity, life);

    ParticleSim p;
    p.position        = req.origin;
    p.life_remaining  = life;
    p.velocity        = velocity;
    p.cached_field_d  = 0.0;
    p.color_rgba8     = e.color_keys.x;
    // The ONE divide in the whole subsystem's per-particle path, paid ONCE at spawn: the sim then
    // normalizes age by a MULTIPLY, so `particle_sim` carries no `OpFDiv` at all (plan gate #14).
    p.size0_invlife   = f32tof16(e.size_base) | (f32tof16(1.0 / life) << 16u);
    p.effect_flags    = req.effect_index | ((e.flags & 65535u) << 16u);
    p.rot_cs          = ROT_IDENTITY;

    p_particle[slot]    = p;
    p_alive_read[pos]   = slot;
}
