// particle_sort_scan.comp -- rung P2 item 3's 256-BIN SCAN, dispatch 2 of 3
// (`docs/PARTICLES-PLAN.md` Rev 4, decision D10). ONE group of 256 threads, dispatched
// DIRECTLY.
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. Hand-edits
// fail `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # One group, and therefore no second scan level
//
// A 256-element exclusive prefix sum fits one workgroup exactly (the group width IS the bin count),
// so the whole scan is 8 Hillis-Steele steps in LDS with no partial-sum buffer, no
// spine pass and no third dispatch. That is the entire reason D10 chose an 8-bit digit: a wider key
// would need `numGroups x bins` of per-group histograms and the multi-level scan FFX carries for
// them.
//
// # THE RE-ZERO IS PART OF THIS PASS, and it is what keeps `particle_kickoff` byte-frozen
//
// Lane `b` reads `p_sort_bins[b]` into a register at the top and writes `0u` back at the bottom.
// No other lane touches that word, so no barrier separates the two -- and the histogram half is
// therefore clean for the NEXT frame without any other shader learning that the sort exists. The
// alternative (kickoff clearing the bins) would have needed a `-D` variant of a module that ships in
// every configuration, i.e. a tenth artifact to zero 1 KB.
//
// Frame 0 works because the boot fill zeroes every particle buffer, so the invariant "the histogram
// half is zero when `particle_sort_hist` runs" holds from the first frame and is re-established by
// this pass on every one after it.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_sort_scan.comp.hlsl -Fo particle_sort_scan.comp.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 12, STORAGE_BUFFER)  RWStructuredBuffer<uint>  p_sort_bins  read+write
//
//   The ONLY resource this pass touches. It carries no atomic at all -- one lane owns one bin
//   through the whole dispatch.
//
// # Push constants
//
//   NONE IN THE SHADER. The scan is a pure reduction over a fixed-size array: it needs neither the
//   capacity nor the camera, and a range it does not read cannot drift from the one the other two
//   passes do. Its pipeline LAYOUT still carries the family's 16-byte range host-side, because the
//   RHI has no zero-range form -- a declared range no shader references is legal Vulkan, and the
//   recorder emits no `vkCmdPushConstants` for this pass.

[[vk::binding(12, 0)]] RWStructuredBuffer<uint> p_sort_bins : register(u12);

// The radix's 512-word scratch, ONE allocation in TWO halves (plan D10's `histogram ->
// 256-bin scan -> scatter`):
//
//   [0, SORT_BINS)                 the HISTOGRAM -- accumulated by `particle_sort_hist`,
//                                  consumed AND RE-ZEROED by `particle_sort_scan`;
//   [SORT_OFFSET_BASE, +SORT_BINS) the running OFFSETS -- written by the scan, consumed
//                                  by the scatter's per-group reservations.
//
// TWO halves and not one array because the scatter DESTROYS what it consumes (each
// reservation advances its bin's offset), so there would be nothing left to zero for the
// next frame. The scan zeroing the histogram half in the same dispatch that reads it is
// what keeps `particle_kickoff` -- one module for every arming -- byte-frozen across this
// rung: no shipping shader learned that the sort exists.
static const uint  SORT_BINS         = 256u;
static const uint  SORT_BIN_MAX      = 255u;
static const float SORT_BIN_MAX_F    = 255.0;
static const uint  SORT_OFFSET_BASE  = 256u;

// The key's range constants. `SORT_INV_LOG_SPAN` is the HOST-computed reciprocal of the
// octave span, so the device multiplies (plan gate #14's no-divide discipline).
static const float SORT_NEAR         = 0.125;
static const float SORT_LOG_NEAR     = -3.0;
static const float SORT_INV_LOG_SPAN = 0.06666667;

// The ALPHA class's live instance count, at the word the generator derived from
// `PARTICLE_ALPHA_INSTANCE_COUNT_OFFSET` (28 bytes) -- plan gate #8. It is the sim's own
// returning `InterlockedAdd` result and therefore the exact length of the range this pass
// sorts.
static const uint  DRAW_ALPHA_INSTANCE_WORD = 7u;

groupshared uint gs_scan[SORT_BINS];

[numthreads(256, 1, 1)]
void main(uint lane : SV_GroupIndex) {
    // This lane's OWN bin population, held in a register across the scan so the exclusive result is
    // `inclusive - own` and no second LDS array (or shifted store) is needed.
    uint own = p_sort_bins[lane];
    gs_scan[lane] = own;
    GroupMemoryBarrierWithGroupSync();

    // Hillis-Steele INCLUSIVE scan, 8 steps. The read and the write are separated by
    // barriers on BOTH sides: without the second one a fast lane could overwrite `gs_scan[lane]`
    // while a slower lane at `lane + off` still needs the pre-step value.
    [unroll]
    for (uint off = 1u; off < SORT_BINS; off <<= 1) {
        uint add = (lane >= off) ? gs_scan[lane - off] : 0u;
        GroupMemoryBarrierWithGroupSync();
        gs_scan[lane] = gs_scan[lane] + add;
        GroupMemoryBarrierWithGroupSync();
    }

    // The offsets half: where bin `lane`'s first element lands. Bin 0 is the FARTHEST (the key is
    // inverted), so rank 0 -- offset 0 -- is the farthest particle, which the ALPHA draw's
    // `(capacity - 1, -1)` affine fetches FIRST. Back-to-front, with no reverse anywhere.
    p_sort_bins[SORT_OFFSET_BASE + lane] = gs_scan[lane] - own;
    // ...and the histogram half, clean for next frame (see the header).
    p_sort_bins[lane] = 0u;
}
