// particle_sim.comp -- the GPU particle system's HOT LOOP
// (`docs/PARTICLES-PLAN.md` Rev 4, algorithm A4 / decisions D3, D5). `DispatchIndirect`, 256
// threads, O(alive_count_cur).
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. The
// `// === GENERATED <name> BEGIN/END ===` spans are MACHINE-EMITTED from `boyko_shaderdsl`'s
// generic leaf bodies; a hand-edit of any of them fails
// `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # The wave-level atomic mechanism -- the plan's NORMATIVE block, symbol for symbol
//
//   w_count = WaveActiveCountBits(survives)      // survivors in THIS wave        (per-wave)
//   w_lane  = WavePrefixCountBits(survives)      // this lane's rank among them   (per-lane)
//   if (WaveIsFirstLane())
//       w_base_raw = InterlockedAdd(alive_count_next, w_count)     // returns the OLD value
//   w_base  = WaveReadLaneFirst(w_base_raw)      // the wave's LIST reservation base
//   idx     = w_base + w_lane                    // this lane's LIST position
//
// and, on the additive class's own RENDER counter (`p_draw_args`'s `instanceCount`, at the byte
// offset the generator was fed):
//
//   r_base  = WaveReadLaneFirst(InterlockedAdd(additive.instanceCount, r_count))
//   r_pos   = r_base + r_lane
//
// EXACTNESS: reservations from one `InterlockedAdd` counter are contiguous and disjoint, so the
// multiset of `(base, count)` pairs partitions `[0, sum)` exactly and the counter's final value is
// the sum -- independent of the order in which waves retire, because integer addition is
// commutative. That is why NO `InterlockedMax` and no mirror is needed (plan M1), and plan gate
// #14 asserts this module carries ZERO `OpAtomicUMax`.
//
// P0 is ADDITIVE-ONLY, so the blend-class select is a compile-time constant and `r_count`/`r_lane`
// are exactly `w_count`/`w_lane`. They are spelled as their own names anyway: P2's alpha class
// makes them different numbers, and the seam is where the reader needs to see it.
//
// # The atomic budget, per WAVE (plan D5)
//
//   all dying                     -> 1     (dead_count)
//   all surviving, one class      -> 2     (alive_count_next, additive.instanceCount)
//   mixed survive/die             -> 3     (+ dead_count)
//
// At 1M survivors that is ~62 500 ops ~= 32 us, against ~0.5 ms for the naive per-lane form.
//
// # Two counters, not one (plan N3c)
//
// The LIST count lives in `p_counters` (whose frame terminal is an undrained compute write, so
// next frame's kickoff gets a real RAW) and the RENDER counts in `p_draw_args` (whose terminal is
// the indirect fetch, so next frame's kickoff gets a real WAR). `ResSync` cannot express both on
// one resource. They are also genuinely different numbers the moment a second blend class exists.
//
// # The substep loop is WAVE-UNIFORM
//
// `pc.steps` is a push constant, already clamped ONCE on the host (plan M3), so every lane runs
// the same trip count and the loop never diverges. The `min` below is the F25 HANG GUARD against
// a corrupt push constant and nothing else -- it cannot bind on a well-formed frame.
//
// # No `OpFDiv` in this module
//
// Plan gate #14 requires the `particle_rot_advance` span to carry no divide. DXC inlines every
// helper into `%main`, so a per-function opcode scan of the artifact is UNREACHABLE -- there is
// one `OpFunction` header. The decidable form of that requirement is therefore MODULE-WIDE, and
// this module is written to satisfy it: the age normalization multiplies by the reciprocal
// lifetime `particle_emit` stored at spawn, and the group/index math is integer.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_sim.comp.hlsl -Fo particle_sim.comp.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 0, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_counters     read+write (atomic)
//   (0, 2, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_draw_args    read+write (atomic)
//   (0, 3, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_dead         write
//   (0, 4, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_alive_read   read
//   (0, 5, STORAGE_BUFFER)  RWStructuredBuffer<uint>            p_alive_write  write
//   (0, 6, STORAGE_BUFFER)  RWStructuredBuffer<ParticleSim>     p_particle     read+write
//   (0, 7, STORAGE_BUFFER)  RWStructuredBuffer<ParticleRender>  p_render       write
//   (0, 9, STORAGE_BUFFER)  StructuredBuffer<EffectParamsGpu>   p_effects      read
//
// # Push constants (8 B)
//
//   [0,4)  uint  steps    -- the host-clamped substep count (plan M3); ONE number, two consumers
//   [4,8)  float timestep -- `ParticleClock`'s CONSTANT dt (plan D6)

struct SimPush {
    uint  steps;
    float timestep;
};
[[vk::push_constant]] SimPush pc;

// The per-effect row (plan D2, 128 B). `damping` and the rotation multiplier are
// HOST-PRECOMPUTED against the CONSTANT `ParticleClock` timestep (plan D6), which is what
// deletes `exp2` and all trig from the device. `rot_mul_cos`/`rot_mul_sin` are an f32 PAIR,
// not snorm16 (plan K1: a quantized multiplier's magnitude error is a per-effect CONSTANT
// that compounds as (1+d)^n to ~1% over 640 steps; at f32 it is <= 1 ULP).
struct EffectParamsGpu {
    float3 gravity;      float damping;
    float  rot_mul_cos;  float rot_mul_sin;
    uint2  _r0;
    uint4  color_keys;
    uint2  color_times;  uint2 size_keys;
    float  lifetime_min; float lifetime_max; float speed_min; float speed_max;
    float  size_base;    float cone_cos;     float _r1;       float _r2;
    uint   tex_index;    uint  blend_class;  uint  flags;     float collision_radius;
    float  restitution;  float friction;     uint  emitter_shape; uint _r3;
};

// The sim's working set (plan D2, 48 B, AoS). `size0_invlife` packs the spawn size and the
// RECIPROCAL total lifetime as two binary16 halves -- emit pays the one divide, once per
// particle, so the per-frame sim is divide-free. `effect_flags` packs `u16 effect_index |
// u16 flags`. `cached_field_d` is the P1 Lipschitz cache, written 0 at P0.
struct ParticleSim {
    float3 position; float life_remaining;
    float3 velocity; float cached_field_d;
    uint   color_rgba8;
    uint   size0_invlife;
    uint   effect_flags;
    uint   rot_cs;
};

// The draw's working set (plan D2, 32 B, AoS). Written by the sim at the CLASS-DENSE render
// index; read by the VS at `pc.index_base + pc.index_step * SV_InstanceID`. Ramp resolution
// happens ONCE per particle in the sim rather than 4x per particle in the VS.
struct ParticleRender {
    float3 position; float size;
    uint   color_rgba8;
    uint   rot_cs;
    uint   tex_index;
    uint   flags;
};

[[vk::binding(0, 0)]] RWStructuredBuffer<uint>              p_counters    : register(u0);
[[vk::binding(2, 0)]] RWStructuredBuffer<uint>              p_draw_args   : register(u2);
[[vk::binding(3, 0)]] RWStructuredBuffer<uint>              p_dead        : register(u3);
[[vk::binding(4, 0)]] RWStructuredBuffer<uint>              p_alive_read  : register(u4);
[[vk::binding(5, 0)]] RWStructuredBuffer<uint>              p_alive_write : register(u5);
[[vk::binding(6, 0)]] RWStructuredBuffer<ParticleSim>       p_particle    : register(u6);
[[vk::binding(7, 0)]] RWStructuredBuffer<ParticleRender>    p_render      : register(u7);
[[vk::binding(9, 0)]] StructuredBuffer<EffectParamsGpu>     p_effects     : register(t9);

// `ParticleCounters` (plan D2) is one 64-byte line addressed as `uint` WORDS -- a typed
// record cannot be the destination of `InterlockedAdd`. Every index below is a GENERATOR
// INPUT (`emit_particles.rs`), never typed here, so it cannot drift from the host struct.
static const uint CTR_ALIVE_CUR  = 0u;
static const uint CTR_ALIVE_NEXT = 1u;
static const uint CTR_DEAD_COUNT = 2u;
static const uint CTR_DEAD_BASE  = 3u;
static const uint CTR_EMIT_BASE  = 4u;
static const uint CTR_REAL_EMIT  = 5u;
static const uint CTR_CLAMPED    = 6u;

// The additive class's RENDER counter, at the word the generator derived from
// `PARTICLE_ADDITIVE_INSTANCE_COUNT_OFFSET` (4 bytes) -- plan gate #8. The `InterlockedAdd` on it
// yields BOTH this lane's render position and, at retirement, the class's final instance count.
static const uint DRAW_ADDITIVE_INSTANCE_WORD = 1u;

// `PARTICLE_SUBSTEP_CEILING` (plan M3). The HOST already clamped; this is the F25 hang guard.
static const uint SUBSTEP_CEILING = 64u;

// === GENERATED particle_integrate BEGIN ===
// One explicit-Euler substep (`boyko_shaderdsl::particle::particle_integrate_body`). `damping` is
// host-precomputed against the constant timestep (plan D6), which is what deletes `exp2` here.
void particle_integrate(inout float3 pos, inout float3 vel, inout float life,
                        float3 gravity, float damping, float dt) {
    vel = (vel + gravity * dt) * damping;
    pos = pos + vel * dt;
    life = life - dt;
}
// === GENERATED particle_integrate END ===

// === GENERATED particle_rot_advance BEGIN ===
// The rotation advance (`boyko_shaderdsl::particle::particle_rot_advance_body`): a complex
// multiply against the host-precomputed `(cos w*dt, sin w*dt)` f32 pair, re-quantized to snorm16
// with NO renormalization and NO divide (plan M7/K1).
uint particle_rot_advance(uint rot_cs, float mul_cos, float mul_sin) {
    uint cb = rot_cs + 32768u;
    float rc = ((float)(cb & 65535u) - 32768.0) * 3.051851e-5;
    uint sb = (rot_cs >> 16u) + 32768u;
    float rs = ((float)(sb & 65535u) - 32768.0) * 3.051851e-5;
    float nc = rc * mul_cos - rs * mul_sin;
    float ns = rc * mul_sin + rs * mul_cos;
    float qc = min(max(nc, -1.0), 1.0) * 32767.0 + 65536.5;
    float qs = min(max(ns, -1.0), 1.0) * 32767.0 + 65536.5;
    return ((uint)qc & 65535u) | (((uint)qs & 65535u) << 16u);
}
// === GENERATED particle_rot_advance END ===

// === GENERATED particle_curve_eval BEGIN ===
// The branch-free 4-key ramp over two packed binary16 pairs
// (`boyko_shaderdsl::particle::particle_curve_eval_body`). Evaluated ONCE per particle here
// rather than 4x per particle in the VS -- the larger half of D2's two-record win.
float particle_curve_eval(uint keys_lo, uint keys_hi, float t) {
    float k0 = f16tof32(keys_lo & 65535u);
    float k1 = f16tof32(keys_lo >> 16u);
    float k2 = f16tof32(keys_hi & 65535u);
    float k3 = f16tof32(keys_hi >> 16u);
    float u = clamp(t, 0.0, 1.0) * 3.0;
    float w0 = clamp(u, 0.0, 1.0);
    float w1 = clamp(u - 1.0, 0.0, 1.0);
    float w2 = clamp(u - 2.0, 0.0, 1.0);
    float v0 = lerp(k0, k1, w0);
    float v1 = lerp(v0, k2, w1);
    return lerp(v1, k3, w2);
}
// === GENERATED particle_curve_eval END ===

[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {
    uint i = tid.x;
    // The SAME field kickoff sized this dispatch from -- one value read twice, never two
    // derivations that have to be kept in agreement. Lanes past it retire BEFORE any wave
    // intrinsic, so they contribute to no ballot.
    if (i >= p_counters[CTR_ALIVE_CUR]) { return; }

    uint slot = p_alive_read[i];
    ParticleSim p = p_particle[slot];
    EffectParamsGpu e = p_effects[p.effect_flags & 65535u];

    float3 pos  = p.position;
    float3 vel  = p.velocity;
    float  life = p.life_remaining;
    uint   rot  = p.rot_cs;

    uint steps = min(pc.steps, SUBSTEP_CEILING);
    [loop]
    for (uint s = 0u; s < steps; ++s) {
        particle_integrate(pos, vel, life, e.gravity, e.damping, pc.timestep);
        rot = particle_rot_advance(rot, e.rot_mul_cos, e.rot_mul_sin);
    }

    bool survives = (life > 0.0);

    // Every wave quantity is computed BEFORE either branch, so the ballots see the full set of
    // in-range lanes exactly as the plan's NORMATIVE block describes them.
    uint w_count = WaveActiveCountBits(survives);
    uint w_lane  = WavePrefixCountBits(survives);
    uint d_count = WaveActiveCountBits(!survives);
    uint d_lane  = WavePrefixCountBits(!survives);
    // P0 is additive-only: the class predicate is the compile-time `true`, so the RENDER
    // reservation is the LIST reservation's twin. P2 gives them different predicates.
    uint r_count = w_count;
    uint r_lane  = w_lane;

    uint w_base_raw = 0u;
    uint r_base_raw = 0u;
    uint d_base_raw = 0u;
    if (WaveIsFirstLane()) {
        // The `> 0u` guards are what keep an all-surviving wave at TWO atomics and an all-dying
        // wave at ONE (plan D5's budget), rather than three unconditional ones.
        if (w_count > 0u) {
            InterlockedAdd(p_counters[CTR_ALIVE_NEXT], w_count, w_base_raw);
            InterlockedAdd(p_draw_args[DRAW_ADDITIVE_INSTANCE_WORD], r_count, r_base_raw);
        }
        if (d_count > 0u) {
            InterlockedAdd(p_counters[CTR_DEAD_COUNT], d_count, d_base_raw);
        }
    }
    // Broadcast OUTSIDE the leader branch -- every lane needs the reservation base.
    uint w_base = WaveReadLaneFirst(w_base_raw);
    uint r_base = WaveReadLaneFirst(r_base_raw);
    uint d_base = WaveReadLaneFirst(d_base_raw);

    if (!survives) {
        // The dying path returns the slot to the free list at its wave-aggregated position.
        p_dead[d_base + d_lane] = slot;
        return;
    }

    p.position       = pos;
    p.velocity       = vel;
    p.life_remaining = life;
    p.rot_cs         = rot;
    p_particle[slot] = p;

    float size0    = f16tof32(p.size0_invlife & 65535u);
    float inv_life = f16tof32(p.size0_invlife >> 16u);
    // Normalized age in [0,1]. `inv_life` is the RECIPROCAL emit stored at spawn, so this is a
    // multiply and this module stays free of `OpFDiv` (see the header).
    float age  = 1.0 - life * inv_life;
    float size = size0 * particle_curve_eval(e.size_keys.x, e.size_keys.y, age);

    // The LIST position (shared by both blend classes -- this is what makes an alpha leak
    // structurally impossible, plan M2) and the class-dense RENDER position.
    uint idx   = w_base + w_lane;
    uint r_pos = r_base + r_lane;

    p_alive_write[idx] = slot;

    ParticleRender r;
    r.position    = pos;
    r.size        = size;
    r.color_rgba8 = p.color_rgba8;
    r.rot_cs      = rot;
    r.tex_index   = e.tex_index;
    r.flags       = p.effect_flags >> 16u;
    p_render[r_pos] = r;
}
