// particle_kickoff.comp -- the GPU particle system's ONE-THREAD bookkeeping pass
// (`docs/PARTICLES-PLAN.md` Rev 4, algorithm A2 / decision D3).
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_particles`. Hand-edits
// fail `boyko_rhi_vulkan/tests/particle_edsl_sync.rs`.
//
// # What it does, in one thread
//
// Swaps the alive roles' COUNTS, clamps the requested spawn against the free list, publishes the
// two bases emit reads, and writes both indirect argument blocks. It is O(1) over three cache
// lines and entirely branchless.
//
// The reason it is ONE thread is the reason `particle_emit` needs ZERO atomics: because a single
// lane owns `dead_count` and `alive_count_cur` here, it can pre-DECREMENT one and pre-INCREMENT
// the other in the same pass, publishing `dead_base` and `emit_append_base` as plain values.
// Every emit lane then computes both of its indices arithmetically from `gid`.
//
// # The partition this pass maintains (plan, "The partition at each boundary")
//
// Let A = alive_count_cur, D = dead_count, E = real_emit_count, N = alive_count_next. `A + D ==
// CAP` holds ACROSS this pass because the reservation is accounted on BOTH sides simultaneously:
// `dead_count` drops by E in the same lane that raises `alive_count_cur` by E.
//
// # Compile (offline + hermetic; committed `.spv` is byte-gated)
//
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 particle_kickoff.comp.hlsl -Fo particle_kickoff.comp.spv
//
// # Set / binding vocabulary -- MIRRORS the host `PARTICLE_LAYOUT_ENTRIES` table
//
//   (set, binding, kind)
//   (0, 0, STORAGE_BUFFER)  RWStructuredBuffer<uint>  p_counters       read+write
//   (0, 1, STORAGE_BUFFER)  RWStructuredBuffer<uint>  p_dispatch_args  write
//   (0, 2, STORAGE_BUFFER)  RWStructuredBuffer<uint>  p_draw_args      write
//
//   The three compute passes SHARE one Set-0 vocabulary (bindings 0..9); each declares only the
//   subset it uses, and DXC strips the rest. The host layout is the union.
//
// # Push constants (8 B, well under the shared COMPUTE range floor)
//
//   [0,4)  uint requested_spawn -- the host's already-clamped total across all emitters
//   [4,8)  uint capacity        -- CAP, the boot-frozen pool size (plan D14)

struct KickoffPush {
    uint requested_spawn;
    uint capacity;
};
[[vk::push_constant]] KickoffPush pc;

[[vk::binding(0, 0)]] RWStructuredBuffer<uint> p_counters      : register(u0);
[[vk::binding(1, 0)]] RWStructuredBuffer<uint> p_dispatch_args : register(u1);
[[vk::binding(2, 0)]] RWStructuredBuffer<uint> p_draw_args     : register(u2);

// `ParticleCounters` (plan D2) is one 64-byte line addressed as `uint` WORDS -- a typed
// record cannot be the destination of `InterlockedAdd`. Every index below is a GENERATOR
// INPUT (`emit_particles.rs`), never typed here, so it cannot drift from the host struct.
static const uint CTR_ALIVE_CUR  = 0u;
static const uint CTR_ALIVE_NEXT = 1u;
static const uint CTR_DEAD_COUNT = 2u;
static const uint CTR_DEAD_BASE  = 3u;
static const uint CTR_EMIT_BASE  = 4u;
static const uint CTR_REAL_EMIT  = 5u;
static const uint CTR_CLAMPED    = 6u;

// The two `VkDispatchIndirectCommand` blocks inside `p_dispatch_args` (plan D4: offsets 0 and 16).
static const uint DISPATCH_EMIT_WORD = 0u;
static const uint DISPATCH_SIM_WORD  = 4u;

// The two `VkDrawIndexedIndirectCommand` slots inside `p_draw_args`. The `instanceCount` word
// indices are DERIVED by the generator from `PARTICLE_{ADDITIVE,ALPHA}_INSTANCE_COUNT_OFFSET`
// (4 and 28 bytes, both 4-aligned), which are the SAME `offset_of!` chains the host
// pins -- plan gate #8.
static const uint DRAW_ADDITIVE_BASE_WORD     = 0u;
static const uint DRAW_ADDITIVE_INSTANCE_WORD = 1u;
static const uint DRAW_ALPHA_BASE_WORD        = 6u;
static const uint DRAW_ALPHA_INSTANCE_WORD    = 7u;

// The workgroup widths this pass sizes the two indirect dispatches for. `>> LOG2` rather than
// `/ LOCAL_SIZE`: the width is a power of two, so the round-up is a shift and this module carries
// no integer divide.
static const uint LOCAL_SIZE      = 256u;
static const uint LOCAL_SIZE_LOG2 = 8u;

// The 6-index quad every particle instance draws (plan D4).
static const uint QUAD_INDEX_COUNT = 6u;

[numthreads(1, 1, 1)]
void main() {
    // The ROLE SWAP. `alive_count_next` was written by the PREVIOUS frame's sim; the seed on
    // `p_counters` is what carries its availability across the frame edge (plan seed-table row 6).
    uint a = p_counters[CTR_ALIVE_NEXT];
    p_counters[CTR_ALIVE_NEXT] = 0u;

    // D3's release-present clamp on the free list (plan D15/R8, and F25 -- `robustBufferAccess`
    // is OFF, so `dead_base + gid` addressing `p_dead` out of range is UB, not a clamp).
    //
    // D3 writes this clamp `max(0, dead_count)`. Over a `uint` that half is VACUOUS -- DXC folds
    // it and no instruction survives -- so the operative half, and the only one that can bind, is
    // the upper cap at CAP. Both directions of "clamp into the legal range" are therefore carried
    // by the `min` alone.
    uint d = min(p_counters[CTR_DEAD_COUNT], pc.capacity);

    // The spawn request, clamped against what the free list can actually serve. The shortfall
    // ACCUMULATES in a cold diagnostic word the host reads out of band.
    uint e = min(pc.requested_spawn, d);
    p_counters[CTR_CLAMPED] = p_counters[CTR_CLAMPED] + (pc.requested_spawn - e);

    uint dead_base = d - e;      // the PRE-DECREMENT: the E reserved slots sit at [dead_base, d)
    uint alive_cur = a + e;      // the PRE-INCREMENT: the E fresh list slots sit at [a, alive_cur)

    p_counters[CTR_DEAD_COUNT] = dead_base;
    p_counters[CTR_DEAD_BASE]  = dead_base;
    p_counters[CTR_EMIT_BASE]  = a;
    p_counters[CTR_REAL_EMIT]  = e;
    p_counters[CTR_ALIVE_CUR]  = alive_cur;

    // The two indirect DISPATCH blocks. The sim is sized from `alive_count_cur` -- the SAME field
    // its own range guard reads, not a second derivation that has to be kept in agreement.
    p_dispatch_args[DISPATCH_EMIT_WORD + 0u] = (e + (LOCAL_SIZE - 1u)) >> LOCAL_SIZE_LOG2;
    p_dispatch_args[DISPATCH_EMIT_WORD + 1u] = 1u;
    p_dispatch_args[DISPATCH_EMIT_WORD + 2u] = 1u;
    p_dispatch_args[DISPATCH_EMIT_WORD + 3u] = 0u;
    p_dispatch_args[DISPATCH_SIM_WORD  + 0u] = (alive_cur + (LOCAL_SIZE - 1u)) >> LOCAL_SIZE_LOG2;
    p_dispatch_args[DISPATCH_SIM_WORD  + 1u] = 1u;
    p_dispatch_args[DISPATCH_SIM_WORD  + 2u] = 1u;
    p_dispatch_args[DISPATCH_SIM_WORD  + 3u] = 0u;

    // Both indirect DRAW slots, reset for this frame. `indexCount` is written FIRST and
    // `instanceCount` is zeroed here because it is ALSO the sim's per-class render counter (plan
    // M1/M2): the `InterlockedAdd` that yields a lane's render position leaves the class's final
    // count behind, so the command processor reads a live count with no finish pass (closing R9).
    //
    // `firstInstance` is 0 in BOTH slots and must stay so -- F5b: `drawIndirectFirstInstance` is
    // not enabled on this device and a nonzero value there is a silent corruption class.
    p_draw_args[DRAW_ADDITIVE_BASE_WORD + 0u] = QUAD_INDEX_COUNT;  // indexCount
    p_draw_args[DRAW_ADDITIVE_INSTANCE_WORD]  = 0u;                // instanceCount
    p_draw_args[DRAW_ADDITIVE_BASE_WORD + 2u] = 0u;                // firstIndex
    p_draw_args[DRAW_ADDITIVE_BASE_WORD + 3u] = 0u;                // vertexOffset
    p_draw_args[DRAW_ADDITIVE_BASE_WORD + 4u] = 0u;                // firstInstance (F5b)
    p_draw_args[DRAW_ADDITIVE_BASE_WORD + 5u] = 0u;                // inter-command pad

    // The alpha slot is P2's. It is zeroed every frame at P0 -- an undeclared pass writes no
    // instances, so its `instanceCount` stays 0 and the command processor draws nothing from it.
    p_draw_args[DRAW_ALPHA_BASE_WORD + 0u] = QUAD_INDEX_COUNT;
    p_draw_args[DRAW_ALPHA_INSTANCE_WORD]  = 0u;
    p_draw_args[DRAW_ALPHA_BASE_WORD + 2u] = 0u;
    p_draw_args[DRAW_ALPHA_BASE_WORD + 3u] = 0u;
    p_draw_args[DRAW_ALPHA_BASE_WORD + 4u] = 0u;                   // firstInstance (F5b)
    p_draw_args[DRAW_ALPHA_BASE_WORD + 5u] = 0u;
}
