// Render P7 GROUP A — screen-space AO (HBAO-lite, no-trig) compute shader.
//
// A full-resolution, deterministic, no-blur horizon-based AO pass that gathers an
// occlusion factor from the FROZEN G-buffer and writes it to an R8_UNORM `ssao` lane the
// deferred resolve combines (`min(class_ao, ssao)`). It is admitted as a SECOND AO
// strategy (Principle 9) for the two structural capability wins the analytic A2 SDF march
// cannot reach: (1) mesh pixels have no field, so SSAO is the ONLY AO there; (2)
// cross-representation occlusion (a mesh occluding an SDF pixel, or disjoint SDF edits
// beyond the local march reach). The default is OFF (the resolve `ssao_mode` header word
// gates the combine; this pass is recorded only when `scene.ssao.is_some()`), so the exact
// A2 path is byte-identically preserved when SSAO is not admitted.
//
// # The horizon reducer (HBAO-lite, no trig)
//
// For each of `SSAO_SLICES` rotated screen-space slices, march `SSAO_STEPS` forward-
// projected neighbour taps in each of the two half-slices, tracking the maximum neighbour
// ELEVATION ABOVE THE SURFACE TANGENT PLANE `hc` (the sine of the elevation against the
// center surface normal N, clamped non-negative); fold the two half-slice maxes into a
// per-slice occlusion, sum over slices, and complement: `ao = clamp01(1 - SSAO_STRENGTH *
// occ / SSAO_SLICES)` then `ao = ao*ao`. The horizon step needs only `dot`/`max`/`sqrt`/
// `div` — NO `sin`/`cos`/`acos` (GTAO's arc integral, which has an irreducible GPU↔CPU
// transcendental ULP gap) and NO `fract` rotation (an integer-boundary discontinuity under
// FMA). A flat lit surface (delta perpendicular to N) raises NO horizon (AO = 1.0); a
// crevice (neighbours rising above the tangent) does. The horizon-step MATH is the
// eDSL-GENERATED span (see the sentinels below).
//
// # The eDSL-generated span (single-source — `boyko_shaderdsl::ssao`)
//
// The `// === GENERATED ssao_horizon_step BEGIN/END ===` span is MACHINE-GENERATED by
// `boyko_shaderdsl::emit::emit_hlsl_ssao()` (tracing `ssao::ssao_horizon_step_body` over
// the Emit backend) — ONE forward horizon tap's math. The `ssao_edsl_sync` test pins the
// committed span to the generator (`.contains` drift gate) AND re-DXCs this whole file to
// assert it is byte-identical to the committed `sdf_ssao.comp.spv`. A hand-edit of the span
// fails CI. ZERO new eDSL leaves: `dot` is inline component-reads + mul/add, `length =
// sqrt(dot(d,d))`, the elevation clamp the existing `max`, the `ao*ao` power an integer
// self-mul — so the frozen marcher/field/shadow/brick/resolve `.spv` physically cannot fork.
// The forward neighbour reconstruct, the `[unroll]` slice/step loops, the rotation-table tap
// offset, the center-normal decode, and the `occ → ao` fold are HAND-WRITTEN glue (framing b)
// — the host oracle is the full `ssao_estimate_body`.
//
// # The PCG-hash dither (bit-exact GPU↔host) — rotation + radial step-phase
//
// Two INTEGER hashes (no float `fract`/`floor`, no trig) decorrelate the discrete-step
// pattern into high-frequency noise the depth-aware resolve blur removes. Both go through the
// NON-LINEAR `ssao_pcg`/`ssao_hash2` avalanche: a LINEAR `px*A + py*B` hash has DIAGONAL
// iso-lines (collinear pixels hash to the SAME slot/phase), so its dither was itself diagonally
// COHERENT and the blur left faint diagonal STRIPES — PCG mixing scatters them away:
//   (1) the per-pixel slice ROTATION — `slot = ssao_hash2(px, py) & 15u` into a 16-entry
//       pre-baked `(cos, sin)` table (16 evenly-spaced angles break the angular banding);
//   (2) the per-pixel radial STEP-PHASE — the SAME hash seeded distinctly
//       (`hr = ssao_hash2(px ^ 0x68bc21ebu, py ^ 0x02e5be93u); radial_phase =
//       ((hr & 255u)+1)/256.0` in [1/256, 1.0]) added to the step index so EVERY pixel marches
//       a different set of step radii (the concentric-ring fix), decorrelated from the rotation.
//       Both are integer-indexed / exact-divide, so the GPU and the host oracle pick the SAME
//       dither bit-exactly.
//
// # The forward neighbour reconstruct (no proj-matrix inverse)
//
// Each tap offsets in SCREEN PIXELS (`px' = round(px + dir.x*step*pix_radius)`), bounds-
// clamps, and reconstructs the neighbour world position FORWARD via `generate_ray(px',py')
// * gViewT'` (the SAME shared ray-gen `ray_gen.hlsli` the marcher/resolve use). NO world→
// pixel inverse (the un-mirrorable step). A tap that falls out of bounds or onto a non-lit
// pixel (`mask != 1 || view_t >= 1e30`) reconstructs `Pp = P` so its falloff contributes
// nothing (the eDSL span carries no per-tap branch).
//
// # Resources (dedicated 5-binding SSAO bind-group — the base, non-`VB_THIN` build)
//
//   binding 0 : RWTexture2D<float4> (STORAGE, rgba8) — gNormal   (READ; oct + material id)
//   binding 1 : RWTexture2D<float4> (STORAGE, rgba8) — gMaterial (READ; .b = mask)
//   binding 2 : RWTexture2D<float>  (STORAGE, r32f)  — gViewT    (READ; surface ray param t)
//   binding 3 : RWTexture2D<float>  (STORAGE, r8)    — ssao      (WRITE; the AO factor)
//   binding 4 : cbuffer Camera (UNIFORM)             — the 80-byte extent/camera block
// `gAlbedo` is NOT bound. `[[vk::image_format]]` pins each storage image's OpTypeImage
// (shaderStorageImageWriteWithoutFormat is OFF).
//
// # VB_THIN variant (`-D VB_THIN=1` — R9-VB-SPLIT-PLAN.md §5, the SSAO-gather half of the
// VisibilityBuffer geo/shade split, R9b)
//
// The VB split (`vb_geo`/`vb_shade_split`) has NO material G-buffer (the no-matcache rule):
// there is no `gMaterial` image to read `.b` from for the background/mask test, and the
// normal source is `vb_geo`'s thin aux image (`gThinNormal`, oct-encoded in RG, roughness in
// BA — UNREAD here) instead of the fat `gNormal`. Under this define:
//   - `gMaterial` is DROPPED ENTIRELY — not declared, no binding reserved for it (a hole in
//     this shader's own declarations, unlike the `sdf_forward_march.comp.hlsl` HAS_MESH
//     precedent of reserving an unread slot in a SHARED layout — VB_THIN gets its OWN dense
//     layout, so there is no shared layout to keep a slot alive in).
//   - `gNormal` is REPLACED by `gThinNormal` at the SAME slot (binding 0), decoded with the
//     SAME `oct_decode` (RG-only; the BA roughness lane is not read by this pass).
//   - The mask test becomes `view_t < SSAO_VIEWT_BG` alone, read off the already-bound
//     `gViewT` (the `vb_viewt`/marcher background sentinel — mirrors
//     `viewt_from_depth_rz.comp.hlsl`'s `VIEWT_BG` convention): a background pixel takes the
//     SAME neutral path the base's `mask != 1` arm takes (a tap reconstructs `Pp = P`; a
//     non-lit CENTER writes the SAME neutral `1.0` the base writes).
//   - With the material image gone, the remaining 3 images + Camera RENUMBER into a DENSE
//     4-binding table — a DIFFERENT bind-group layout host-side (`vb_ssao_layout`), not a
//     hole in the base's 5-binding one:
//       binding 0 : RWTexture2D<float4> (STORAGE, rgba8) — gThinNormal (READ; oct RG, roughness BA unread)
//       binding 1 : RWTexture2D<float>  (STORAGE, r32f)  — gViewT      (READ; surface ray param t)
//       binding 2 : RWTexture2D<float>  (STORAGE, r8)    — ssao        (WRITE; the AO factor)
//       binding 3 : cbuffer Camera (UNIFORM)              — the SAME 80-byte extent/camera block
//   - The march/dither/slice math, the tuning header, and the eDSL-GENERATED
//     `ssao_horizon_step` span are BYTE-IDENTICAL text either way — the span (and its
//     surrounding hand-written glue) reads only function-local names (`Pp`, `P`, `n`, `hc`),
//     never a binding, so the renumbering never touches it.
//
// Compiled offline (hermetic — no SDK at `cargo build` time) with:
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main \
//       -fspv-target-env=vulkan1.3 sdf_ssao.comp.hlsl -Fo sdf_ssao.comp.spv
// The `ssao_edsl_sync` re-DXC byte-identity test pins the committed .spv to this recipe.
//
// VB_THIN is compiled per quality preset, from the SAME per-preset `.hlsl` the base variant
// derivation emits (`sdf_ssao_<quality>.comp.hlsl`, `boyko_shaderdsl::ssao::variant_hlsl`),
// re-DXC'd with the ADDITIONAL `-D VB_THIN=1`:
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main -D VB_THIN=1 \
//       -fspv-target-env=vulkan1.3 sdf_ssao_low.comp.hlsl -Fo sdf_ssao_vb_low.comp.spv
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main -D VB_THIN=1 \
//       -fspv-target-env=vulkan1.3 sdf_ssao_medium.comp.hlsl -Fo sdf_ssao_vb_medium.comp.spv
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T cs_6_0 -E main -D VB_THIN=1 \
//       -fspv-target-env=vulkan1.3 sdf_ssao_high.comp.hlsl -Fo sdf_ssao_vb_high.comp.spv
// The `ssao_edsl_sync` re-DXC byte-identity loop is extended to these 3 blobs.

// bindings 0..2 (base) / 0..1 (VB_THIN): the aux/G-buffer lanes READ by the gather (the
// vb_geo/marcher store views). VB_THIN drops `gMaterial` and renumbers into the dense
// 4-binding table — see the VB_THIN header doc above.
#if VB_THIN
[[vk::image_format("rgba8")]] RWTexture2D<float4> gThinNormal : register(u0);
[[vk::image_format("r32f")]]  RWTexture2D<float>  gViewT      : register(u1);
// binding 2: the SSAO output lane (R8_UNORM STORAGE in GENERAL its whole life).
[[vk::image_format("r8")]]    RWTexture2D<float>  ssao        : register(u2);
#else
[[vk::image_format("rgba8")]] RWTexture2D<float4> gNormal   : register(u0);
[[vk::image_format("rgba8")]] RWTexture2D<float4> gMaterial : register(u1);
[[vk::image_format("r32f")]]  RWTexture2D<float>  gViewT    : register(u2);
// binding 3: the SSAO output lane (R8_UNORM STORAGE in GENERAL its whole life).
[[vk::image_format("r8")]]    RWTexture2D<float>  ssao      : register(u3);
#endif

// binding 4 (base) / binding 3 (VB_THIN, the dense renumbered table): the camera/extent
// UNIFORM block — byte-identical field layout to the marcher's `Camera` (and the host
// `CompositePushConstants`). The 80-byte head is all this pass needs (no M4 clip-map tail):
// the extent (1:1 the marched pixels) + the per-pixel view direction (the shared ray-gen).
// Offsets pinned host-side by the existing COMPOSITE_PC_* const-asserts.
#if VB_THIN
cbuffer Camera : register(b3) {
    uint   count;        // total pixel count = img_w * img_h
    uint   img_w_raw;    // runtime extent width  (0 => IMG_W_DEFAULT)
    uint   img_h_raw;    // runtime extent height (0 => IMG_H_DEFAULT)
    uint   camera_mode;  // RAYGEN_CAM_ORTHO | RAYGEN_CAM_PERSPECTIVE
    float4 cam_eye;      // xyz = eye world pos          (PERSPECTIVE)
    float4 cam_forward;  // xyz = forward basis, w = tan(fovY/2) (PERSPECTIVE)
    float4 cam_right;    // xyz = right basis,  w = aspect (W/H)  (PERSPECTIVE)
    float4 cam_up;       // xyz = up basis                (PERSPECTIVE)
};
#else
cbuffer Camera : register(b4) {
    uint   count;        // total pixel count = img_w * img_h
    uint   img_w_raw;    // runtime extent width  (0 => IMG_W_DEFAULT)
    uint   img_h_raw;    // runtime extent height (0 => IMG_H_DEFAULT)
    uint   camera_mode;  // RAYGEN_CAM_ORTHO | RAYGEN_CAM_PERSPECTIVE
    float4 cam_eye;      // xyz = eye world pos          (PERSPECTIVE)
    float4 cam_forward;  // xyz = forward basis, w = tan(fovY/2) (PERSPECTIVE)
    float4 cam_right;    // xyz = right basis,  w = aspect (W/H)  (PERSPECTIVE)
    float4 cam_up;       // xyz = up basis                (PERSPECTIVE)
};
#endif

// Shared camera ray-generation (the SAME header the marcher + resolve include — ONE
// ray-gen, no drift). Takes the camera fields as plain parameters (binding-agnostic).
#include "ray_gen.hlsli"

// The legacy 64x64 fixture extent when the UBO extent is zero (mirrors the marcher/resolve).
static const uint IMG_W_DEFAULT = 64u;
static const uint IMG_H_DEFAULT = 64u;
uint img_w() { return (img_w_raw != 0u) ? img_w_raw : IMG_W_DEFAULT; }
uint img_h() { return (img_h_raw != 0u) ? img_h_raw : IMG_H_DEFAULT; }

// --- SSAO tuning (mirror boyko_shaderdsl::ssao; the eDSL span spells these SYMBOLICALLY) ---
static const float SSAO_RADIUS   = 0.5;     // world-space sampling radius
static const uint  SSAO_SLICES   = 2u;      // rotated screen-space slices
static const float SSAO_SLICES_F = 2.0;     // the slice count as a float (the `occ / N` divisor)
static const uint  SSAO_STEPS    = 4u;      // forward steps per half-slice
static const float SSAO_STRENGTH = 2.5;     // occlusion strength multiplier
static const float SSAO_EPS      = 1.0e-4;  // length(delta) divide-by-zero guard

// The mesh/SDF G-buffer sentinel (mirror the marcher's gViewT `1.0e30` background sentinel).
static const float SSAO_VIEWT_BG = 1.0e30;
// The screen-pixel radius clamp (perspective): keep taps from collapsing to one texel or
// blowing past a sane neighbourhood. `RAYGEN_HALF_EXTENT` (ortho half-extent) lives in
// `ray_gen.hlsli`; the ortho pix_radius divides the radius by it.
static const float SSAO_RADIUS_PIX_MIN = 2.0;
static const float SSAO_RADIUS_PIX_MAX = 24.0;

// --- The evenly-spaced rotation/base-axis table (bit-exact GPU↔host) ------------------------
// A pre-baked `(cos, sin)` table for SSAO_ROT_N evenly-spaced angles over [0, pi): angle k =
// k*(pi/64) for k = 0..63 (a 2.8125° step). It serves BOTH (1) the per-slice BASE axes since
// Change A (`SSAO_ROT[sl * SSAO_BASE_STRIDE]` — slice s at s*(pi/N); the strided entries are
// bit-identical to the retired 16-entry table's) and (2) the per-pixel DITHER rotation slot
// (see the pick site in `main`). Widened 16 -> 64: on an even-slice axis set the effective
// dither classes = `SSAO_ROT_N / SSAO_SLICES`, and 16 entries left only 2 classes at 8 slices
// — spatially-coherent streaks. The host mirror bakes the IDENTICAL `f32`-rounded values
// (byte-value-identical literals).
static const uint SSAO_ROT_N = 64u;
static const float2 SSAO_ROT[64] = {
    float2(  1.00000000,  0.00000000 ),  //   0.00 deg
    float2(  0.99879545,  0.04906768 ),  //   2.81 deg
    float2(  0.99518472,  0.09801714 ),  //   5.62 deg
    float2(  0.98917651,  0.14673047 ),  //   8.44 deg
    float2(  0.98078525,  0.19509032 ),  //  11.25 deg
    float2(  0.97003126,  0.24298018 ),  //  14.06 deg
    float2(  0.95694035,  0.29028466 ),  //  16.88 deg
    float2(  0.94154406,  0.33688986 ),  //  19.69 deg
    float2(  0.92387950,  0.38268343 ),  //  22.50 deg
    float2(  0.90398932,  0.42755508 ),  //  25.31 deg
    float2(  0.88192129,  0.47139674 ),  //  28.12 deg
    float2(  0.85772860,  0.51410276 ),  //  30.94 deg
    float2(  0.83146960,  0.55557024 ),  //  33.75 deg
    float2(  0.80320752,  0.59569931 ),  //  36.56 deg
    float2(  0.77301043,  0.63439327 ),  //  39.38 deg
    float2(  0.74095112,  0.67155898 ),  //  42.19 deg
    float2(  0.70710677,  0.70710677 ),  //  45.00 deg
    float2(  0.67155898,  0.74095112 ),  //  47.81 deg
    float2(  0.63439327,  0.77301043 ),  //  50.62 deg
    float2(  0.59569931,  0.80320752 ),  //  53.44 deg
    float2(  0.55557024,  0.83146960 ),  //  56.25 deg
    float2(  0.51410276,  0.85772860 ),  //  59.06 deg
    float2(  0.47139674,  0.88192129 ),  //  61.88 deg
    float2(  0.42755508,  0.90398932 ),  //  64.69 deg
    float2(  0.38268343,  0.92387950 ),  //  67.50 deg
    float2(  0.33688986,  0.94154406 ),  //  70.31 deg
    float2(  0.29028466,  0.95694035 ),  //  73.12 deg
    float2(  0.24298018,  0.97003126 ),  //  75.94 deg
    float2(  0.19509032,  0.98078525 ),  //  78.75 deg
    float2(  0.14673047,  0.98917651 ),  //  81.56 deg
    float2(  0.09801714,  0.99518472 ),  //  84.38 deg
    float2(  0.04906768,  0.99879545 ),  //  87.19 deg
    float2(  0.00000000,  1.00000000 ),  //  90.00 deg
    float2( -0.04906768,  0.99879545 ),  //  92.81 deg
    float2( -0.09801714,  0.99518472 ),  //  95.62 deg
    float2( -0.14673047,  0.98917651 ),  //  98.44 deg
    float2( -0.19509032,  0.98078525 ),  // 101.25 deg
    float2( -0.24298018,  0.97003126 ),  // 104.06 deg
    float2( -0.29028466,  0.95694035 ),  // 106.88 deg
    float2( -0.33688986,  0.94154406 ),  // 109.69 deg
    float2( -0.38268343,  0.92387950 ),  // 112.50 deg
    float2( -0.42755508,  0.90398932 ),  // 115.31 deg
    float2( -0.47139674,  0.88192129 ),  // 118.12 deg
    float2( -0.51410276,  0.85772860 ),  // 120.94 deg
    float2( -0.55557024,  0.83146960 ),  // 123.75 deg
    float2( -0.59569931,  0.80320752 ),  // 126.56 deg
    float2( -0.63439327,  0.77301043 ),  // 129.38 deg
    float2( -0.67155898,  0.74095112 ),  // 132.19 deg
    float2( -0.70710677,  0.70710677 ),  // 135.00 deg
    float2( -0.74095112,  0.67155898 ),  // 137.81 deg
    float2( -0.77301043,  0.63439327 ),  // 140.62 deg
    float2( -0.80320752,  0.59569931 ),  // 143.44 deg
    float2( -0.83146960,  0.55557024 ),  // 146.25 deg
    float2( -0.85772860,  0.51410276 ),  // 149.06 deg
    float2( -0.88192129,  0.47139674 ),  // 151.88 deg
    float2( -0.90398932,  0.42755508 ),  // 154.69 deg
    float2( -0.92387950,  0.38268343 ),  // 157.50 deg
    float2( -0.94154406,  0.33688986 ),  // 160.31 deg
    float2( -0.95694035,  0.29028466 ),  // 163.12 deg
    float2( -0.97003126,  0.24298018 ),  // 165.94 deg
    float2( -0.98078525,  0.19509032 ),  // 168.75 deg
    float2( -0.98917651,  0.14673047 ),  // 171.56 deg
    float2( -0.99518472,  0.09801714 ),  // 174.38 deg
    float2( -0.99879545,  0.04906768 ),  // 177.19 deg
};

// Even-slice base axis (Change A): slice `s` spans angle `s*(pi/SSAO_SLICES)` == `SSAO_ROT[s*STRIDE]`,
// reusing the SAME bit-exact 16-entry rotation table (host + shader share the identical literals)
// instead of a new per-N `(cos,sin)` table (no round-trip risk, no per-variant header). REQUIRES
// `SSAO_SLICES` to DIVIDE `SSAO_ROT_N` (2/4/8/16) for exact even spacing — the host oracle asserts
// this. `N=2` gives stride 8 -> `ROT[0]=(1,0)`, `ROT[8]=(0,1)`: byte-identical to the pre-A hardcoded
// `(sl==0)?(1,0):(0,1)` pair, so the Medium variant stays frozen (the no-op proof). A common-glue
// line (NOT in the swapped `SSAO_*` header block), so `variant_hlsl` carries it verbatim per variant.
static const uint SSAO_BASE_STRIDE = SSAO_ROT_N / SSAO_SLICES;

// --- Octahedral decode (BYTE-IDENTICAL to the resolve's `oct_decode` in deferred_pbr.hlsl;
// the inverse of the marcher's oct_encode). gNormal.rg carries the octahedral normal; the
// horizon step measures the neighbour's elevation above the tangent plane this normal defines.
float3 oct_decode(float2 e) {
    e = e * 2.0 - 1.0;                          // [0,1] -> [-1,1]
    float3 n = float3(e.x, e.y, 1.0 - abs(e.x) - abs(e.y));
    float t = saturate(-n.z);
    n.x += n.x >= 0.0 ? -t : t;
    n.y += n.y >= 0.0 ? -t : t;
    return normalize(n);
}

// --- Hilbert-curve + R2 low-discrepancy dither (BIT-IDENTICAL to host `ssao_hilbert`/`ssao_r2`
// in compute.rs). The prior per-pixel WHITE-NOISE hash put UNCORRELATED values on adjacent
// pixels; white noise has energy at ALL spatial frequencies, so the depth-aware blur (a low-pass)
// strips the highs but leaves low-frequency NOISY BLOBS — the "pixelated" look. The production fix
// (Intel XeGTAO's no-TAA noise basis, NVIDIA HBAO+) is a LOW-DISCREPANCY / blue-noise pattern whose
// energy is HIGH-frequency ONLY, which the SAME blur removes cleanly. We map (px,py) to a 64x64
// Hilbert-curve index (a locality-preserving 2D->1D order) and drive Martin Roberts' R2 quasi-random
// sequence from it (the XeGTAO recipe). Made BIT-EXACT GPU<->host via INTEGER fixed point:
// `r2 = (index * ALPHA_24) & 0xFFFFFF` is `frac(index * alpha)` in Q0.24, and a `uint` multiply
// wraps mod 2^32 IDENTICALLY on GPU and host (the low 24 bits are untouched by the wrap) — so there
// is NO `frac`/trig and the host oracle and GPU pick the SAME dither bit-for-bit.
static const uint SSAO_HILBERT_W = 64u;        // the Hilbert tile edge (XeGTAO uses level 6 = 64)
// R2 plastic-number reciprocals 1/phi, 1/phi^2 (phi = 1.32471795724474602596...) in Q0.24 fixed
// point: round(0.75487766624669276 * 2^24), round(0.56984029099805327 * 2^24).
static const uint SSAO_R2_ALPHA1 = 12664746u;
static const uint SSAO_R2_ALPHA2 = 9560334u;
// The locality-preserving 2D->1D Hilbert index over an n x n tile (n a power of two). Pure integer
// bit-twiddling (the canonical `xy2d`) -> bit-exact GPU<->host.
uint ssao_hilbert(uint n, uint x, uint y) {
    uint d = 0u;
    for (uint s = n / 2u; s > 0u; s /= 2u) {
        uint rx = ((x & s) > 0u) ? 1u : 0u;
        uint ry = ((y & s) > 0u) ? 1u : 0u;
        d += s * s * ((3u * rx) ^ ry);
        if (ry == 0u) {
            if (rx == 1u) { x = n - 1u - x; y = n - 1u - y; }
            uint t = x; x = y; y = t;
        }
    }
    return d;
}
// The R2 fractional part in Q0.24 fixed point (the dither value), bit-exact via `uint` wrap.
uint ssao_r2(uint index, uint alpha) { return (index * alpha) & 0xFFFFFFu; }

[numthreads(64, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {
    uint idx = tid.x;
    if (idx >= count) {
        return;
    }

    uint w = img_w();
    uint h = img_h();
    uint px = idx % w;
    uint py = idx / w;
    int2 coord = int2((int)px, (int)py);

    // Read the center pixel's class. `view_t` is the surface ray param (a `1.0e30` sentinel
    // on a non-lit / mesh / background pixel). VB_THIN has no material G-buffer, so `view_t`
    // alone is the mask; the base build additionally gates on `gMaterial.b` (a binary flag —
    // an R8 round-trip maps 1.0 -> ~255/255, so test > 0.5).
#if VB_THIN
    float center_view_t = gViewT.Load(coord);
    bool center_lit = (center_view_t < SSAO_VIEWT_BG);
#else
    float center_mask = gMaterial.Load(coord).b;
    float center_view_t = gViewT.Load(coord);
    bool center_lit = (center_mask > 0.5) && (center_view_t < SSAO_VIEWT_BG);
#endif

    // Default AO = 1.0 (no occlusion). A non-lit pixel (background) carries no surface, so
    // it gets the neutral factor and the resolve's `min(class_ao, ssao)` leaves it unchanged.
    float ao_out = 1.0;
    if (center_lit) {
        // Reconstruct the center world position P = ro + rd * view_t via the shared ray-gen.
        float3 ro;
        float3 rd;
        generate_ray(px, py, w, h, camera_mode, cam_eye.xyz, cam_forward, cam_right, cam_up.xyz, ro, rd);
        float3 P = ro + rd * center_view_t;

        // Decode the center surface normal ONCE (VB_THIN: `gThinNormal.rg`; base: `gNormal.rg`
        // — the SAME octahedral decode either way). The horizon step measures each neighbour's
        // ELEVATION ABOVE THE TANGENT PLANE this normal defines — a flat lit surface (delta
        // perpendicular to N) raises no horizon (AO = 1), a crevice (neighbours above the
        // tangent) does. CONSTANT across all slices/taps.
#if VB_THIN
        float3 N = oct_decode(gThinNormal.Load(coord).rg);
#else
        float3 N = oct_decode(gNormal.Load(coord).rg);
#endif

        // The screen-pixel march radius. PERSPECTIVE: a world radius R at view-depth z spans
        // ~ R*(h/2)/(z*tan(fovY/2)) pixels (clamped to a sane band). ORTHO: the view maps the
        // [-HALF_EXTENT, HALF_EXTENT] world span across h/2 pixels, so R spans R*(h/2)/HALF_EXTENT.
        float pix_radius;
        if (camera_mode == RAYGEN_CAM_PERSPECTIVE) {
            float z = max(dot(rd, cam_forward.xyz) * center_view_t, 1.0e-3);
            float pr = SSAO_RADIUS * ((float)h * 0.5) / (z * cam_forward.w);
            pix_radius = clamp(pr, SSAO_RADIUS_PIX_MIN, SSAO_RADIUS_PIX_MAX);
        } else {
            pix_radius = SSAO_RADIUS * ((float)h * 0.5) / RAYGEN_HALF_EXTENT;
        }

        // The Hilbert+R2 rotation slot (bit-exact; NO float fract/floor/trig/DIV). ONE 64x64
        // Hilbert index per pixel drives two R2 channels: ALPHA1 -> the rotation slot, ALPHA2 ->
        // the radial phase. `slot = (r2 * SSAO_ROT_N) >> 24` maps the Q0.24 fraction into
        // [0, ROT_N) by an integer scale. The table is 64 entries (was 16): on an EVEN-SLICE
        // axis set, rotating the set by its own slice spacing maps it onto itself, so the
        // EFFECTIVE dither classes = `SSAO_ROT_N / SSAO_SLICES` — 16 entries gave only TWO
        // distinct sampling patterns at 8 slices, whose spatially-coherent Hilbert+R2 layout
        // read as un-blurrable STREAKS radiating from contact regions. 64 entries keep >= 8
        // classes at a 2.8125° step (4x finer), so the residual class-to-class estimator delta
        // is small and fine-grained — noise the depth-aware resolve blur removes. The pick
        // stays INTEGER (a continuous/rational rotation needs an FDiv, whose 2.5-ULP Vulkan
        // tolerance breaks the bit-exact GPU<->host tap positions this shader is pinned to).
        uint hindex = ssao_hilbert(SSAO_HILBERT_W, px & (SSAO_HILBERT_W - 1u), py & (SSAO_HILBERT_W - 1u));
        uint slot = (ssao_r2(hindex, SSAO_R2_ALPHA1) * SSAO_ROT_N) >> 24u;
        float2 rot = SSAO_ROT[slot];

        // The radial step-phase jitter from the SECOND R2 channel (decorrelated from the rotation):
        // the top 8 bits of the Q0.24 fraction map to [1, 256] -> [1/256, 1.0] — STRICTLY positive,
        // so the nearest tap (`sp == 0`) never self-samples the center and the farthest tap reaches
        // exactly `pix_radius` (the prior outer reach). Integer + one exact `/256.0` ⇒ bit-exact
        // GPU↔host, NO `fract`, NO trig. The low-discrepancy phase spreads the step radii so any
        // residual ringing is high-frequency noise the depth-aware blur removes.
        uint r2_rad = ssao_r2(hindex, SSAO_R2_ALPHA2);
        float radial_phase = (float)((r2_rad >> 16u) + 1u) / 256.0;

        float occ = 0.0;
        [unroll]
        for (uint sl = 0u; sl < SSAO_SLICES; ++sl) {
            // The base slice axis: slices EVENLY split a half-turn (slice s at s*(pi/SLICES)),
            // read from the pre-baked `(cos, sin)` rotation table at stride `SSAO_BASE_STRIDE`
            // (Change A — real angular coverage; the pre-A code hardcoded only 2 axes, so 3+ slices
            // duplicated the (0,1) axis and added NO coverage). Then rotated by the per-pixel `rot`.
            // The 2D screen axis is lifted to a 3D in-screen direction along the camera right/up
            // basis (PERSPECTIVE) or the world x/y plane (ORTHO) — the same basis ray-gen builds from.
            float2 base = SSAO_ROT[sl * SSAO_BASE_STRIDE];
            // Rotate the base axis by the per-pixel rotation: (c -s; s c) * base. This 2D screen
            // axis picks the neighbour PIXEL (the tap offset); the horizon math measures
            // elevation against the center surface normal N, NOT this direction.
            float2 sdir2 = float2(base.x * rot.x - base.y * rot.y,
                                  base.x * rot.y + base.y * rot.x);

            // The + half-slice: SSAO_STEPS forward taps, tracking the horizon max `hc`. Its own
            // brace scope so `hc`/`n` (the names the generated span writes) do not collide with
            // the - half-slice's. The screen offset advances along +sdir2 here.
            float hc_pos = 0.0;
            {
                float hc = 0.0;
                float3 n = N;
                [unroll]
                for (uint sp = 0u; sp < SSAO_STEPS; ++sp) {
                    // Forward neighbour reconstruct (hand-written seam): offset in SCREEN pixels,
                    // round to integer, bounds-clamp, reconstruct Pp = ro' + rd' * view_t'. A tap
                    // out of bounds or onto a non-lit pixel reconstructs Pp = P (zero falloff).
                    float advance = ((float)sp + radial_phase) * pix_radius / (float)SSAO_STEPS;
                    int npx = (int)round((float)px + sdir2.x * advance);
                    int npy = (int)round((float)py + sdir2.y * advance);
                    float3 Pp = P;
                    if (npx >= 0 && npy >= 0 && npx < (int)w && npy < (int)h) {
                        int2 ncoord = int2(npx, npy);
#if VB_THIN
                        float nview_t = gViewT.Load(ncoord);
                        if (nview_t < SSAO_VIEWT_BG) {
#else
                        // The base arm keeps the ORIGINAL statement order (gMaterial load FIRST,
                        // then gViewT) — the no-define compile must stay byte-identical to the
                        // committed pre-VB_THIN .spv.
                        float nmask = gMaterial.Load(ncoord).b;
                        float nview_t = gViewT.Load(ncoord);
                        if (nmask > 0.5 && nview_t < SSAO_VIEWT_BG) {
#endif
                            float3 nro;
                            float3 nrd;
                            generate_ray((uint)npx, (uint)npy, w, h, camera_mode, cam_eye.xyz, cam_forward, cam_right, cam_up.xyz, nro, nrd);
                            Pp = nro + nrd * nview_t;
                        }
                    }
                    // === GENERATED ssao_horizon_step BEGIN ===
                    float3 delta = Pp - P;
                    float d2 = delta.x * delta.x + delta.y * delta.y + delta.z * delta.z;
                    float r2 = SSAO_RADIUS * SSAO_RADIUS;
                    float falloff = clamp(1.0 - d2 / r2, 0.0, 1.0);
                    float elev = max((delta.x * n.x + delta.y * n.y + delta.z * n.z) / max(sqrt(d2), SSAO_EPS), 0.0);
                    hc = max(hc, elev * falloff);
                    // === GENERATED ssao_horizon_step END ===
                }
                hc_pos = hc;
            }

            // The - half-slice: SSAO_STEPS forward taps along the negated screen offset. Same
            // brace-scoped `hc`/`n`; the screen offset is subtracted (`-sdir2`). The elevation
            // reference is the SAME center normal N (both half-slices measure against the tangent).
            float hc_neg = 0.0;
            {
                float hc = 0.0;
                float3 n = N;
                [unroll]
                for (uint sn = 0u; sn < SSAO_STEPS; ++sn) {
                    float advance = ((float)sn + radial_phase) * pix_radius / (float)SSAO_STEPS;
                    int npx = (int)round((float)px - sdir2.x * advance);
                    int npy = (int)round((float)py - sdir2.y * advance);
                    float3 Pp = P;
                    if (npx >= 0 && npy >= 0 && npx < (int)w && npy < (int)h) {
                        int2 ncoord = int2(npx, npy);
#if VB_THIN
                        float nview_t = gViewT.Load(ncoord);
                        if (nview_t < SSAO_VIEWT_BG) {
#else
                        // The base arm keeps the ORIGINAL statement order (gMaterial load FIRST,
                        // then gViewT) — the no-define compile must stay byte-identical to the
                        // committed pre-VB_THIN .spv.
                        float nmask = gMaterial.Load(ncoord).b;
                        float nview_t = gViewT.Load(ncoord);
                        if (nmask > 0.5 && nview_t < SSAO_VIEWT_BG) {
#endif
                            float3 nro;
                            float3 nrd;
                            generate_ray((uint)npx, (uint)npy, w, h, camera_mode, cam_eye.xyz, cam_forward, cam_right, cam_up.xyz, nro, nrd);
                            Pp = nro + nrd * nview_t;
                        }
                    }
                    // === GENERATED ssao_horizon_step BEGIN ===
                    float3 delta = Pp - P;
                    float d2 = delta.x * delta.x + delta.y * delta.y + delta.z * delta.z;
                    float r2 = SSAO_RADIUS * SSAO_RADIUS;
                    float falloff = clamp(1.0 - d2 / r2, 0.0, 1.0);
                    float elev = max((delta.x * n.x + delta.y * n.y + delta.z * n.z) / max(sqrt(d2), SSAO_EPS), 0.0);
                    hc = max(hc, elev * falloff);
                    // === GENERATED ssao_horizon_step END ===
                }
                hc_neg = hc;
            }

            occ = occ + (hc_pos + hc_neg);
        }

        // The final occlusion complement (the eDSL `ssao_estimate` tail, mirrored): the mean
        // per-slice horizon cosine scaled by strength, complemented to an AO factor, squared.
        float ao = clamp(1.0 - SSAO_STRENGTH * occ / SSAO_SLICES_F, 0.0, 1.0);
        ao_out = ao * ao;
    }

    ssao[uint2(px, py)] = ao_out;
}
