// SDFDDGI I2 — the probe-update compute pass (`sdf_probe_update.comp.hlsl`).
//
// Sphere-traces the CSG edit-list from each ACTIVE probe over a Fibonacci ray set, shades each
// hit (direct light + `sdf_soft_shadow_ranged` visibility), and blends the results into the
// probe's octahedral irradiance tile (+ two-moment depth tile). Subset-limited by round-robin
// from frame one (plan §4). INTERNAL checkpoint (strobes without hysteresis). All work stays
// behind the GI-OFF 0%-gate: the pass is recorded ONLY when `ResolvedDdgi::enabled()`.
//
// # Single-source (eDSL — `boyko_shaderdsl`)
//
// The `// === GENERATED oct_decode / probe_march / probe_blend / probe_depth_blend BEGIN/END
// ===` spans are MACHINE-GENERATED by `boyko_shaderdsl::emit` (this file is produced by the
// `emit_probe_gi` bin). A hand-edit of a generated span fails the `emit_probe_gi` drift
// gate. The `sdf_soft_shadow_ranged` visibility function is COPIED VERBATIM from
// `deferred_pbr.hlsl` (pinned equal by `sdf_soft_shadow_ranged_copy_matches_resolve`); a shared
// `.hlsli` dedup is deferred to I3.
//
// # The I2 → I3 oct-decode contract (load-bearing)
//
// The tile-UV↔texel REMAP + probe-spacing reconstruction I3 owns MUST live in the texel→UV
// chain OUTSIDE `oct_decode` (in the hand-written `texel_dir_irr`/`texel_dir_depth` glue),
// never inside `oct_decode` — else this pass's WRITE iteration and I3's READ desync.
//
// # Compiled offline (hermetic) with, per `GI_MAX_IT` variant:
//   dxc -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3 \
//       sdf_probe_update_it32.comp.hlsl -Fo sdf_probe_update_it32.comp.spv

// --- Resources (dedicated update bind-group, set 0 — plan §2.2) ----------------------------
//   t0 : StructuredBuffer<uint>   Buf            — the SDF edit-list (`sdf_field.hlsli` contract)
//   u1 : RWTexture2DArray<float4> gIrrOut        — the irradiance atlas (B10G11R11, STORAGE write)
//   u2 : RWTexture2DArray<float2> gDepthOut      — the two-moment depth atlas (RG16F, STORAGE write)
//   t3 : RWStructuredBuffer<uint> Classification — 1 u32/probe (bit0 active, bit1 converged-once)
//   t4 : StructuredBuffer<float4> RayTable       — the Fibonacci ray directions (boot-static)
//   t5 : StructuredBuffer<uint>   LightBuf       — the L0 light table
//   b6 : cbuffer DdgiUpdate                      — the grid/subset/ray params
//
// The `[[vk::image_format]]` pin fixes each storage image's OpTypeImage: `r11g11b10f` →
// SPIR-V `R11fG11fB10f` (the exact format for VK_FORMAT_B10G11R11_UFLOAT_PACK32),
// `rg16f` → `Rg16f` (VK_FORMAT_R16G16_SFLOAT). A wrong decoration string is silent write
// corruption (plan §10.3 / P2-1). `shaderStorageImageWriteWithoutFormat` is OFF.
StructuredBuffer<uint> Buf : register(t0);
[[vk::image_format("r11g11b10f")]] RWTexture2DArray<float4> gIrrOut   : register(u1);
[[vk::image_format("rg16f")]]      RWTexture2DArray<float2> gDepthOut : register(u2);
// `Classification` is READ+WRITE, so it binds a `u` UAV register (HLSL requires `u` for a
// `RWStructuredBuffer`); the Vulkan binding number is still 3 (the `u3`/`t3` namespaces are
// separate in HLSL, unified in the SPIR-V binding). RayTable/LightBuf are READ-ONLY `t` SRVs.
RWStructuredBuffer<uint>  Classification : register(u3);
StructuredBuffer<float4>  RayTable       : register(t4);
StructuredBuffer<uint>    LightBuf       : register(t5);

// The `sdf_field.hlsli` INCLUDE CONTRACT requires `StructuredBuffer<uint> Buf : register(t0)`
// in scope BEFORE the include (the field eval reads `Buf[0]` = edit_count, then the packed
// edits). It provides `field_distance(p)`, `sdf(p)`, `sdf_normal(p)` (the central-difference
// gradient — the SAME eDSL-generated `sdf_normal` the resolve uses, pinned by
// `sdf_field_edsl_sync`), `MAX_SDF_EDITS`, `GRAD_H`, `FIELD_LIPSCHITZ_L`, etc.
#include "sdf_field.hlsli"

// The shared light-table decode (`light_table.hlsli`) — a READ-ONLY shared header (like
// `sdf_field.hlsli`), guarded by `#ifndef LIGHT_TABLE_HLSLI`, indexing the SAME
// `StructuredBuffer<uint> LightBuf` already in scope above. It does NOT touch the frozen
// resolve. Provides `load_light(LightBuf, i)` (the 16-word header + 12-word GpuLight[] layout,
// `dir@+0..2 / kind@+3 / pos@+4..6 / range@+7 / color@+8..10 / cone@+11`), `light_kind()`, and
// the `LIGHT_KIND_*` enum — the ONE source of truth for the GPU light table (P0-1 fix).
#include "light_table.hlsli"

// --- The shadow-march tuning (mirror `deferred_pbr.hlsl` — the copied `sdf_soft_shadow_ranged`
// reads these; `FIELD_LIPSCHITZ_L`/`GRAD_H`/`FAR` come from `sdf_field.hlsli`). Identical values
// to the resolve so the copied marcher behaves byte-identically. `EPS` is the field hit epsilon
// (also the base of `GI_HIT_EPS` / `SHADOW_HIT_EPS`), declared here before its consumers.
static const float EPS                = 0.001;
static const uint  MAX_IT             = 128u;
static const float SHADOW_K           = 8.0;
static const float SHADOW_MINT        = 16.0 * GRAD_H;
static const float SHADOW_MINT_STEP   = 16.0 * GRAD_H;
static const float SHADOW_HIT_EPS     = 2.0 * EPS;
// The normal-offset march-origin lift (anti grazing-acne) — the SAME value the resolve uses
// (`deferred_pbr.hlsl` SHADOW_NORMAL_BIAS = 0.02), so the GI shadow origin agrees with it (P1-1).
static const float SHADOW_NORMAL_BIAS = 0.02;

// binding b6: the per-frame update parameters (grid origin/spacing/dims + subset + ray count +
// light count). `grid_dims.xyz` = the grid dims (probes per axis) as uint; `origin.xyz` = the
// grid world origin, `origin.w` = the probe spacing. Phase 2's Rust `DdgiUpdateUbo` matches this
// field name (P2-1 — `grid_dims`, NOT the misleading `inv_spacing_dims`, which held dims, not an
// inverse spacing).
cbuffer DdgiUpdate : register(b6) {
    float4 origin;             // xyz = grid world origin, w = probe spacing
    uint4  grid_dims;          // xyz = grid dims (probes per axis), w = free
    uint   frame_index;        // host-frame-derived (the round-robin phase)
    uint   subset_n;           // round-robin divisor N (divides DDGI_PROBE_COUNT)
    uint   rays_per_probe;     // Fibonacci ray count (== RayTable length)
    uint   light_count;        // light-table entry count
};

// --- The atlas geometry (mirror boyko_rhi_vulkan::ddgi; host-pinned) -----------------------
// Y-plane-major: array layer = probe Y; within a layer, tile column = X, tile row = Z. The
// irradiance tile is 8x8 (6x6 valid + 1-texel border); the depth tile 16x16 (14x14 + border).
static const uint  GI_MAX_IT           = 32u; // the swept `[loop]` trip count (this variant)
// The `probe_march` tuning (the generated span spells these SYMBOLICALLY — plan §1.2). The
// SHADOW_MINT-class start bias, the occluder-hit epsilon, the min per-step advance, and the
// escape bound. GRAD_H/EPS come from `sdf_field.hlsli` / the shadow tuning block above.
static const float GI_MINT      = 16.0 * GRAD_H;
static const float GI_HIT_EPS   = 2.0 * EPS;
static const float GI_MINT_STEP = 16.0 * GRAD_H;
static const float GI_T_MAX     = 10.0;
static const uint  DDGI_IRR_TILE_EDGE   = 8u;
static const uint  DDGI_DEPTH_TILE_EDGE  = 16u;
static const uint  DDGI_IRR_VALID_EXTENT  = 6u;   // the valid octahedral interior extent (irr)
static const uint  DDGI_DEPTH_VALID_EXTENT = 14u; // the valid interior extent (depth)
static const uint  DDGI_TILE_BORDER      = 1u;    // the 1-texel border inset
static const float DDGI_MIN_SUM_WEIGHT   = 1.0e-6; // the resolve-side cosine-sum divide guard

// The classification bits (plan §4).
static const uint DDGI_CLASS_ACTIVE    = 1u;      // bit0: probe not inside geometry
static const uint DDGI_CLASS_CONVERGED = 2u;      // bit1: first successful tile write done
static const float GI_INSIDE_EPS       = 0.0;     // `field_distance(probe) < eps` ⇒ inside ⇒ inactive

// The groupshared cooperative ray cache (plan §2.4): one thread-block per active probe; the 64
// threads cooperatively march the rays into LDS, sync, then cooperatively gather the texels.
// R = rays_per_probe <= 128; 128 * (dir3 + L3 + t1) = 128 * 7 floats = 3.5 KB, well within 32 KB.
static const uint GI_MAX_RAYS = 128u;
groupshared float3 gs_dir[GI_MAX_RAYS]; // the cached ray direction
groupshared float3 gs_L[GI_MAX_RAYS];   // the cached shaded radiance
groupshared float  gs_t[GI_MAX_RAYS];   // the cached marched hit distance

// The multi-light SDF shadow marcher — copied VERBATIM from `deferred_pbr.hlsl` (pinned equal by
// `sdf_soft_shadow_ranged_copy_matches_resolve`). `t_max` = the light reach.
float sdf_soft_shadow_ranged(float3 p, float3 n, float3 L, float t_max) {
float res = 1.0;
float t = SHADOW_MINT;
[loop]
for (uint i = 0u; i < MAX_IT; ++i) {
float d = field_distance(p + L * t);
res = min(res, SHADOW_K * d / t);
if (d < SHADOW_HIT_EPS) {
return 0.0;
}
t = t + max(d / FIELD_LIPSCHITZ_L, SHADOW_MINT_STEP);
if (t > t_max) {
break;
}
}
return clamp(res, 0.0, 1.0);
}


// === GENERATED oct_decode BEGIN ===
float3 oct_decode(float2 e) {
    float ex = e.x * 2.0 - 1.0;
    float ey = e.y * 2.0 - 1.0;
    float nz = 1.0 - abs(ex) - abs(ey);
    float t = clamp((-nz), 0.0, 1.0);
    float nx = ex + (ex >= 0.0 ? (-t) : t);
    float ny = ey + (ey >= 0.0 ? (-t) : t);
    return normalize(float3(nx, ny, nz));
}
// === GENERATED oct_decode END ===

// The GI-ray sphere-trace, wrapping the eDSL-generated `probe_march` span (which spells a
// function-`return true/false` + writes the `out float hit_t`). Returns the occluder-hit flag;
// `hit_t` = the marched hit distance (or GI_T_MAX on a sky miss). The span reads `ro`/`rd`.
bool probe_march(float3 ro, float3 rd, out float hit_t) {
    // === GENERATED probe_march BEGIN ===
        float t = GI_MINT;
        [loop]
        for (uint i = 0u; i < GI_MAX_IT; ++i) {
            float d = field_distance(ro + rd * t);
            if (d < GI_HIT_EPS) {
                hit_t = t;
                return true;
            }
            t = t + max(d, GI_MINT_STEP);
            if (t > GI_T_MAX) {
                break;
            }
        }
        hit_t = t;
        return false;
    // === GENERATED probe_march END ===
}

// --- Probe index <-> grid coordinate + world position (Y-plane-major) ----------------------
uint3 probe_coord(uint probe_index) {
    uint dx = grid_dims.x;
    uint dy = grid_dims.y;
    uint x = probe_index % dx;
    uint y = (probe_index / dx) % dy;
    uint z = probe_index / (dx * dy);
    return uint3(x, y, z);
}

float3 probe_world_pos(uint3 c) {
    // origin + coord * spacing (the world-fixed D1 grid — probe i is the same world point
    // every frame).
    return origin.xyz + float3(c) * origin.w;
}

// The atlas tile texel origin (Y-plane-major): array layer = Y; ox = X * tile_edge; oy = Z *
// tile_edge (mirrors `boyko_rhi_vulkan::ddgi::ddgi_probe_tile_origin`).
uint3 tile_origin(uint3 c, uint tile_edge) {
    return uint3(c.y, c.x * tile_edge, c.z * tile_edge);
}

// The valid-interior texel (tx, ty) -> the [0,1]^2 tile UV oct_decode remaps to [-1,1]^2. The
// texel CENTER maps through `(tx + 0.5) / VALID_EXTENT` (mirrors the I0b host oracle
// `goldens::ddgi_texel_dir`). This tile-UV chain is I2's business; the I3 remap lives OUTSIDE
// oct_decode (the load-bearing contract).
float2 texel_uv(uint tx, uint ty, uint valid_extent) {
    float extent = (float)valid_extent;
    return float2(((float)tx + 0.5) / extent, ((float)ty + 0.5) / extent);
}

// --- The direct-light shade of one ray hit (plan §1.6 per-ray glue) -------------------------
// Loops the light table, accumulating each DIRECTIONAL light's diffuse Lambert term gated by the
// SDF visibility `sdf_soft_shadow_ranged`. A minimal single-bounce DIFFUSE direct shade
// (multi-bounce probe feedback is I5; specular is a later cone-trace). `hit_pos` is the marched
// surface point, `n` the TRUE SDF field normal at the hit (`sdf_normal(hit_pos)`, P1-2).
//
// Layout / double-count fix (P0-1): the light table is the shared `light_table.hlsli` layout —
// 16-word header, 12-word `GpuLight[]` entries; `e.dir` is the TO-LIGHT direction (normalize it),
// and `e.color` is `linear_color × illuminance` ALREADY BAKED (`from_directional`), so the shade
// multiplies by `e.color` ONLY — NO separate illuminance word (the resolve does the same:
// `lit_direct += (diff + spec) * (NoL * vis) * L.color`).
float3 shade_hit(float3 hit_pos, float3 n) {
    float3 lit = float3(0.0, 0.0, 0.0);
    for (uint li = 0u; li < light_count; ++li) {
        LightElem e = load_light(LightBuf, li);
        // I2 handles DIRECTIONAL lights (the showcase's main lights). Point/spot need per-kind
        // attenuation/cone handling the resolve does in its L0b block; skip them here rather than
        // silently mis-shading them as directional.
        // TODO(I-later): fold POINT/SPOT into the GI shade (attenuation + cone), per resolve L0b.
        if (light_kind(e) != LIGHT_KIND_DIRECTIONAL) { continue; }
        // `e.dir` is the TO-LIGHT world direction (the resolve `normalize(L.dir)`); the diffuse
        // Lambert cosine against the true field normal.
        float3 l = normalize(e.dir);
        float NoL = max(dot(n, l), 0.0);
        if (NoL <= 0.0) { continue; }
        // SDF visibility toward the light, ranged to GI_T_MAX (a directional reaches everywhere),
        // from a NORMAL-BIASED origin so grazing rays clear the surface (anti self-occlusion,
        // P1-1). Mirrors the resolve `sdf_soft_shadow_ranged(P + n*SHADOW_NORMAL_BIAS, n, l, ...)`.
        float vis = sdf_soft_shadow_ranged(hit_pos + n * SHADOW_NORMAL_BIAS, n, l, GI_T_MAX);
        // Diffuse only: `e.color` already carries `color × illuminance` (no double-count).
        lit += e.color * (NoL * vis);
    }
    return lit;
}

[numthreads(64, 1, 1)]
void main(uint3 gid : SV_GroupID, uint3 lid : SV_GroupThreadID) {
    // One thread-block per active-subset probe. Map block -> probe index in the current subset:
    // probe_index = block * subset_n + (frame_index % subset_n) (plan §4 round-robin). The
    // dispatch is sized to `DDGI_PROBE_COUNT / subset_n` blocks.
    uint phase = frame_index % subset_n;
    uint probe_index = gid.x * subset_n + phase;

    uint3 c = probe_coord(probe_index);
    float3 pw = probe_world_pos(c);
    uint R = min(rays_per_probe, GI_MAX_RAYS);

    // Classification bit0 (active): re-evaluated each scheduled frame (geometry is dynamic).
    // `inside = field_distance(probe) < GI_INSIDE_EPS` ⇒ the probe is buried ⇒ skip it.
    bool inside = field_distance(pw) < GI_INSIDE_EPS;
    if (inside) {
        if (lid.x == 0u) {
            // Clear the active bit (keep the converged bit) so the resolve treats a
            // newly-buried probe as inactive.
            Classification[probe_index] = Classification[probe_index] & DDGI_CLASS_CONVERGED;
        }
        return;
    }

    // (1) Cooperatively march the rays into groupshared (thread i marches rays i, i+64, ...).
    for (uint r = lid.x; r < R; r += 64u) {
        float3 rd = normalize(RayTable[r].xyz);
        float hit_t;
        bool hit = probe_march(pw, rd, hit_t);
        // Shade the hit; a sky miss contributes zero radiance + GI_T_MAX depth.
        float3 L = float3(0.0, 0.0, 0.0);
        if (hit) {
            float3 hit_pos = pw + rd * hit_t;
            // The TRUE SDF field normal at the hit (`sdf_normal` from `sdf_field.hlsli` — the SAME
            // eDSL-generated central-difference gradient the resolve uses, pinned by
            // `sdf_field_edsl_sync`; NOT the coarse `-rd`, P1-2). Its ~6 field taps/hit are a
            // real part of the `ddgi_probe_update_cost` bench (cost-honesty).
            float3 n = sdf_normal(hit_pos);
            L = shade_hit(hit_pos, n);
        } else {
            hit_t = GI_T_MAX;
        }
        gs_dir[r] = rd;
        gs_L[r] = L;
        gs_t[r] = hit_t;
    }
    GroupMemoryBarrierWithGroupSync();

    // (2) Cooperatively gather the irradiance texels (6x6 valid) across the 64 threads. Each
    // thread owns texels `t = lid.x, lid.x+64, ...` over the DDGI_IRR_VALID_EXTENT^2 grid.
    uint3 irr_org = tile_origin(c, DDGI_IRR_TILE_EDGE);
    uint irr_valid = DDGI_IRR_VALID_EXTENT * DDGI_IRR_VALID_EXTENT;
    for (uint it = lid.x; it < irr_valid; it += 64u) {
        uint tx = it % DDGI_IRR_VALID_EXTENT;
        uint ty = it / DDGI_IRR_VALID_EXTENT;
        float2 uv = texel_uv(tx, ty, DDGI_IRR_VALID_EXTENT);
        // texelUV -> texelDir. The tile-UV -> [-1,1]^2 remap lives HERE (outside oct_decode).
        float3 texelDir = oct_decode(uv);
        float sum_r = 0.0, sum_g = 0.0, sum_b = 0.0, sum_w = 0.0;
        for (uint r = 0u; r < R; ++r) {
            float3 rayDir = gs_dir[r];
            float l_r = gs_L[r].x, l_g = gs_L[r].y, l_b = gs_L[r].z;
            // === GENERATED probe_blend BEGIN ===
            float w = max(texelDir.x * rayDir.x + texelDir.y * rayDir.y + texelDir.z * rayDir.z, 0.0);
            sum_r = sum_r + l_r * w;
            sum_g = sum_g + l_g * w;
            sum_b = sum_b + l_b * w;
            sum_w = sum_w + w;
            // === GENERATED probe_blend END ===
        }
        float3 irr = float3(sum_r, sum_g, sum_b) / max(sum_w, DDGI_MIN_SUM_WEIGHT);
        // Write the valid interior texel (offset past the 1-texel border).
        uint3 dst = uint3(irr_org.y + DDGI_TILE_BORDER + tx, irr_org.z + DDGI_TILE_BORDER + ty, irr_org.x);
        gIrrOut[dst] = float4(irr, 1.0);
    }

    // (3) Cooperatively gather the depth texels (14x14 valid) — the two-moment tile.
    uint3 depth_org = tile_origin(c, DDGI_DEPTH_TILE_EDGE);
    uint depth_valid = DDGI_DEPTH_VALID_EXTENT * DDGI_DEPTH_VALID_EXTENT;
    for (uint dt = lid.x; dt < depth_valid; dt += 64u) {
        uint tx = dt % DDGI_DEPTH_VALID_EXTENT;
        uint ty = dt / DDGI_DEPTH_VALID_EXTENT;
        float2 uv = texel_uv(tx, ty, DDGI_DEPTH_VALID_EXTENT);
        float3 texelDir = oct_decode(uv);
        float dmean = 0.0, dmean2 = 0.0, dw = 0.0;
        for (uint r = 0u; r < R; ++r) {
            float3 rayDir = gs_dir[r];
            float t = gs_t[r];
            // === GENERATED probe_depth_blend BEGIN ===
            float w = max(texelDir.x * rayDir.x + texelDir.y * rayDir.y + texelDir.z * rayDir.z, 0.0);
            float wt = w * t;
            dmean = dmean + wt;
            dmean2 = dmean2 + wt * t;
            dw = dw + w;
            // === GENERATED probe_depth_blend END ===
        }
        float inv = 1.0 / max(dw, DDGI_MIN_SUM_WEIGHT);
        float2 moments = float2(dmean * inv, dmean2 * inv);
        uint3 dst = uint3(depth_org.y + DDGI_TILE_BORDER + tx, depth_org.z + DDGI_TILE_BORDER + ty, depth_org.x);
        gDepthOut[dst] = moments;
    }

    // (4) One thread stamps the converged-once bit (+ keeps active set): the tile is written.
    if (lid.x == 0u) {
        Classification[probe_index] = DDGI_CLASS_ACTIVE | DDGI_CLASS_CONVERGED;
    }
}
