// VB-SV0 (`docs/VB-SV0-SDF-SHADOW-PLAN.md` §4.1): the SHARED SDF shadow/contact-AO LEAF header.
//
// Before this file existed, `sdf_soft_shadow_ranged` had ONE hand-placed definition in
// `deferred_pbr.hlsl` and `sdf_ao` had ONE in `sdf_gbuffer_composite.hlsl`, and SV0's three VB
// lit-producer tails each needed both. Naively that is five copies of the ranged shadow leaf and
// four of the AO leaf, only ONE of which (the ranged shadow) has an eDSL generator to re-emit
// from (`boyko_shaderdsl::emit::emit_hlsl_sdf_soft_shadow_ranged`; there is NO `emit_hlsl_sdf_ao`
// — plan §4.1's corrected fact). This header cuts the ranged shadow to TWO definitions
// (here + the generated `sdf_probe_update.comp.hlsl:160` copy, deliberately NOT re-pointed so the
// frozen probe-update `.spv` does not move) and `sdf_ao` to TWO (here + the marcher's, which is
// the frozen-`.spv` blast radius this campaign protects and is therefore left untouched).
//
// # INCLUDE CONTRACT (preconditions — all must be in scope BEFORE the `#include`)
//
//   * `field_distance(float3)`      — `sdf_field.hlsli`, which itself requires
//                                     `StructuredBuffer<uint> Buf : register(t0)` declared first.
//   * `MAX_IT`, `SHADOW_K`, `SHADOW_MINT`, `SHADOW_MINT_STEP`, `SHADOW_HIT_EPS`
//                                   — the shadow-march tuning block (`deferred_pbr.hlsl:466-474`
//                                     and its verbatim copies in the VB tails).
//   * `FIELD_LIPSCHITZ_L`           — `sdf_field.hlsli`.
//
// This header declares NO binding and NO resource: it is pure leaf math over `field_distance`.
//
// # What pins each half
//
//   * `sdf_soft_shadow_ranged` is GENERATED. The `// === GENERATED ... BEGIN/END ===` sentinels
//     below are load-bearing: `sdf_field_edsl_sync.rs::sdf_soft_shadow_ranged_matches_edsl_emit`
//     re-runs the generator and asserts this file contains its output, and
//     `ddgi_probe_gi_sync.rs::sdf_soft_shadow_ranged_copy_matches_resolve` extracts the function
//     from THIS file and asserts the probe-update shader's copy is token-identical. HAND-EDITING
//     the span fails both. Regenerate with
//     `cargo run -p boyko_shaderdsl --features emit --bin emit_field` and re-splice.
//   * `sdf_ao` is NOT generated (no eDSL body exists for it — plan §4.1/R8). It is a verbatim
//     copy of `sdf_gbuffer_composite.hlsl:532-541` and is pinned to it by a cross-file textual
//     identity test, a deliberately WEAKER instrument than an eDSL re-emit pin. The three AO
//     consts below are copied from `sdf_gbuffer_composite.hlsl:488-490` and are pinned
//     separately, because a body-identity test structurally cannot see a constant declared
//     outside the body: change `AO_FALLOFF` in one file only and the two bodies stay
//     byte-identical while computing different things.

// === P6 R1 — the `t_max`-RANGED soft-shadow leaf (multi-light SDF shadows) ===============
// GENERATED by `boyko_shaderdsl::emit::emit_hlsl_sdf_soft_shadow_ranged()`; a SEPARATELY-
// named clone of the marcher's frozen `sdf_soft_shadow` whose escape break spells the RUNTIME
// `t_max` instead of the hardcoded `T_MAX` (B3 — option a). The `sdf_soft_shadow_ranged_
// matches_edsl_emit` sync pin (in `boyko_rhi_vulkan/tests/sdf_field_edsl_sync.rs`) pins this
// to the generator; a hand-edit fails CI. `t_max` = the light DISTANCE for a punctual caster
// or `T_MAX` for an extra directional. The `dot(n, L)` early-out is the resolve's per-light
// `NoL <= 0` skip (hand-written in the loop), so this body is the loop+tail only.
// === GENERATED sdf_soft_shadow_ranged BEGIN ===
float sdf_soft_shadow_ranged(float3 p, float3 n, float3 L, float t_max) {
    float res = 1.0;
    float t = SHADOW_MINT;
    [loop]
    for (uint i = 0u; i < MAX_IT; ++i) {
        float d = field_distance(p + L * t);
        res = min(res, SHADOW_K * d / t);
        if (d < SHADOW_HIT_EPS) {
            return 0.0;
        }
        t = t + max(d / FIELD_LIPSCHITZ_L, SHADOW_MINT_STEP);
        if (t > t_max) {
            break;
        }
    }
    return clamp(res, 0.0, 1.0);
}
// === GENERATED sdf_soft_shadow_ranged END ===

// A2 tuning (owner defaults). Mirror the host consts.
static const float AO_STEP     = 0.1;   // step between the 5 taps along the normal
static const float AO_FALLOFF  = 0.95;  // per-tap geometric falloff (AO_FALLOFF^i)
static const float AO_STRENGTH = 1.0;   // overall occlusion strength

// A2: 5-tap ambient occlusion. March the surface normal `n` from `p`, summing the
// `(h - d)` field-deficit (how much closer the surface is than the unoccluded clearance
// would be) weighted by AO_FALLOFF^i. `field_distance` is the FROZEN field. Returns an
// occlusion factor in [0,1] (1 = unoccluded).
float sdf_ao(float3 p, float3 n) {
    float occ = 0.0;
    [unroll]
    for (uint i = 1u; i <= 5u; ++i) {
        float h = (float)i * AO_STEP;
        float d = field_distance(p + n * h);
        occ += (h - d) * pow(AO_FALLOFF, (float)i);
    }
    return clamp(1.0 - AO_STRENGTH * occ, 0.0, 1.0);
}
