"""Window 9a, 2026-09-30: build rows9a.extra.json (the Rapier block C4-RAPIER) and record the four Rapier pose fixtures into
gate/fixtures/fixtures.json. Deterministic and idempotent: run it again after editing, never edit rows9a.extra.json by hand.
  python -B tools/mkextra9a.py
Inputs (all COPIES inside the window dir, so the harness dir is never read at launch): gate/rapier/pins.json, gate/rapier/window9a_rows.md
(the two reviewed rows RP-D / RP-M are PARSED out of its json block, not retyped), bin/rapier_parity_simd{8,4}_<sha8>.exe and
gate/fixtures/R{D,M}{8,4}.pose. Orchestrator rulings for this block: (a) own block C4-RAPIER, priority 1.5 (after C4-AB, before C4-G5), K 9
= 3 passes x 3 rounds, the same pass order (p0 reversed, p1 forward, p2 reversed); the four configurations RP-D/RP-M x simd8/simd4 are
adjacent inside every W group of every round (the row order RP-D, RP-M and each row's binaries [rs8, rs4] make it so: cell_order walks
rows inside a W group and binaries inside a row); adjacency to our C4-JD / C4-JT rows is NOT required (a different block).
One untimed warm-up per exe per pass (window9a_rows.md, Protocol): RP-D rs8 W8 and RP-D rs4 W8."""
import hashlib
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
W9 = os.path.dirname(HERE)


def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


pins_path = os.path.join(W9, 'gate', 'rapier', 'pins.json')
pins = json.load(open(pins_path, encoding='utf-8'))
doc = open(os.path.join(W9, 'gate', 'rapier', 'window9a_rows.md'), encoding='utf-8').read()
block = re.search(r'```json\n(.*?)```', doc, re.S).group(1)
doc_rows = [json.loads(l) for l in block.splitlines() if l.strip()]
assert [r['id'] for r in doc_rows] == ['RP-D', 'RP-M'], [r['id'] for r in doc_rows]

EXE = {'rs8': ('simd8', 'bin/rapier_parity_simd8_736c2a06.exe'), 'rs4': ('simd4', 'bin/rapier_parity_simd4_1e5136ca.exe')}
sources = open(os.path.join(W9, 'gate', 'rapier', 'SOURCES.sha256'), encoding='utf-8').read().split()
src_line = '; '.join(f'{sources[i + 1].lstrip("*")} {sources[i][:8]}' for i in range(0, len(sources), 2))
binaries = {}
for key, (arm, exe) in EXE.items():
    sha = sha256(os.path.join(W9, exe))
    assert sha == pins['exe_sha256'][arm], f'{key}: {exe} sha256 {sha} != the pins\' {pins["exe_sha256"][arm]}'
    binaries[key] = {
        'exe': exe, 'kind': 'rapier', 'arm': arm, 'sha256_pin': sha,
        'commit': f'rapier-parity rev 2 (2026-09-30), rapier3d {pins["rapier_version"]} --locked, arm {arm}; sources sha256 (gate/rapier/SOURCES.sha256): {src_line}',
        'what': (f'Rapier {pins["rapier_version"]} parity harness, arm {arm} ({pins["arms"][arm]["lanes"]} SIMD lanes), a byte copy (sha256 checked) of '
                 f'D:/tmp/rapier-parity/gate/bin/rapier-parity-{arm}.exe; run by path, timed with counters off'),
    }

rows = []
for r in doc_rows:
    r = json.loads(json.dumps(r))
    assert r['kind'] == 'rapier' and r['binaries'] == ['rs8', 'rs4'] and r['workers'] == [1, 2, 4, 8, 16] and r['steps'] == 500
    r['blocks'] = ['C4-RAPIER']            # ruling (a): the doc's shared block PAR becomes the window's own block
    r['note'] = ('window 9a Rapier row, rows and void rules V1-V9 of gate/rapier/window9a_rows.md; the four configurations (RP-D/RP-M x rs8/rs4) '
                 'are adjacent at every W of every round (cell_order: rows in list order, binaries in order); validated by window9a_run.'
                 'rapier_check (V1-V9); rows_pin = the per-step mean row-iteration count of the harness\'s W1 receipt twin over each metric '
                 'window, recorded for the analysis (R-ROW-D / R-ROW-M), not gated by the driver')
    rows.append(r)

overlay = {
    '_comment': ('Window 9a Rapier block, GENERATED by tools/mkextra9a.py (never edit by hand). Merged over rows9a.json by the driver at start '
                 '(binaries by key, rows by id, blocks by name; blocks ordered by priority). Orchestrator ruling (a): the block C4-RAPIER '
                 'has priority 1.5 (after C4-AB, before C4-G5), K 9 = 3 passes x 3 rounds, the same pass order.'),
    'rapier': {'pins': 'gate/rapier/pins.json', 'pins_sha256': sha256(pins_path),
               'rules': 'V1-V9 of gate/rapier/window9a_rows.md, implemented by window9a_run.rapier_check / validate_rapier'},
    'binaries': binaries,
    'blocks': [{
        'name': 'C4-RAPIER', 'item': 'Rapier 0.36 vs boyko J-T (window 9a Rapier rows)', 'priority': 1.5, 'passes': 3, 'rounds': 3,
        'warmups': [['RP-D', 'rs8', 8], ['RP-D', 'rs4', 8]],
        'note': ('K 9 = 3 passes x 3 rounds. One untimed warm-up PER EXE per pass (RP-D rs8 W8, RP-D rs4 W8: window9a_rows.md, Protocol). '
                 'Every Rapier cell is adjacent to its three sibling configurations at each W of each round; ours J-T is a different block '
                 '(C4-AB) and is NOT required to be adjacent. Which arm is faster is decided by the analysis from the rows at every W.')}],
    'rows': rows,
}
with open(os.path.join(W9, 'rows9a.extra.json'), 'w', encoding='utf-8', newline='\n') as f:
    json.dump(overlay, f, indent=1)

# The four pose fixtures: files under gate/fixtures/ (byte copies of the harness's, sha256 checked against the pins), their hashes in
# fixtures.json (the driver's verify_fixtures reads both; verify_rapier_pins re-checks the sha256 at every start).
fx_path = os.path.join(W9, 'gate', 'fixtures', 'fixtures.json')
fx = json.load(open(fx_path, encoding='utf-8'))
for arm, a in pins['arms'].items():
    for cfg, c in a['cfgs'].items():
        name = os.path.basename(c['fixture']).split('.')[0]
        path = os.path.join(W9, 'gate', 'fixtures', name + '.pose')
        assert sha256(path) == c['fixture_sha256'], f'{name}: sha256 differs from the pins'
        fx[name] = {'hash': c['pose_hash'], 'sha256': c['fixture_sha256'], 'arm': arm, 'cfg': cfg,
                    'recorded_by': 'rapier-parity gate g2 (the W1 --receipt run of the arm), a byte copy of D:/tmp/rapier-parity/gate/fixtures/',
                    'kind': 'rapier'}
with open(fx_path, 'w', encoding='utf-8', newline='\n') as f:
    json.dump(fx, f, indent=1)
print('rows9a.extra.json: 2 rows, 2 binaries, 1 block; fixtures.json:', sorted(k for k in fx if fx[k].get('kind') == 'rapier'))
