//! [`TextureGpu`] — the GPU-resident, mip-chained, bindless-registered texture asset
//! record (textured-PBR campaign rung T2).
//!
//! Mirrors [`MeshGpu`](crate::mesh::MeshGpu) / [`mesh_assets`](crate::mesh_assets)'s
//! shape: [`TextureGpu`] OWNS its RHI
//! [`VulkanTexture`](boyko_rhi_vulkan::texture::VulkanTexture) directly (Principle 0's
//! FFI/GPU exception — the same class as a mesh's vertex/index buffers), so
//! [`Assets<TextureGpu>`](boyko_ecs::ecs::core::asset::Assets) itself IS the GPU-resident
//! table (no separate mirror). The
//! mint/resolve/teardown domain API ([`TextureAssetsExt`]) is attached via an
//! extension trait, exactly as [`MeshAssetsExt`](crate::mesh_assets::MeshAssetsExt).
//!
//! # Live wiring (textured-PBR T6b/T6c/T7)
//!
//! [`Assets<TextureGpu>`](boyko_ecs::ecs::core::asset::Assets) /
//! [`BindlessTextureTable`] are registered as `NonSend`
//! resources by `boyko_app::runner` at boot (T6b); the bindless descriptor set is bound
//! at set 1 by the TEXTURED raster pipeline (T6c, `gbuffer_mrt_tex.{vs,fs}`).
//! [`TextureAssetsExt::register_texture`] / [`build_texture_gpu`] / [`GpuUpload`] for
//! [`TextureGpu`] are the load-time device path a scene's `setup` system drives directly
//! — exercised end to end by `pbr_material_showcase.rs` (T7) and `textured_smoke.rs`, as
//! well as this module's unit tests and the `#[ignore]` GPU smoke test. Teardown retires
//! through
//! [`asset_refcount::retire_deferred_frees`](crate::asset_refcount::retire_deferred_frees)
//! (bindless-slot recycle + [`OrphanedTextureGpu::drain_ready`]).
//!
//! # sRGB via a UNORM image + a mutable sRGB view (Decision D2)
//!
//! `R8G8B8A8_UNORM` optimal-tiling images have MANDATORY `BLIT_SRC`/`BLIT_DST`
//! support; `R8G8B8A8_SRGB` does not guarantee it. So a color-space-sRGB texture
//! (albedo, emissive) is created as UNORM + `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT`,
//! mip-generated by LINEAR blit on the UNORM image (guaranteed blit support), and
//! SAMPLED through an `R8G8B8A8_SRGB` view (`TextureDesc::view_format`) — the
//! sampler hardware then does sRGB→linear on read. Mip filtering happens in gamma
//! space (the accepted industry-standard tradeoff for a transfer-blit mip chain). A
//! color-space-linear texture (normal, metallic-roughness, AO, ORM) stays UNORM in
//! both image and view. See [`ColorSpace::formats`].

use std::path::{Path, PathBuf};

use boyko_ecs::ecs::core::asset::assets::Assets;
use boyko_ecs::ecs::core::asset::handle::Handle;
use boyko_ecs::ecs::core::asset::{
    Asset, AssetBacking, AssetLoader, HasLoaders, LoaderEntry, register_asset_layout,
};
use boyko_ecs::ecs::identifiers::primitives::ComponentId;
use boyko_ecs::ecs::core::resources::resource::NonSendResource;
use boyko_log::codes::{OnceSite, W2206};
use boyko_rhi::enums::{BarrierAccess, BarrierStage, Format, ImageAspect, ImageLayout, ImageUsage, TextureDimension};
use boyko_rhi::{
    BufferDesc, BufferImageCopy, BufferUsage, ImageBarrierDesc, ImageBlitDesc,
    ImageSubresourceRange, MemoryLocation, RhiCommandEncoder, RhiDevice, RhiQueue, TextureDesc,
};
use boyko_rhi_vulkan::device::VulkanContext;
use boyko_rhi_vulkan::error::VulkanError;
use boyko_rhi_vulkan::texture::VulkanTexture;

use crate::bindless::BindlessTextureTable;
use crate::loaders::PngTextureLoader;
use crate::material::MaterialTextures;
use crate::texture_data::TextureData;

/// The material-slot color space a decoded texture's samples are encoded in
/// (textured-PBR T2 Decision D2). Decides the GPU image/view format pair — see
/// [`Self::formats`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ColorSpace {
    /// sRGB-encoded samples (albedo, emissive): the sampler decodes sRGB→linear in
    /// hardware on every read. The common default for a color texture.
    #[default]
    Srgb,
    /// Linear-encoded samples (normal maps, metallic-roughness, AO, ORM masks): no
    /// hardware decode — the raw byte value IS the linear sample.
    Linear,
}

impl ColorSpace {
    /// Maps to the `(image format, view format)` pair [`upload_texture_2d`] /
    /// [`TextureDesc`] need. [`Self::Srgb`] returns
    /// `(R8G8B8A8Unorm, Some(R8G8B8A8Srgb))` (the mutable-view trick); [`Self::Linear`]
    /// returns `(R8G8B8A8Unorm, None)` (image and view share one format).
    #[inline]
    pub const fn formats(self) -> (Format, Option<Format>) {
        match self {
            ColorSpace::Srgb => (Format::R8G8B8A8Unorm, Some(Format::R8G8B8A8Srgb)),
            ColorSpace::Linear => (Format::R8G8B8A8Unorm, None),
        }
    }
}

/// The full mip-chain level count for a `width`x`height` texture:
/// `floor(log2(max(width, height))) + 1`. E.g. `mip_levels_for(8, 8) == 4`
/// (8 → 4 → 2 → 1), `mip_levels_for(1, 1) == 1`.
///
/// # Panics (debug)
/// `width`/`height` must both be `> 0` (a `debug_assert!`; `leading_zeros` on `0`
/// would otherwise make this return `0`, an invalid mip count).
#[inline]
pub const fn mip_levels_for(width: u32, height: u32) -> u32 {
    debug_assert!(width > 0 && height > 0, "invariant: texture extent must be non-zero");
    let max_dim = if width > height { width } else { height };
    // `floor(log2(max_dim)) + 1`, valid for `max_dim >= 1` (checked above).
    32 - max_dim.leading_zeros()
}

/// Builds a `width`x`height` `mip_levels`-level texture (`format` image,
/// `view_format` decoupled SAMPLED view — [`ColorSpace::formats`]), stages
/// `rgba8` (tightly-packed level-0 RGBA8) into mip 0, and — when `mip_levels > 1`
/// — generates the remaining levels via a LINEAR-filtered blit chain on the
/// UNORM image (T2 Decision D3), finishing every level in
/// `ShaderReadOnlyOptimal`. Generalizes
/// [`upload_solid_pixels`](crate::bindless)'s single-mip 2-barrier staged upload
/// (kept untouched, byte-identical, for [`create_solid_color_texture`](crate::bindless::create_solid_color_texture))
/// with an interleaved barrier/blit/barrier chain when `mip_levels > 1`.
///
/// On any partial failure every object created so far is torn down before the
/// error returns (no leak) — mirrors [`create_solid_color_texture`](crate::bindless::create_solid_color_texture).
pub fn upload_texture_2d(
    ctx: &VulkanContext,
    width: u32,
    height: u32,
    rgba8: &[u8],
    format: Format,
    view_format: Option<Format>,
    mip_levels: u32,
) -> Result<VulkanTexture, VulkanError> {
    debug_assert!(width > 0 && height > 0, "invariant: texture extent is non-zero");
    debug_assert!(mip_levels >= 1, "invariant: mip_levels must be >= 1");
    debug_assert_eq!(
        rgba8.len(),
        (width as usize) * (height as usize) * 4,
        "invariant: rgba8 must be exactly width * height * 4 bytes"
    );

    // A blit needs the source mip in TRANSFER_SRC — only required when a mip chain
    // is actually generated (`mip_levels > 1`); the single-mip path stays exactly
    // `SAMPLED | TRANSFER_DST`, matching every pre-T2 texture's usage.
    let usage = if mip_levels > 1 {
        ImageUsage::SAMPLED | ImageUsage::TRANSFER_DST | ImageUsage::TRANSFER_SRC
    } else {
        ImageUsage::SAMPLED | ImageUsage::TRANSFER_DST
    };

    let texture = ctx.create_texture(&TextureDesc {
        width,
        height,
        depth: 1,
        format,
        dimension: TextureDimension::D2,
        usage,
        array_layers: 1,
        mip_levels,
        view_format,
    })?;

    if let Err(e) = upload_mipped_pixels(ctx, &texture, width, height, rgba8, mip_levels) {
        // SAFETY: `texture` was just created on `ctx`, owned exclusively here, and
        // the upload's own submit (if any ran) is fence-waited internally before
        // this error could surface; destroy it once on this edge.
        unsafe { ctx.destroy_texture(texture) };
        return Err(e);
    }
    Ok(texture)
}

/// The staged upload + mip-chain-blit submit for [`upload_texture_2d`] (T2 Decision
/// D3, steps 1-5): stage level-0 pixels → barrier all mips UNDEFINED→TRANSFER_DST →
/// copy level 0 → (per mip `i` in `1..mip_levels`: barrier mip `i-1` TRANSFER_DST→
/// TRANSFER_SRC, LINEAR blit `i-1`→`i`, barrier mip `i-1`→SHADER_READ_ONLY) → barrier
/// the last mip TRANSFER_DST→SHADER_READ_ONLY → one fenced submit + wait.
fn upload_mipped_pixels(
    ctx: &VulkanContext,
    texture: &VulkanTexture,
    width: u32,
    height: u32,
    rgba8: &[u8],
    mip_levels: u32,
) -> Result<(), VulkanError> {
    let size = rgba8.len() as u64;
    let staging = ctx.create_buffer(&BufferDesc {
        size,
        usage: BufferUsage::TRANSFER_SRC,
        location: MemoryLocation::HostVisibleCoherent,
    })?;
    let Some(dst) = ctx.buffer_mapped_ptr(&staging) else {
        // SAFETY: `staging` was just created, never submitted; destroy it once on
        // this edge.
        unsafe { ctx.destroy_buffer(staging) };
        return Err(VulkanError::Unsupported("staging buffer not host-mapped"));
    };
    // SAFETY: `dst` is the persistently-mapped first byte of the host-coherent
    // staging buffer (exactly `size` bytes, just created); `rgba8` is a distinct,
    // non-overlapping allocation of `size` bytes; this is the unique writer before
    // any submission binds the buffer. Host-coherent ⇒ no flush.
    unsafe {
        core::ptr::copy_nonoverlapping(rgba8.as_ptr(), dst.as_ptr(), rgba8.len());
    }

    let mut encoder = match ctx.create_command_encoder() {
        Ok(e) => e,
        Err(e) => {
            // SAFETY: `staging` was just created, never submitted; destroy once.
            unsafe { ctx.destroy_buffer(staging) };
            return Err(e);
        }
    };
    let fence = match ctx.create_fence(false) {
        Ok(f) => f,
        Err(e) => {
            // SAFETY: `encoder`/`staging` were just created, never submitted;
            // destroy each once.
            unsafe {
                ctx.destroy_command_encoder(encoder);
                ctx.destroy_buffer(staging);
            }
            return Err(e);
        }
    };

    let level0_region = [BufferImageCopy {
        buffer_offset: 0,
        buffer_row_length: 0,
        buffer_image_height: 0,
        aspect: ImageAspect::COLOR,
        mip_level: 0,
        base_array_layer: 0,
        layer_count: 1,
        image_offset_x: 0,
        image_offset_y: 0,
        image_offset_z: 0,
        image_extent_w: width,
        image_extent_h: height,
        image_extent_d: 1,
    }];

    let mip_range = |base_mip_level: u32| ImageSubresourceRange {
        aspect: ImageAspect::COLOR,
        base_mip_level,
        level_count: 1,
        base_array_layer: 0,
        layer_count: 1,
    };

    let record = (|| -> Result<(), VulkanError> {
        encoder.begin()?;

        // Step 2: every mip UNDEFINED → TRANSFER_DST_OPTIMAL, then copy level 0.
        encoder.image_barrier(&ImageBarrierDesc {
            texture,
            src_stage: BarrierStage::TOP_OF_PIPE,
            dst_stage: BarrierStage::TRANSFER,
            src_access: BarrierAccess::NONE,
            dst_access: BarrierAccess::TRANSFER_WRITE,
            old_layout: ImageLayout::Undefined,
            new_layout: ImageLayout::TransferDstOptimal,
            range: ImageSubresourceRange {
                aspect: ImageAspect::COLOR,
                base_mip_level: 0,
                level_count: mip_levels,
                base_array_layer: 0,
                layer_count: 1,
            },
        });
        encoder.copy_buffer_to_image(
            &staging,
            texture,
            ImageLayout::TransferDstOptimal,
            &level0_region,
        );

        // Step 3: the mip chain — each level blit-downsampled from the previous.
        for level in 1..mip_levels {
            let src_w = (width >> (level - 1)).max(1);
            let src_h = (height >> (level - 1)).max(1);
            let dst_w = (width >> level).max(1);
            let dst_h = (height >> level).max(1);

            // Source mip TRANSFER_DST → TRANSFER_SRC (it was just written: either the
            // staged copy for level 1's source == mip 0, or the previous iteration's blit).
            encoder.image_barrier(&ImageBarrierDesc {
                texture,
                src_stage: BarrierStage::TRANSFER,
                dst_stage: BarrierStage::TRANSFER,
                src_access: BarrierAccess::TRANSFER_WRITE,
                dst_access: BarrierAccess::TRANSFER_READ,
                old_layout: ImageLayout::TransferDstOptimal,
                new_layout: ImageLayout::TransferSrcOptimal,
                range: mip_range(level - 1),
            });

            encoder.blit_image(&ImageBlitDesc {
                texture,
                aspect: ImageAspect::COLOR,
                src_mip_level: level - 1,
                src_extent_w: src_w,
                src_extent_h: src_h,
                src_layout: ImageLayout::TransferSrcOptimal,
                dst_mip_level: level,
                dst_extent_w: dst_w,
                dst_extent_h: dst_h,
                dst_layout: ImageLayout::TransferDstOptimal,
            });

            // The source mip is now done being read — TRANSFER_SRC → SHADER_READ_ONLY
            // (sample-ready; this level will never be written again).
            encoder.image_barrier(&ImageBarrierDesc {
                texture,
                src_stage: BarrierStage::TRANSFER,
                dst_stage: BarrierStage::FRAGMENT_SHADER,
                src_access: BarrierAccess::TRANSFER_READ,
                dst_access: BarrierAccess::SHADER_READ,
                old_layout: ImageLayout::TransferSrcOptimal,
                new_layout: ImageLayout::ShaderReadOnlyOptimal,
                range: mip_range(level - 1),
            });
        }

        // Step 4: the LAST mip (still TRANSFER_DST — either the level-0 copy when
        // `mip_levels == 1`, or the final blit's destination) → SHADER_READ_ONLY.
        encoder.image_barrier(&ImageBarrierDesc {
            texture,
            src_stage: BarrierStage::TRANSFER,
            dst_stage: BarrierStage::FRAGMENT_SHADER,
            src_access: BarrierAccess::TRANSFER_WRITE,
            dst_access: BarrierAccess::SHADER_READ,
            old_layout: ImageLayout::TransferDstOptimal,
            new_layout: ImageLayout::ShaderReadOnlyOptimal,
            range: mip_range(mip_levels - 1),
        });

        encoder.end()?;
        let queue = ctx.rhi_queue();
        queue.submit(&encoder, &fence)?;
        ctx.wait_fence(&fence, u64::MAX)?;
        Ok(())
    })();

    // Tear down the setup-class transients. The submit (if it ran) is
    // fence-waited above.
    // SAFETY: `encoder`/`fence`/`staging` were created on `ctx`; the encoder's
    // only submission (if any) completed (fence-waited above on the Ok path, or
    // never submitted on an error path), and each is moved by value ⇒ destroyed
    // once.
    unsafe {
        ctx.destroy_command_encoder(encoder);
        ctx.destroy_fence(fence);
        ctx.destroy_buffer(staging);
    }
    record
}

/// Format-generic, single-mip staged upload (AA campaign Stage 2 — the SMAA LUT sibling of
/// [`upload_texture_2d`], which hardcodes RGBA8 4B/px + a mip-blit chain and cannot ingest the
/// SMAA `AreaTex`/`SearchTex` LUTs' `R8G8`/`R8` formats). Builds a `w`x`h` `SAMPLED |
/// TRANSFER_DST` texture at `format`, stages `bytes` into mip 0 via a single fenced
/// staged-upload submit (forks [`crate::bindless::create_solid_color_texture`]'s
/// `upload_solid_pixels` shape, generalized to an arbitrary format + caller-supplied byte
/// buffer instead of a repeated solid fill), and finishes `ShaderReadOnlyOptimal` — the
/// texture is sample-ready before this call returns (no per-frame LUT barrier is ever
/// needed).
///
/// `bytes_per_pixel` is derived from `format`: `R8Unorm` → 1, `R8G8Unorm` → 2,
/// `R8G8B8A8Unorm` → 4. Any other format is `debug_assert`-unreachable (this seam is used
/// ONLY by the boot-time LUT uploads today) and returns [`VulkanError::Unsupported`] in
/// release, rather than silently misreading `bytes`' length.
///
/// On any partial failure every object created so far is torn down before the error returns
/// (no leak) — mirrors [`upload_texture_2d`] / [`create_solid_color_texture`](crate::bindless::create_solid_color_texture).
///
/// # Panics (debug)
/// `debug_assert!`s that `bytes.len() == w * h * bytes_per_pixel(format)` and that `w`/`h`
/// are non-zero.
pub fn upload_texture_2d_raw(
    ctx: &VulkanContext,
    w: u32,
    h: u32,
    bytes: &[u8],
    format: Format,
) -> Result<VulkanTexture, VulkanError> {
    debug_assert!(w > 0 && h > 0, "invariant: texture extent is non-zero");
    let bpp = match format {
        Format::R8Unorm => 1u64,
        Format::R8G8Unorm => 2,
        Format::R8G8B8A8Unorm => 4,
        // SAFETY-adjacent invariant (not `unsafe`): this seam is used only for the boot-time
        // LUT uploads today, all of which are one of the three formats above.
        _ => return Err(VulkanError::Unsupported("upload_texture_2d_raw: unhandled format")),
    };
    debug_assert_eq!(
        bytes.len() as u64,
        (w as u64) * (h as u64) * bpp,
        "invariant: bytes must be exactly w * h * bytes_per_pixel(format)"
    );

    let texture = ctx.create_texture(&TextureDesc {
        width: w,
        height: h,
        depth: 1,
        format,
        dimension: TextureDimension::D2,
        usage: ImageUsage::SAMPLED | ImageUsage::TRANSFER_DST,
        array_layers: 1,
        mip_levels: 1,
        view_format: None,
    })?;

    if let Err(e) = upload_raw_pixels(ctx, &texture, w, h, bytes) {
        // SAFETY: `texture` was just created on `ctx`, owned exclusively here, and the
        // upload's own submit (if any ran) is fence-waited internally before this error
        // could surface; destroy it once on this edge.
        unsafe { ctx.destroy_texture(texture) };
        return Err(e);
    }
    Ok(texture)
}

/// The staged upload + layout-transition submit for [`upload_texture_2d_raw`] — mirrors
/// [`crate::bindless`]'s `upload_solid_pixels` exactly (staging buffer →
/// `copy_buffer_to_image` → UNDEFINED→TRANSFER_DST→SHADER_READ_ONLY barriers → one fenced
/// submit), generalized to a caller-supplied (not repeated-fill) byte buffer.
fn upload_raw_pixels(
    ctx: &VulkanContext,
    texture: &VulkanTexture,
    w: u32,
    h: u32,
    bytes: &[u8],
) -> Result<(), VulkanError> {
    let size = bytes.len() as u64;
    let staging = ctx.create_buffer(&BufferDesc {
        size,
        usage: BufferUsage::TRANSFER_SRC,
        location: MemoryLocation::HostVisibleCoherent,
    })?;
    let Some(dst) = ctx.buffer_mapped_ptr(&staging) else {
        // SAFETY: `staging` was just created, never submitted; destroy it once on this edge.
        unsafe { ctx.destroy_buffer(staging) };
        return Err(VulkanError::Unsupported("staging buffer not host-mapped"));
    };
    // SAFETY: `dst` is the persistently-mapped first byte of the host-coherent staging
    // buffer (exactly `size` bytes, just created); `bytes` is a distinct, non-overlapping
    // allocation of `size` bytes; this is the unique writer before any submission binds the
    // buffer. Host-coherent ⇒ no flush.
    unsafe {
        core::ptr::copy_nonoverlapping(bytes.as_ptr(), dst.as_ptr(), bytes.len());
    }

    let mut encoder = match ctx.create_command_encoder() {
        Ok(e) => e,
        Err(e) => {
            // SAFETY: `staging` was just created, never submitted; destroy once.
            unsafe { ctx.destroy_buffer(staging) };
            return Err(e);
        }
    };
    let fence = match ctx.create_fence(false) {
        Ok(f) => f,
        Err(e) => {
            // SAFETY: `encoder`/`staging` were just created, never submitted; destroy each
            // once.
            unsafe {
                ctx.destroy_command_encoder(encoder);
                ctx.destroy_buffer(staging);
            }
            return Err(e);
        }
    };

    let region = [BufferImageCopy {
        buffer_offset: 0,
        buffer_row_length: 0,
        buffer_image_height: 0,
        aspect: ImageAspect::COLOR,
        mip_level: 0,
        base_array_layer: 0,
        layer_count: 1,
        image_offset_x: 0,
        image_offset_y: 0,
        image_offset_z: 0,
        image_extent_w: w,
        image_extent_h: h,
        image_extent_d: 1,
    }];

    let record = (|| -> Result<(), VulkanError> {
        encoder.begin()?;
        // UNDEFINED → TRANSFER_DST_OPTIMAL (the copy destination).
        encoder.image_barrier(&ImageBarrierDesc {
            texture,
            src_stage: BarrierStage::TOP_OF_PIPE,
            dst_stage: BarrierStage::TRANSFER,
            src_access: BarrierAccess::NONE,
            dst_access: BarrierAccess::TRANSFER_WRITE,
            old_layout: ImageLayout::Undefined,
            new_layout: ImageLayout::TransferDstOptimal,
            range: ImageSubresourceRange::COLOR,
        });
        encoder.copy_buffer_to_image(&staging, texture, ImageLayout::TransferDstOptimal, &region);
        // TRANSFER_DST_OPTIMAL → SHADER_READ_ONLY_OPTIMAL (sample-ready).
        encoder.image_barrier(&ImageBarrierDesc {
            texture,
            src_stage: BarrierStage::TRANSFER,
            dst_stage: BarrierStage::FRAGMENT_SHADER,
            src_access: BarrierAccess::TRANSFER_WRITE,
            dst_access: BarrierAccess::SHADER_READ,
            old_layout: ImageLayout::TransferDstOptimal,
            new_layout: ImageLayout::ShaderReadOnlyOptimal,
            range: ImageSubresourceRange::COLOR,
        });
        encoder.end()?;
        let queue = ctx.rhi_queue();
        queue.submit(&encoder, &fence)?;
        ctx.wait_fence(&fence, u64::MAX)?;
        Ok(())
    })();

    // Tear down the setup-class transients. The submit (if it ran) is fence-waited above.
    // SAFETY: `encoder`/`fence`/`staging` were created on `ctx`; the encoder's only
    // submission (if any) completed (fence-waited above on the Ok path, or never submitted
    // on an error path), and each is moved by value ⇒ destroyed once.
    unsafe {
        ctx.destroy_command_encoder(encoder);
        ctx.destroy_fence(fence);
        ctx.destroy_buffer(staging);
    }
    record
}

/// One GPU-resident, mip-chained, bindless-registered texture asset: the OWNED
/// [`VulkanTexture`] plus the bindless slot it was registered into and the draw-time
/// metadata a future sampling shader needs (`width`, `height`, `mip_levels`).
///
/// `TextureGpu` does NOT implement `Drop`: an RHI [`VulkanTexture`] must be
/// destroyed through the owning [`VulkanContext`] (`destroy_texture`) AFTER the
/// device is idle, which a blind `Drop` cannot guarantee — see [`TextureAssetsExt::destroy`].
pub struct TextureGpu {
    /// The owned device-local image + view(s) (see [`upload_texture_2d`]).
    pub texture: VulkanTexture,
    /// This texture's slot in the world's [`BindlessTextureTable`] (`>= 1`; slot `0`
    /// is the reserved magenta error texture — see
    /// [`BindlessTextureTable::register`](crate::bindless::BindlessTextureTable::register)).
    pub bindless_slot: u32,
    /// Width in texels (mip 0).
    pub width: u32,
    /// Height in texels (mip 0).
    pub height: u32,
    /// The number of mip levels the texture was built with (`>= 1`).
    pub mip_levels: u32,
}

impl Asset for TextureGpu {
    // `TextureGpu` owns a non-`Send` RHI texture, so it cannot satisfy `Asset::Cpu:
    // Send` itself (mirrors `MeshGpu`'s own `Asset::Cpu = MeshData` reasoning).
    // `TextureData` is the `Send`-safe decoded intermediate `PngTextureLoader` produces.
    type Cpu = TextureData;
}

impl TextureGpu {
    /// The [`AssetBacking::register_layout`] drop glue for `TextureGpu` (mirrors
    /// [`MeshGpu::drop_glue`](crate::mesh::MeshGpu)). Device-inert by design: device
    /// teardown is manual, gated on the caller's idle contract, via
    /// [`TextureAssetsExt::destroy`] / [`OrphanedTextureGpu::drain_ready`] — never
    /// from a destructor. This glue only lets Rust's ordinary field-drop glue run
    /// (`VulkanTexture`/integers all have trivial drop), freeing NO device memory.
    ///
    /// # Safety
    /// The caller (`ComponentPool::drop_at` / the terminal `Drop for Assets<TextureGpu>`)
    /// guarantees `ptr` points at a valid, aligned, fully-initialized `TextureGpu`,
    /// exclusively owned, not accessed again after this call — the standard `DropFn`
    /// contract (`boyko_ecs`'s `component_registry::DropFn`).
    unsafe fn drop_glue(ptr: *mut u8) {
        // SAFETY: see this function's own doc — the caller upholds the `DropFn`
        // contract. `drop_in_place` runs `TextureGpu`'s (trivial, field-wise) drop
        // glue exactly once; no device call is made here (see the doc above).
        unsafe { core::ptr::drop_in_place(ptr.cast::<TextureGpu>()) }
    }
}

impl AssetBacking for TextureGpu {
    // Resident asset record: teardown is manual (device-idle-gated), never a bare
    // `Drop` — see `drop_glue`'s doc.
    const NEEDS_TEARDOWN: bool = true;

    fn register_layout() -> ComponentId {
        register_asset_layout::<TextureGpu>(Some(TextureGpu::drop_glue))
    }
}

impl HasLoaders for TextureGpu {
    /// One entry: the in-house PNG loader.
    const LOADERS: &'static [LoaderEntry<Self>] = &[LoaderEntry::of::<PngTextureLoader>()];
}

/// The device work behind [`TextureAssetsExt::register_texture`]: uploads a
/// mip-chained texture per `data` ([`ColorSpace::formats`] picks the image/view
/// format, [`mip_levels_for`] picks the mip count), registers it into `aux`'s
/// bindless table, and returns the assembled [`TextureGpu`] (NOT yet inserted into
/// any [`Assets<TextureGpu>`] table — the caller mints the row).
///
/// Factored out of [`TextureAssetsExt::register_texture`] (mirrors
/// [`build_mesh_gpu`](crate::mesh_assets::build_mesh_gpu)) so a loaded texture's
/// GPU-upload pass ([`GpuUpload`](crate::gpu_upload::GpuUpload) for [`TextureGpu`])
/// runs through the EXACT SAME device path a host-authored `register_texture` call
/// uses.
///
/// # Panics
/// Panics (`expect`) if the texture upload fails — a device out-of-memory at
/// asset-registration time is a setup failure, not a recoverable per-frame error
/// (mirrors [`build_mesh_gpu`](crate::mesh_assets::build_mesh_gpu)'s contract).
pub fn build_texture_gpu(
    ctx: &VulkanContext,
    aux: &mut BindlessTextureTable,
    data: &TextureData,
) -> TextureGpu {
    let (format, view_format) = data.color_space.formats();
    let mip_levels = mip_levels_for(data.width, data.height);
    let texture = upload_texture_2d(ctx, data.width, data.height, &data.rgba8, format, view_format, mip_levels)
        .expect("invariant: texture upload (setup stage)");
    let bindless_slot = aux.register(ctx, texture.view());
    TextureGpu {
        texture,
        bindless_slot,
        width: data.width,
        height: data.height,
        mip_levels,
    }
}

/// The texture-domain API over the world's [`Assets<TextureGpu>`] table
/// (textured-PBR T2), mirroring [`MeshAssetsExt`](crate::mesh_assets::MeshAssetsExt).
///
/// Unlike [`MeshHandle`](boyko_scene::render_caps::MeshHandle) (a bespoke dense
/// `u32` render carrier), texture resolution uses [`Handle<TextureGpu>`] directly —
/// no per-entity render-cap component references a texture yet (T5/T6), so there is
/// no existing dense-carrier consumer to mirror `MeshHandle`'s truncation shape for.
pub trait TextureAssetsExt {
    /// Uploads `data` into a fresh, mip-chained, bindless-registered GPU texture and
    /// returns its handle.
    ///
    /// # Bindless-slot exhaustion
    /// If `aux`'s bindless table is exhausted (every real slot in use or awaiting its
    /// fence horizon — practically unreachable at
    /// [`BINDLESS_TEXTURE_CAPACITY`](boyko_rhi_vulkan::bindless::BINDLESS_TEXTURE_CAPACITY)),
    /// [`BindlessTextureTable::register`] `debug_assert!`s (a dev-build invariant
    /// violation) and, in release, `eprintln!`s a warning and silently aliases the
    /// reserved slot 0 (the magenta error texture) instead of an out-of-range write —
    /// the returned [`TextureGpu`] resolves through that slot, so the material renders
    /// visibly wrong (magenta) rather than corrupting memory.
    ///
    /// # Panics
    /// Same contract as [`build_texture_gpu`]: a device out-of-memory at
    /// asset-registration time is a setup failure.
    fn register_texture(
        &mut self,
        ctx: &VulkanContext,
        aux: &mut BindlessTextureTable,
        data: &TextureData,
    ) -> Handle<TextureGpu>;

    /// Resolves a [`Handle<TextureGpu>`] to its GPU asset, or `None` if the handle is
    /// stale / out of range / never registered.
    fn try_get(&self, h: Handle<TextureGpu>) -> Option<&TextureGpu>;

    /// Resolves a [`Handle<TextureGpu>`] to its GPU asset.
    ///
    /// # Panics
    /// Panics if `h` does not resolve — a handle no live row resolves to is a
    /// caller/asset-binding bug, not a recoverable error.
    fn texture(&self, h: Handle<TextureGpu>) -> &TextureGpu;

    /// Destroys every registered texture's RHI image through `ctx` and its bindless
    /// slot through `aux`, then empties the table.
    ///
    /// # Safety
    /// The caller MUST have made the device idle (e.g. via the renderer's `Drop` /
    /// `wait_idle`) so no in-flight submit still references any texture or the
    /// bindless set; each is destroyed/unregistered exactly once. Mirrors
    /// [`MeshAssetsExt::destroy`](crate::mesh_assets::MeshAssetsExt::destroy).
    unsafe fn destroy(&mut self, ctx: &VulkanContext, aux: &mut BindlessTextureTable);
}

impl TextureAssetsExt for Assets<TextureGpu> {
    fn register_texture(
        &mut self,
        ctx: &VulkanContext,
        aux: &mut BindlessTextureTable,
        data: &TextureData,
    ) -> Handle<TextureGpu> {
        let gpu = build_texture_gpu(ctx, aux, data);
        self.add(gpu)
    }

    #[inline]
    fn try_get(&self, h: Handle<TextureGpu>) -> Option<&TextureGpu> {
        self.get(h)
    }

    #[inline]
    fn texture(&self, h: Handle<TextureGpu>) -> &TextureGpu {
        self.try_get(h)
            .expect("invariant: Handle<TextureGpu> resolves to a registered texture")
    }

    unsafe fn destroy(&mut self, ctx: &VulkanContext, aux: &mut BindlessTextureTable) {
        // `Assets<T>` exposes no owned/mutable whole-table iteration (only the
        // borrowed `iter()` and the handle-keyed `remove()`), so every live handle is
        // collected FIRST (a small, one-shot teardown allocation — never on the
        // gameplay hot path, Principle 5's actual scope) and then removed by value,
        // one texture at a time (mirrors `MeshAssetsExt::destroy`).
        let handles: Vec<Handle<TextureGpu>> = self.iter().map(|(h, _)| h).collect();
        for h in handles {
            let record = self
                .remove(h)
                .expect("invariant: a handle collected from iter() resolves via remove()");
            // The device is idle (caller contract), so the slot's fence horizon is
            // moot — return it to the free list immediately (epoch 0) rather than
            // stage it, mirroring a hard/full-teardown recycle.
            aux.unregister(record.bindless_slot, 0);
            // SAFETY: `record.texture` was created by `build_texture_gpu` on this
            // same `ctx`; the device is idle (caller contract), so no submit
            // references it; the by-value move destroys it exactly once.
            unsafe { ctx.destroy_texture(record.texture) };
        }
    }
}

/// One [`MaterialTextures`] slot's texture-folder convention: the candidate filenames
/// (tried in order — later entries are filename aliases) and the [`ColorSpace`] the
/// decoded samples are encoded in (textured-PBR T7's documented folder convention).
#[derive(Debug, Clone, Copy)]
struct FolderSlotSpec {
    /// Candidate filenames, most-preferred first.
    candidates: &'static [&'static str],
    /// The color space this slot's samples are encoded in.
    color_space: ColorSpace,
    /// A short label for diagnostics (`eprintln!`/`println!` notes).
    label: &'static str,
}

const FOLDER_SLOT_ALBEDO: FolderSlotSpec = FolderSlotSpec {
    candidates: &["albedo.png", "base_color.png"],
    color_space: ColorSpace::Srgb,
    label: "albedo",
};
const FOLDER_SLOT_NORMAL: FolderSlotSpec = FolderSlotSpec {
    candidates: &["normal.png"],
    color_space: ColorSpace::Linear,
    label: "normal",
};
const FOLDER_SLOT_METAL_ROUGH: FolderSlotSpec = FolderSlotSpec {
    candidates: &["metallic_roughness.png", "mr.png"],
    color_space: ColorSpace::Linear,
    label: "metallic_roughness",
};
const FOLDER_SLOT_AO: FolderSlotSpec = FolderSlotSpec {
    candidates: &["ao.png"],
    color_space: ColorSpace::Linear,
    label: "ao",
};
const FOLDER_SLOT_EMISSIVE: FolderSlotSpec = FolderSlotSpec {
    candidates: &["emissive.png"],
    color_space: ColorSpace::Srgb,
    label: "emissive",
};

/// A `Once` latch is PROCESS state, so it is a named module-level `static` rather than one
/// tucked inside the reporter: an observer must be able to reset it, or its green only means
/// "nothing else in this binary tripped this condition first". See `OnceSite::reset`.
pub(crate) static W2206_SITE: OnceSite = OnceSite::new();

/// Reports `boyko-W2206`: a material texture file that EXISTS and could not be decoded.
///
/// **This arm warns and the missing-file arm does not**, which is the whole distinction the two
/// carry. All five folder slots are documented as optional, so an absent map is the normal case
/// and gets an `info!`; a present-but-undecodable one means somebody put a file there intending it
/// to be used, and it silently is not.
///
/// `#[cold]` + `#[inline(never)]`, and a separate function rather than an inline block, for two
/// reasons: it keeps the decode success path free of the emission body, and it gives the observer
/// below something to call — a code whose only emitter is buried inside a function that needs a
/// live `VulkanContext` is a code no unit test can watch.
#[cold]
#[inline(never)]
fn report_material_texture_undecodable(label: &str, path: &Path, err: &impl core::fmt::Display) {
    if W2206_SITE.claim() {
        boyko_log::warn!(
            boyko_log::Render,
            W2206,
            "load_material_folder: {} at {} failed to decode ({}), using the material fallback",
            label,
            boyko_log::dsp!(path.display()),
            boyko_log::dsp!(err)
        );
    }
}

/// Tries each `<dir>/<candidate>` in `candidates`' order (later entries are filename
/// aliases), returning the first `(path, bytes)` pair `read` resolves successfully.
///
/// Pure: `read` is injected so unit tests can exercise the candidate-priority order
/// without touching a real filesystem; the real caller ([`load_material_folder`])
/// passes [`std::fs::read`].
fn resolve_candidate(
    dir: &Path,
    candidates: &[&str],
    mut read: impl FnMut(&Path) -> std::io::Result<Vec<u8>>,
) -> Option<(PathBuf, Vec<u8>)> {
    candidates.iter().find_map(|name| {
        let path = dir.join(name);
        read(&path).ok().map(|bytes| (path, bytes))
    })
}

/// Loads one [`MaterialTextures`] slot from `dir` per `spec`'s candidate/color-space
/// convention, decoding via [`PngTextureLoader::decode`] (the SAME device-upload path
/// a host-authored `.png` asset takes) and registering it into the bindless table.
///
/// Returns the resolved bindless slot, or `0` (the reserved fallback — the material's
/// scalar/vertex data covers this channel) with a one-line [`eprintln!`] note if no
/// candidate file exists, is unreadable, or fails to decode. NEVER panics: a folder
/// convention must render with whatever subset of maps is present.
fn load_slot(
    dir: &Path,
    spec: FolderSlotSpec,
    ctx: &VulkanContext,
    textures: &mut Assets<TextureGpu>,
    bindless: &mut BindlessTextureTable,
) -> u32 {
    let Some((path, bytes)) = resolve_candidate(dir, spec.candidates, |p| std::fs::read(p)) else {
        // `info!`, and NOT a coded `warn!`. Every one of the five folder slots is documented as
        // optional and a missing file is the normal case, so warning here would put a `Warn` in
        // the log of every material that ships four maps instead of five — noise that trains a
        // reader to ignore the level.
        //
        // KNOWN LIMIT, recorded rather than guessed at: this arm also covers an UNREADABLE file,
        // because `resolve_candidate` discards the `io::Error` with `.ok()`. A permissions fault
        // is therefore reported at the same level as an absent optional map. Splitting them means
        // returning the reason from `resolve_candidate` and re-blessing the three tests that pin
        // its `Option` signature; it is in `docs/OPEN-QUESTIONS.md` with that cost, not silently
        // folded into this rung.
        boyko_log::info!(
            boyko_log::Render,
            "load_material_folder: {} not found in {} (tried {}), using the material fallback",
            spec.label,
            boyko_log::dsp!(dir.display()),
            boyko_log::dsp!(format_args!("{:?}", spec.candidates))
        );
        return 0;
    };
    match PngTextureLoader::decode(&bytes) {
        Ok(mut data) => {
            data.color_space = spec.color_space;
            // NORMAL-MAP CONVENTION (owner-set 2026-07-16): this engine's CANONICAL
            // tangent-space normal convention is DIRECTX (green-down: +G = a slope facing
            // image-BOTTOM) -- the Unreal Engine convention. The engine NEVER re-signs a
            // normal map: not here, and not in the TEXTURED shaders (which read the map with
            // no negation). An `assets/materials/<pack>/pbr/normal.png` is REQUIRED to already
            // be DirectX-convention; OpenGL-convention downloads (`*-ogl` vendor files) are
            // converted ONCE, offline, at asset-prep time (`scripts/normal_ogl_to_dx.py`).
            // See that script + `gbuffer_mrt.fs.hlsl`'s GREEN-CHANNEL CONVENTION block.
            let handle = textures.register_texture(ctx, bindless, &data);
            let slot = textures.texture(handle).bindless_slot;
            // The one `println!` in this crate, and the only site in the whole L8a set that wrote
            // to STDOUT rather than stderr. It is a lifecycle fact with no condition behind it,
            // so by Decision 7 it carries no code.
            boyko_log::info!(
                boyko_log::Render,
                "load_material_folder: loaded {} <- {}",
                spec.label,
                boyko_log::dsp!(path.display())
            );
            slot
        }
        Err(e) => {
            report_material_texture_undecodable(spec.label, &path, &e);
            0
        }
    }
}

/// Loads the standard PBR texture-folder convention (textured-PBR rung T7) from `dir`,
/// uploading + bindless-registering whichever of the five slot files are present, and
/// returns the assembled [`MaterialTextures`] sidecar (pass it to
/// [`Material::with_textures`](crate::material::Material::with_textures)).
///
/// # Filenames (all optional — a missing file falls back gracefully, never panics)
///
/// | slot          | candidates (later = alias)          | color space                        |
/// |---------------|--------------------------------------|-------------------------------------|
/// | albedo        | `albedo.png`, `base_color.png`       | sRGB                                |
/// | normal        | `normal.png`                          | linear, tangent-space               |
/// | metal_rough   | `metallic_roughness.png`, `mr.png`   | linear, glTF ORM (G=rough, B=metal) |
/// | ao            | `ao.png`                              | linear, R=occlusion                 |
/// | emissive      | `emissive.png`                        | sRGB                                |
///
/// A missing, unreadable, or undecodable file for a given slot leaves that slot `0`
/// (the material's scalar/vertex-color fallback for that channel) and prints a
/// one-line [`eprintln!`] note — this fn never panics on a partial or empty folder.
/// Each file is decoded via [`PngTextureLoader::decode`] — the SAME device-upload
/// path a host-authored `.png` asset takes — with [`TextureData::color_space`]
/// overridden per-slot (the loader itself has no per-material-slot context).
pub fn load_material_folder(
    textures: &mut Assets<TextureGpu>,
    ctx: &VulkanContext,
    bindless: &mut BindlessTextureTable,
    dir: &Path,
) -> MaterialTextures {
    MaterialTextures {
        albedo: load_slot(dir, FOLDER_SLOT_ALBEDO, ctx, textures, bindless),
        normal: load_slot(dir, FOLDER_SLOT_NORMAL, ctx, textures, bindless),
        metal_rough: load_slot(dir, FOLDER_SLOT_METAL_ROUGH, ctx, textures, bindless),
        ao: load_slot(dir, FOLDER_SLOT_AO, ctx, textures, bindless),
        emissive: load_slot(dir, FOLDER_SLOT_EMISSIVE, ctx, textures, bindless),
    }
}

/// Fill-reject `TextureGpu` values awaiting the fence-gated device-free pass
/// (mirrors [`OrphanedMeshGpu`](crate::mesh_assets::OrphanedMeshGpu) — the F6
/// Decision-4 sibling for the texture asset table).
///
/// `Assets::fill`'s `Err((_, TextureGpu))` arm returns a value the store never took
/// ownership of (a stale/double-fill target) — it still holds a LIVE device image
/// (and a live bindless slot) with no `Drop` to free them. This dedicated `!Send`
/// [`NonSendResource`] is the only correct home — see
/// [`OrphanedMeshGpu`](crate::mesh_assets::OrphanedMeshGpu)'s doc for the full
/// argument (identical here, `TextureGpu` in place of `MeshGpu`).
#[derive(Default)]
pub struct OrphanedTextureGpu {
    orphans: Vec<(TextureGpu, u64)>,
}

impl NonSendResource for OrphanedTextureGpu {}

impl OrphanedTextureGpu {
    /// Queues a fill-rejected `TextureGpu` value for teardown once every submit
    /// that could reference it is fence-complete. `retire_frame` is the
    /// caller-computed gate (`RenderEpoch` at reject time `+ RETIRE_DELAY`) —
    /// strictly conservative (a value `fill` rejected was never submitted at all,
    /// mirrors [`OrphanedMeshGpu::push`](crate::mesh_assets::OrphanedMeshGpu::push)'s
    /// proof).
    #[inline]
    pub fn push(&mut self, texture: TextureGpu, retire_frame: u64) {
        self.orphans.push((texture, retire_frame));
    }

    /// `true` if no orphan is awaiting teardown — the O(1) golden early-out (no
    /// `fill` caller exists in-tree yet, so this is always `true` today).
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.orphans.is_empty()
    }

    /// Tears down (bindless slot unregister, then the RHI image) every orphan whose
    /// `retire_frame <= epoch`, retaining the rest in enqueue order. Called ONLY by
    /// the host's per-frame F6-style retire step AFTER `wait_frame_in_flight` for
    /// this `epoch` — the same per-resource fence precondition every other F6
    /// destroy call relies on (mirrors
    /// [`OrphanedMeshGpu::drain_ready`](crate::mesh_assets::OrphanedMeshGpu::drain_ready)).
    pub fn drain_ready(&mut self, epoch: u64, ctx: &VulkanContext, aux: &mut BindlessTextureTable) {
        let mut i = 0;
        while i < self.orphans.len() {
            if self.orphans[i].1 > epoch {
                i += 1;
                continue;
            }
            let (record, _) = self.orphans.remove(i);
            // Stage the slot at the SAME `epoch` gate this orphan itself just cleared
            // — the value was never submitted (F6 design proof C), so its bindless
            // write is also never read by any in-flight command buffer.
            aux.unregister(record.bindless_slot, epoch);
            // SAFETY: `record.texture` was created by the failed upload attempt on
            // this same `ctx`; the value was never submitted (see above), so no GPU
            // work references it; the by-value move destroys it exactly once.
            unsafe { ctx.destroy_texture(record.texture) };
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mip_levels_for_power_of_two_square() {
        assert_eq!(mip_levels_for(8, 8), 4, "8 -> 4 -> 2 -> 1 is 4 levels");
        assert_eq!(mip_levels_for(1024, 1024), 11);
        assert_eq!(mip_levels_for(1, 1), 1, "a 1x1 texture has exactly 1 level");
    }

    #[test]
    fn mip_levels_for_non_power_of_two_uses_the_larger_dimension() {
        // floor(log2(3)) + 1 = 2 (3 -> 1).
        assert_eq!(mip_levels_for(3, 1), 2);
        // The larger dimension drives the count regardless of which axis it is on.
        assert_eq!(mip_levels_for(1, 1024), mip_levels_for(1024, 1));
        assert_eq!(mip_levels_for(1, 1024), 11);
    }

    #[test]
    fn mip_levels_for_non_square_uses_max_dimension() {
        assert_eq!(mip_levels_for(512, 4), mip_levels_for(512, 512));
    }

    #[test]
    fn color_space_srgb_maps_to_unorm_image_with_srgb_view() {
        let (format, view_format) = ColorSpace::Srgb.formats();
        assert_eq!(format, Format::R8G8B8A8Unorm);
        assert_eq!(view_format, Some(Format::R8G8B8A8Srgb));
    }

    #[test]
    fn color_space_linear_maps_to_unorm_image_with_no_view_decouple() {
        let (format, view_format) = ColorSpace::Linear.formats();
        assert_eq!(format, Format::R8G8B8A8Unorm);
        assert_eq!(view_format, None);
    }

    #[test]
    fn color_space_default_is_srgb() {
        assert_eq!(ColorSpace::default(), ColorSpace::Srgb);
    }

    // ── `load_material_folder`'s pure parts (candidate resolution + color-space
    // assignment) — no filesystem, no GPU. `load_material_folder`/`load_slot`
    // themselves need a live `VulkanContext` + `BindlessTextureTable` and so are
    // exercised only by the GPU-facing eval scenes (`pbr_material_showcase.rs`,
    // `textured_smoke.rs`), mirroring `drain_ready`'s note below. ────────────────

    #[test]
    fn resolve_candidate_prefers_the_first_existing_candidate_in_order() {
        let dir = Path::new("/fixture");
        let found = resolve_candidate(dir, &["a.png", "b.png"], |p| {
            if p.ends_with("a.png") || p.ends_with("b.png") {
                Ok(vec![1, 2, 3])
            } else {
                Err(std::io::Error::from(std::io::ErrorKind::NotFound))
            }
        });
        let (path, bytes) = found.expect("both candidates resolve — the first must win");
        assert!(path.ends_with("a.png"), "the first candidate must be preferred: {path:?}");
        assert_eq!(bytes, vec![1, 2, 3]);
    }

    #[test]
    fn resolve_candidate_falls_back_to_a_later_alias_when_the_first_is_absent() {
        let dir = Path::new("/fixture");
        let found = resolve_candidate(dir, &["albedo.png", "base_color.png"], |p| {
            if p.ends_with("base_color.png") {
                Ok(vec![9])
            } else {
                Err(std::io::Error::from(std::io::ErrorKind::NotFound))
            }
        });
        let (path, bytes) = found.expect("the alias must resolve");
        assert!(path.ends_with("base_color.png"));
        assert_eq!(bytes, vec![9]);
    }

    #[test]
    fn resolve_candidate_returns_none_when_no_candidate_resolves() {
        let dir = Path::new("/fixture");
        let found =
            resolve_candidate(dir, &["a.png", "b.png"], |_| {
                Err(std::io::Error::from(std::io::ErrorKind::NotFound))
            });
        assert!(found.is_none());
    }

    #[test]
    fn folder_slot_specs_assign_srgb_to_albedo_and_emissive_and_linear_to_the_rest() {
        assert_eq!(FOLDER_SLOT_ALBEDO.color_space, ColorSpace::Srgb);
        assert_eq!(FOLDER_SLOT_EMISSIVE.color_space, ColorSpace::Srgb);
        assert_eq!(FOLDER_SLOT_NORMAL.color_space, ColorSpace::Linear);
        assert_eq!(FOLDER_SLOT_METAL_ROUGH.color_space, ColorSpace::Linear);
        assert_eq!(FOLDER_SLOT_AO.color_space, ColorSpace::Linear);
    }

    #[test]
    fn folder_slot_candidates_list_the_documented_aliases() {
        assert_eq!(FOLDER_SLOT_ALBEDO.candidates, &["albedo.png", "base_color.png"]);
        assert_eq!(FOLDER_SLOT_METAL_ROUGH.candidates, &["metallic_roughness.png", "mr.png"]);
        assert_eq!(FOLDER_SLOT_NORMAL.candidates, &["normal.png"]);
        assert_eq!(FOLDER_SLOT_AO.candidates, &["ao.png"]);
        assert_eq!(FOLDER_SLOT_EMISSIVE.candidates, &["emissive.png"]);
    }

    // `OrphanedTextureGpu::drain_ready` requires a live `VulkanContext` +
    // `BindlessTextureTable` (it calls `ctx.destroy_texture` / `aux.unregister` on a
    // real device-owned `VulkanTexture`, whose fields are `pub(crate)` to
    // `boyko_rhi_vulkan` and so cannot be fabricated here) — mirroring
    // `OrphanedMeshGpu`, which carries no unit test for the identical reason. The
    // `#[ignore]` GPU integration test (`tests/texture_upload_smoke.rs`) exercises
    // the real device path this module's device-facing functions run.
}

#[cfg(test)]
mod l8a_w2206 {
    use super::*;
    use boyko_log::probe::{watch, watched};

    use crate::log_probe::arm;

    #[test]
    fn w2206_warns_for_an_undecodable_file_and_the_absent_case_does_not() {
        // The distinction this rung drew, asserted rather than asserted-about: a file that EXISTS
        // and fails to decode is a `Warn` with a code, and it reports once. The absent-file arm
        // that sits three lines above the emitter in `load_slot` is an `info!` with no code,
        // because every slot in a material folder is documented as optional -- warning there
        // would put a `Warn` in the log of every material that ships four maps instead of five.
        arm();
        W2206_SITE.reset();

        watch(b'W', W2206.number());
        report_material_texture_undecodable("albedo", Path::new("/fixture/albedo.png"), &"bad CRC");
        assert_eq!(watched(), 1, "a present-but-undecodable file warns");

        watch(b'W', W2206.number());
        report_material_texture_undecodable("normal", Path::new("/fixture/normal.png"), &"bad CRC");
        assert_eq!(watched(), 0, "Once: the second undecodable file is silent");
    }
}
