// GUI P5a UI-rect fragment shader (`ui_rect.fs.hlsl`): a rounded-box SDF + AA +
// UNIFORM border + flag-gated in-shader clip, output PREMULTIPLIED (matches the
// engine's src=ONE premultiplied-alpha blend).
//
// GENERATED by `cargo run -p boyko_shaderdsl --features emit --bin emit_ui` (UI-ADVANCED S1).
// The `// === GENERATED <name> BEGIN/END ===` spans are MACHINE-EMITTED from
// `boyko_shaderdsl::ui`'s generic `C: Cf` leaves; a hand-edit fails
// `boyko_render/tests/ui_rect_edsl_sync.rs`, and the committed `.spv` is byte-gated by
// `boyko_render/tests/ui_rect_spv_sync.rs`. The `f32` Eval instantiation of the SAME
// leaves is the CPU oracle `boyko_shaderdsl/tests/ui_leaves.rs` pins.
//
// The record is re-read from the same StructuredBuffer<UiInstance> by the
// interpolated SV_InstanceID (the FRAGMENT-stage SSBO read proven by Rung 0.5).
// All math is in physical px (the VS forwards rect-centred local_px), so fwidth(d)
// is one device-pixel wide AA -- DPI-correct under the Decision-9 full-extent
// contract (the UI viewport spans the same pixels the ortho denominator uses).
//
// Compiled offline (hermetic build -- no SDK at `cargo build` time) with:
//   C:\VulkanSDK\1.4.350.0\Bin\dxc.exe -spirv -T ps_6_0 -E main \
//       -fspv-target-env=vulkan1.3 ui_rect.fs.hlsl -Fo ui_rect.fs.spv

// === GENERATED ui_instance_mirror BEGIN ===
// The std430 UiInstance record -- the byte-layout mirror of the Rust
// #[repr(C, align(16))] UiInstance (stride 80 B). The offsets below are emit_ui
// GENERATOR INPUTS, pinned to the host offset_of! constants by ui_rect_edsl_sync.
struct UiInstance {
    float2 min_px;        // @0
    float2 size_px;       // @8
    float4 clip;          // @16  (min.xy, max.xy; valid iff CLIP_PRESENT)
    float4 corner_radius; // @32  (tl, tr, br, bl) -- ALWAYS the radius (the alias is retired)
    float4 uv;            // @48  normalized (u0, v0, u1, v1) -- glyphs AND sprites
    uint   color;         // @64  premultiplied RGBA8
    uint   border_color;  // @68  premultiplied RGBA8
    float  border_width;  // @72  uniform, physical px
    uint   flags;         // @76  bit0 BORDER_ANY, bit1 CLIP_PRESENT, bit2 TEXT, bit3 TEXTURED,
                          //      bits 20..31 the bindless sprite slot
};
// === GENERATED ui_instance_mirror END ===

[[vk::binding(0, 0)]] StructuredBuffer<UiInstance> g_instances : register(t0);

// GUI P5b (Decision T4-G/T4-A): the MSDF glyph atlas (binding 1, a combined
// image+sampler, FRAGMENT-visible) + the per-atlas uniform (binding 2): the baked
// distance range in TEXELS and the atlas size in texels. The atlas is upload-once,
// all-FIF sample concurrently (SampledComposite); the UBO is written once at upload
// and is immutable (one atlas -> one constant pxRange/size). Both bindings are present
// for EVERY draw but only sampled in the FLAG_TEXT branch, so the rect path is free.
[[vk::binding(1, 0)]] Texture2D    g_atlas         : register(t1);
[[vk::binding(1, 0)]] SamplerState g_atlas_sampler : register(s1);
struct AtlasUniform {
    float px_range;     // = AtlasMeta.distance_range_texels (the screenPxRange divisor)
    float _pad0;
    float2 atlas_size;  // (atlas_w, atlas_h) in texels
};
[[vk::binding(2, 0)]] ConstantBuffer<AtlasUniform> g_atlas_ubo : register(b2);

// UI-ADVANCED S3 -- the SPRITE lane's two declarations (architecture D2 + S-D3 + S-D4).
//
// Set 1, binding 0 is the SHARED bindless texture array (`BindlessTextureTable`, capacity
// 4096) -- the SAME set the textured gbuffer / Forward / particle paths bind, declared here
// character-for-character as `particle_draw.fs.hlsl` declares it. The UI declares ONLY that
// binding of set 1: it samples through its OWN sampler below, never through the set's shared
// immutable sampler (trilinear + 16x anisotropic + REPEAT), which was chosen for tiled world
// material textures and would foreclose a pixel-art UI forever (S-D4).
[[vk::binding(0, 1)]] Texture2D g_sprites[] : register(t0, space1);

// The UI's OWN sprite sampler (set 0, binding 3): the filter mode is chosen once at
// `ui_setup` (`UiSamplerMode::{Smooth, Pixel}` -> LINEAR/ClampToEdge vs NEAREST/ClampToEdge),
// so NEAREST pixel art is expressible without touching the world-shared bindless set (which
// D3 refuses to let a UI concern mutate). The host binds a COMBINED_IMAGE_SAMPLER there and
// this stage reads only its SAMPLER half -- the same separate-image/separate-sampler shape
// binding 1 above already uses for the atlas, and the mechanism gate G3-0 measured.
[[vk::binding(3, 0)]] SamplerState g_ui_sampler : register(s3);

struct VsOut {
    float4 position  : SV_Position;
    float2 pos_px    : TEXCOORD0;
    float2 local_px  : TEXCOORD1;
    float2 local_uv  : TEXCOORD2;   // GUI P5b: the 0..1 quad corner (Decision T4-B)
    nointerpolation uint inst_index : INSTANCE;
};

// === GENERATED ui_flag_consts BEGIN ===
static const uint FLAG_BORDER_ANY   = 1u << 0;
static const uint FLAG_CLIP_PRESENT = 1u << 1;
static const uint FLAG_TEXT         = 1u << 2;
static const uint FLAG_TEXTURED     = 1u << 3;
// The bindless sprite slot rides flags bits 20..31 (12 bits, slots 0..4095).
static const uint UI_SLOT_SHIFT     = 20u;
static const uint UI_SLOT_MASK      = 0xFFFu;
// === GENERATED ui_flag_consts END ===

// === GENERATED ui_unpack_rgba8 BEGIN ===
// Unpack a premultiplied RGBA8 (byte0=R..byte3=A) to a float4 in [0,1]
// (`boyko_shaderdsl::ui::ui_unpack_rgba8_body`).
float4 ui_unpack_rgba8(uint c) {
    return float4((float)(c & 255u), (float)(c >> 8u & 255u), (float)(c >> 16u & 255u), (float)(c >> 24u & 255u)) * (1.0 / 255.0);
}
// === GENERATED ui_unpack_rgba8 END ===

// === GENERATED ui_sd_rounded_box BEGIN ===
// Quilez/Bevy per-corner rounded-box SDF (`boyko_shaderdsl::ui::ui_sd_rounded_box_body`).
// `p` is rect-centred; `half_size` is half the rect; `r` is (tl, tr, br, bl). Selects
// the corner radius by the quadrant of p.
float ui_sd_rounded_box(float2 p, float2 half_size, float4 r) {
    float2 rx = (p.x > 0.0) ? r.yz : r.xw;
    float rr = (p.y > 0.0) ? rx.y : rx.x;
    float2 q = abs(p) - half_size + rr;
    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - rr;
}
// === GENERATED ui_sd_rounded_box END ===

// === GENERATED ui_clip_coverage BEGIN ===
// Anti-aliased coverage of a finite clip AABB at physical-px `pos`
// (`boyko_shaderdsl::ui::ui_clip_coverage_body`). 1 inside, 0 outside, a ~1px AA band
// at the edges (so a clipped edge is as crisp as a rect edge). `clip` is
// (min.xy, max.xy), always finite when CLIP_PRESENT is set.
float ui_clip_coverage(float2 pos, float4 clip, float fw) {
    float2 inside_min = smoothstep(clip.xy - fw, clip.xy + fw, pos);
    float2 inside_max = smoothstep(clip.zw - fw, clip.zw + fw, pos);
    float2 cov = inside_min * (1.0 - inside_max);
    return cov.x * cov.y;
}
// === GENERATED ui_clip_coverage END ===

// === GENERATED ui_median3 BEGIN ===
// GUI P5b MSDF reconstruction (canonical Chlumsky; `boyko_shaderdsl::ui::ui_median3_body`).
// The per-channel median recovers the sharp signed distance; corners are preserved
// because the three channels disagree only across a true edge.
float ui_median3(float r, float g, float b) {
    return max(min(r, g), min(max(r, g), b));
}
// === GENERATED ui_median3 END ===

// === GENERATED ui_screen_px_range BEGIN ===
// Converts the baked TEXEL distance range into a SCREEN-px range at this fragment
// (`boyko_shaderdsl::ui::ui_screen_px_range_body`), so the AA band is ~1 device px
// regardless of glyph scale. `fwidth(uv) == 0` on a flat run gives `screenTexSz == Inf`;
// `max(..., 1.0)` floors it (the NaN/Inf guard).
float ui_screen_px_range(float2 uv) {
    float2 unit_range = g_atlas_ubo.px_range / g_atlas_ubo.atlas_size;
    float2 screen_tex_sz = 1.0 / fwidth(uv);
    return max(0.5 * dot(unit_range, screen_tex_sz), 1.0);
}
// === GENERATED ui_screen_px_range END ===

// === GENERATED ui_premultiplied_over BEGIN ===
// Premultiplied "over" (`boyko_shaderdsl::ui::ui_premultiplied_over_body`): composite
// the border ring (premultiplied color `bc`, area-weighted by `border_cov`) ON TOP of
// the fill restricted to the inner shape (`fill * inner_cov`). Where the ring is
// translucent (bc.a < 1) the fill shows through via the (1 - src_a) term -- a `lerp`
// of two premultiplied colors would mis-weight that fall-through.
//   result = src + dst * (1 - src_alpha)
float4 ui_premultiplied_over(float4 bc, float border_cov, float4 fill, float inner_cov) {
    float4 src = bc * border_cov;
    float4 dst = fill * inner_cov;
    return src + dst * (1.0 - src.a);
}
// === GENERATED ui_premultiplied_over END ===

float4 main(VsOut input) : SV_Target0 {
    UiInstance inst = g_instances[input.inst_index];     // SSBO read in the FRAGMENT stage

    // GUI P5b text branch (Decision T4-G): a uniform-per-instance branch (every
    // fragment of one glyph takes the same side), so the rect majority is unregressed.
    // The glyph's normalized atlas UV rect lives in the record's OWN `uv` field
    // (UI-ADVANCED S2 -- the corner_radius alias is retired).
    if ((inst.flags & FLAG_TEXT) != 0u) {
        float2 uv  = lerp(inst.uv.xy, inst.uv.zw, input.local_uv);
        float4 msd = g_atlas.Sample(g_atlas_sampler, uv);   // RGBA8 MTSDF (rgb = MSDF)
        float  sd  = ui_median3(msd.r, msd.g, msd.b);
        float  cov = clamp(ui_screen_px_range(uv) * (sd - 0.5) + 0.5, 0.0, 1.0);

        float4 result = ui_unpack_rgba8(inst.color) * cov;  // PREMULTIPLIED fg, weighted
        if ((inst.flags & FLAG_CLIP_PRESENT) != 0u) {
            float fw = max(fwidth(input.pos_px.x), 1e-5);   // a device-px AA clip band
            result *= ui_clip_coverage(input.pos_px, inst.clip, fw);
        }
        return result;                                      // PREMULTIPLIED (src=ONE)
    }

    // UI-ADVANCED S3 sprite branch (architecture D2 / D8e): a bindless-indexed textured
    // quad. Uniform-per-instance like the text branch above (every fragment of one sprite
    // takes the same side), so the rect majority is unregressed. The slot rides `flags`
    // bits UI_SLOT_SHIFT..+12 (S-D2).
    //
    // `NonUniformResourceIndex` is REQUIRED INSURANCE, not an observed necessity here. The
    // descriptor index is per INSTANCE, and dropping the qualifier was measured on an RTX
    // 3060 (S3, red mutation M3-b) over 256 dense 4x4 quads on 64 distinct slots: every
    // quad still sampled its own texture, because that rasterizer does not pack one warp
    // from two primitives, so the index is wave-uniform by construction -- the same fact
    // that made the plan's 10.1 divergence measurement come out flat. A non-uniform index
    // WITHOUT the qualifier is undefined behaviour by the Vulkan spec, and another driver
    // may pack warps differently, so it stays (risk SR3).
    if ((inst.flags & FLAG_TEXTURED) != 0u) {
        uint   slot = (inst.flags >> UI_SLOT_SHIFT) & UI_SLOT_MASK;
        float2 uv   = lerp(inst.uv.xy, inst.uv.zw, input.local_uv);
        float4 t    = g_sprites[NonUniformResourceIndex(slot)].Sample(g_ui_sampler, uv);

        // The sprite source is STRAIGHT RGBA8; premultiply it, then MODULATE by the
        // already-premultiplied tint. Component-wise multiply of two premultiplied colors
        // is the correct tint here: (src.rgb*src.a) * (c.rgb*c.a) == (src.rgb*c.rgb) *
        // (src.a*c.a), which is the premultiplied form of the straight-space product.
        float4 result = float4(t.rgb * t.a, t.a) * ui_unpack_rgba8(inst.color);
        if ((inst.flags & FLAG_CLIP_PRESENT) != 0u) {
            float fw = max(fwidth(input.pos_px.x), 1e-5);   // a device-px AA clip band
            result *= ui_clip_coverage(input.pos_px, inst.clip, fw);
        }
        return result;                                      // PREMULTIPLIED (src=ONE)
    }

    float2 half_size = 0.5 * inst.size_px;

    float d  = ui_sd_rounded_box(input.local_px, half_size, inst.corner_radius);
    float fw = max(fwidth(d), 1e-5);                      // resolution-independent AA
    float fill_cov = 1.0 - smoothstep(-fw, fw, d);       // outer-shape coverage

    // `inst.color` is PREMULTIPLIED RGBA8. ui_unpack_rgba8 yields a premultiplied
    // float4 (rgb already carries the * a factor); `result` accumulates the final
    // premultiplied pixel.
    float4 result = ui_unpack_rgba8(inst.color) * fill_cov;  // fill, area-weighted
    // UNIFORM border (P5a exact): the inner shape is the same rounded box inset by
    // the border width; the ring between outer and inner is the border color, drawn
    // OVER the fill in PREMULTIPLIED space (ui_premultiplied_over).
    if ((inst.flags & FLAG_BORDER_ANY) != 0u) {
        float bw = inst.border_width;
        float4 inner_r = max(inst.corner_radius - bw, 0.0);
        float d_inner = ui_sd_rounded_box(input.local_px, half_size - bw, inner_r);
        float inner_cov = 1.0 - smoothstep(-fw, fw, d_inner);
        float border_cov = saturate(fill_cov - inner_cov);    // exact ring (uniform)

        result = ui_premultiplied_over(ui_unpack_rgba8(inst.border_color), border_cov,
                                       ui_unpack_rgba8(inst.color), inner_cov);
    }

    if ((inst.flags & FLAG_CLIP_PRESENT) != 0u) {        // well-predicted uniform branch
        result *= ui_clip_coverage(input.pos_px, inst.clip, fw);
    }

    // PREMULTIPLIED output (rgb already carries * a; coverage already folded in).
    return result;
}
