// Benchmark: Component::component_id() hot path.
//
// Measures the amortized cost of reading a ComponentId after the OnceLock has
// been initialised. The cold-path (first call, which triggers register_new +
// AtomicUsize::fetch_add + OnceLock::set) can only fire once per type per
// process. Criterion's iter() loop calls the function millions of times, so
// what we actually measure is the hot path: a single OnceLock::get() ->
// pointer deref -> copy. That is the per-frame cost the ECS pays on every
// system call that looks up a ComponentId.
//
// To establish a cold-path number in the future, use criterion's iter_custom
// API with a fresh type per iteration via a separate process or build.rs
// code-gen. Out of scope for Phase 2c.

// Phase X.E: opt-in low-variance allocator for A/B signal extraction.
// OFF by default (`cargo bench` keeps the production system heap for honest
// absolutes); `cargo bench --features bench-alloc` swaps in mimalloc, which
// is far more deterministic and exposes structural signals the system heap
// masks (the documented ±20-30% variance source). See docs/BENCHMARKING.md.
#[cfg(feature = "bench-alloc")]
#[global_allocator]
static BENCH_ALLOC: mimalloc::MiMalloc = mimalloc::MiMalloc;

use boyko_ecs::ecs::core::component::component::Component;
use boyko_macros::Component;
use criterion::{black_box, criterion_group, criterion_main, Criterion};

// Bench component types. Must be non-ZST (ZST pools panic on arena alloc).
// ID assignment is handled by the OnceLock + register_new path generated by
// #[derive(Component)] — no manual register_layout needed.
#[derive(Component)]
struct BenchCompA {
    #[allow(dead_code)]
    x: f32,
    #[allow(dead_code)]
    y: f32,
    #[allow(dead_code)]
    z: f32,
}

#[derive(Component)]
struct BenchCompB {
    #[allow(dead_code)]
    v: u64,
}

/// Hot-path: OnceLock already initialised, single acquire-load.
fn bench_component_id_hot(c: &mut Criterion) {
    // Warm up the OnceLock before entering the measurement loop.
    let _ = BenchCompA::component_id();
    c.bench_function("component_id_hot_A", |b| {
        b.iter(|| black_box(BenchCompA::component_id()));
    });
}

/// Hot-path for a second type — confirms the cost is type-independent.
fn bench_component_id_hot_second_type(c: &mut Criterion) {
    // Warm up BenchCompB's OnceLock.
    let _ = BenchCompB::component_id();
    c.bench_function("component_id_hot_B", |b| {
        b.iter(|| black_box(BenchCompB::component_id()));
    });
}

criterion_group!(benches, bench_component_id_hot, bench_component_id_hot_second_type);
criterion_main!(benches);
