//! Render P5-r0 eDSL <-> raster-fragment SINGLE-SOURCE GUARD.
//!
//! `shaders/gbuffer_mrt.fs.hlsl`'s `oct_encode` / `pack_material_id_ba` BODIES are
//! MACHINE-GENERATED by `boyko_shaderdsl::emit` — the SAME `emit_hlsl_*` printer call
//! the marcher (`shaders/sdf_gbuffer_composite.hlsl`) consumes. One emission, TWO
//! splice sites: the raster fragment producer (P5-r0) and the marcher. They cannot
//! diverge BY CONSTRUCTION — UNLESS someone hand-edits the spliced span in the raster
//! `.fs.hlsl` without re-emitting, which would silently diverge the mesh G-buffer's
//! normal-encode / material-id pack from the marcher's (and thus from the resolve's
//! `oct_decode` / id reconstruct): a mis-lit mesh normal invisible until an
//! owner-visual on an asymmetric primitive.
//!
//! This test re-runs the generator and asserts the committed raster fragment shader
//! still contains the EXACT generated `oct_encode` / `pack_material_id_ba` bodies, so
//! that drift fails CI loudly (a hard build-gate — no ship on failure). It mirrors
//! `sdf_field_edsl_sync.rs` by name and mechanism. The fix when it trips: re-run
//!     cargo run -p boyko_shaderdsl --features emit --bin emit_field
//! and re-splice the `oct_encode` / `pack_material_id_ba` bodies between the `// ===
//! GENERATED ... BEGIN/END ===` sentinels in `shaders/gbuffer_mrt.fs.hlsl` (the same
//! bodies live in `sdf_gbuffer_composite.hlsl` — both splice the one emission).

/// Reads the committed P5-r0 raster fragment shader, LF-normalized so a CRLF checkout
/// does not spuriously mismatch the LF generator output.
fn raster_fs() -> String {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/gbuffer_mrt.fs.hlsl");
    std::fs::read_to_string(path)
        .expect("invariant: shaders/gbuffer_mrt.fs.hlsl must exist next to this crate")
        .replace("\r\n", "\n")
}

#[test]
fn raster_oct_encode_matches_edsl_emit() {
    // The mesh-MRT producer's `oct_encode` body is the SAME `emit_hlsl_oct_encode()`
    // span the marcher splices (one source, two sites). A hand-edit of the committed
    // raster span — which would diverge the mesh G-buffer normal from the marcher /
    // resolve — fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_oct_encode().replace("\r\n", "\n");
    let shader = raster_fs();

    assert!(
        shader.contains(&generated),
        "gbuffer_mrt.fs.hlsl `oct_encode` body DRIFTED from boyko_shaderdsl::emit — the \
         committed raster span no longer matches the generator (the SAME span the marcher \
         consumes). Re-run `cargo run -p boyko_shaderdsl --features emit --bin emit_field` \
         and re-splice the oct_encode body between the GENERATED oct_encode sentinels in \
         gbuffer_mrt.fs.hlsl.\n--- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn raster_pack_material_id_ba_matches_edsl_emit() {
    // The mesh-MRT producer's `pack_material_id_ba` body is the SAME
    // `emit_hlsl_pack_material_id_ba()` span the marcher splices. A hand-edit of the
    // committed raster span — which would diverge the mesh material-id pack from the
    // marcher / resolve's id reconstruct — fails CI here.
    let generated =
        boyko_shaderdsl::emit::emit_hlsl_pack_material_id_ba().replace("\r\n", "\n");
    let shader = raster_fs();

    assert!(
        shader.contains(&generated),
        "gbuffer_mrt.fs.hlsl `pack_material_id_ba` body DRIFTED from boyko_shaderdsl::emit — \
         the committed raster span no longer matches the generator (the SAME span the \
         marcher consumes). Re-run `cargo run -p boyko_shaderdsl --features emit --bin \
         emit_field` and re-splice the pack_material_id_ba body between the GENERATED \
         pack_material_id_ba sentinels in gbuffer_mrt.fs.hlsl.\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}
