//! eDSL <-> HLSL SINGLE-SOURCE GUARD for the B2 per-instance interpolation pass.
//!
//! `shaders/interp_instances.comp.hlsl`'s `interp_trs` body (the TRS interpolation +
//! 3×4 model-affine compose) is MACHINE-GENERATED by
//! `boyko_shaderdsl::emit::emit_hlsl_transform_interp()` — the eDSL whose `f32` Eval
//! backend (`transform_pair_interp_body::<f32>`) IS the CPU oracle (its composed rows
//! byte-match `boyko_render::InstanceModelCol::from_global` for the interpolated TRS,
//! proven by `boyko_shaderdsl`'s own eval-mirror suite). A hand-edit of the spliced body
//! — which would silently diverge the GPU interpolation from that host oracle — fails CI
//! here.
//!
//! Two gates:
//!   1. `interp_trs_matches_edsl_emit` — the committed shader still contains the EXACT
//!      generated `interp_trs` function (text drift fails loudly).
//!   2. `interp_spv_byte_identical` — a fresh DXC of the WHOLE committed `.hlsl` under
//!      the frozen recipe (`-spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3`, NO
//!      `-O`) equals the committed `.spv` byte-for-byte (SKIPS when DXC is absent).
//!
//! The fix when gate 1 trips: re-run
//!     cargo run -p boyko_shaderdsl --features emit --bin emit_field
//! (which now also prints `interp_trs`), re-splice the body between the
//! `// === GENERATED interp_trs BEGIN/END ===` sentinels, then re-DXC the `.spv`.

use std::path::PathBuf;
use std::process::Command;

/// The shaders directory (`CARGO_MANIFEST_DIR/shaders`), where the committed `.hlsl` and
/// `.spv` live.
fn shaders_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("shaders")
}

/// Extracts a `NAME(...) { ... }` function — the signature line through its MATCHING
/// closing brace — out of generated HLSL. A BRACE COUNTER (not a first-`}` scan) so a
/// body with nested braces extracts whole. The generated `interp_trs` has one nested
/// scope-free block, but the counter is the robust general form. String/comment braces
/// do not occur in the generated body, so a raw brace count is exact.
fn extract_fn(src: &str, sig: &str) -> String {
    let start = src
        .find(sig)
        .unwrap_or_else(|| panic!("generated HLSL output is missing `{sig}`"));
    let after = &src[start..];
    let open = after
        .find('{')
        .expect("a generated function must have an opening brace");
    let mut depth = 0i32;
    for (i, ch) in after[open..].char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return after[..open + i + 1].to_string();
                }
            }
            _ => {}
        }
    }
    panic!("unbalanced braces extracting `{sig}` — the function never closed");
}

/// Locates the `dxc` executable: first the pinned Vulkan-SDK path (the repo's offline
/// recipe), then `$VULKAN_SDK/Bin`, then `PATH`. Returns `None` if none resolve (the
/// byte-identity test then SKIPS).
fn find_dxc() -> Option<PathBuf> {
    let pinned = PathBuf::from("C:/VulkanSDK/1.4.350.0/Bin/dxc.exe");
    if pinned.exists() {
        return Some(pinned);
    }
    let bare = if cfg!(windows) { "dxc.exe" } else { "dxc" };
    if let Ok(sdk) = std::env::var("VULKAN_SDK") {
        let candidate = PathBuf::from(sdk).join("Bin").join(bare);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    if Command::new(bare).arg("--version").output().is_ok() {
        return Some(PathBuf::from(bare));
    }
    None
}

/// Re-DXCs `hlsl_name` (relative to the shaders dir) under the EXACT frozen recipe into a
/// fresh TEMP `.spv`, and returns the bytes. Never overwrites a committed artifact.
fn redxc_to_bytes(dxc: &PathBuf, dir: &PathBuf, hlsl_name: &str) -> Vec<u8> {
    let out_spv = std::env::temp_dir().join(format!("{hlsl_name}.redxc.spv"));
    let status = Command::new(dxc)
        .current_dir(dir)
        .args([
            "-spirv",
            "-T",
            "cs_6_0",
            "-E",
            "main",
            "-fspv-target-env=vulkan1.3",
            hlsl_name,
            "-Fo",
        ])
        .arg(&out_spv)
        .status()
        .expect("invariant: dxc was located and must run");
    assert!(
        status.success(),
        "dxc failed re-compiling {hlsl_name} under the frozen recipe"
    );
    let bytes = std::fs::read(&out_spv).expect("invariant: dxc wrote the re-DXC .spv");
    let _ = std::fs::remove_file(&out_spv);
    bytes
}

#[test]
fn interp_trs_matches_edsl_emit() {
    let generated =
        boyko_shaderdsl::emit::emit_hlsl_transform_interp().replace("\r\n", "\n");
    let interp_trs = extract_fn(
        &generated,
        "InterpModel interp_trs(TransformPair pair, float alpha) {",
    );

    let shader_path = shaders_dir().join("interp_instances.comp.hlsl");
    let shader = std::fs::read_to_string(&shader_path)
        .expect("invariant: shaders/interp_instances.comp.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&interp_trs),
        "interp_instances.comp.hlsl `interp_trs` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the interp_trs body between the \
         GENERATED interp_trs sentinels, then re-DXC interp_instances.comp.spv.\n\
         --- expected (eDSL-generated) ---\n{interp_trs}"
    );
}

#[test]
fn interp_spv_byte_identical() {
    let Some(dxc) = find_dxc() else {
        eprintln!(
            "interp_edsl_sync: dxc not found (no C:/VulkanSDK/.../dxc.exe, no $VULKAN_SDK/Bin, \
             not on PATH) — SKIPPING the interp re-DXC byte-identity check on this host."
        );
        return;
    };

    let dir = shaders_dir();
    let committed_spv_path = dir.join("interp_instances.comp.spv");
    let committed_spv = std::fs::read(&committed_spv_path).unwrap_or_else(|e| {
        panic!("invariant: committed interp_instances.comp.spv must exist: {e}")
    });

    let regenerated = redxc_to_bytes(&dxc, &dir, "interp_instances.comp.hlsl");

    assert_eq!(
        committed_spv.len(),
        regenerated.len(),
        "committed interp_instances.comp.spv is a different SIZE than a fresh DXC of the \
         committed .hlsl — re-DXC and re-commit the .spv"
    );
    assert!(
        committed_spv == regenerated,
        "committed interp_instances.comp.spv DIVERGED from a fresh DXC of the committed .hlsl. \
         The .spv the engine loads is not the single-sourced text — re-DXC \
         `dxc -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3 interp_instances.comp.hlsl \
         -Fo interp_instances.comp.spv` and re-commit the .spv."
    );
}
