//! eDSL <-> HLSL SINGLE-SOURCE GUARD.
//!
//! `shaders/sdf_field.hlsli`'s `smin` / `smax` bodies are MACHINE-GENERATED by
//! `boyko_shaderdsl::emit` — the eDSL whose `Eval` backend (`impl FieldScalar for
//! f32`) IS the host field `boyko_sdf_math::sdf_edit_list`. Both the host (Eval) and
//! the generated HLSL (Emit) instantiate the SAME generic `boyko_shaderdsl::field`
//! body, so they cannot diverge BY CONSTRUCTION — UNLESS someone hand-edits the
//! spliced `smin`/`smax` in the header without re-emitting, which would silently
//! diverge the GPU field from the host field: exactly the by-hand drift (black
//! surfaces, AO craters) the eDSL was built to kill.
//!
//! This test re-runs the generator and asserts the committed header still contains
//! the EXACT generated `smin`/`smax` bodies, so that drift fails CI loudly. The fix
//! when it trips: re-run
//!     cargo run -p boyko_shaderdsl --features emit --bin emit_field
//! and re-splice the `smin`/`smax` bodies between the `// === GENERATED FIELD MATH
//! BEGIN/END ===` sentinels in `shaders/sdf_field.hlsli`.
//!
//! Scope: `smin`/`smax` only — `combine` is intentionally NOT eDSL-generated (its
//! lazy `(k>0)?smooth:hard` ternary lowers to `OpBranchConditional`/`OpPhi`, which
//! the eager `OpSelect` the `Emit` backend produces would fork; `combine` carries no
//! polynomial field math, only calls to the generated `smin`/`smax`). The Eval-side
//! byte-identity (Eval == the frozen host snapshot) is proven separately by
//! `boyko_shaderdsl`'s `eval_byte_identity` suite.

/// Extracts a `float NAME(...) { ... }` function — the signature line through its
/// MATCHING closing brace — out of generated HLSL.
///
/// A BRACE COUNTER (not a first-`\n}` scan): the control-flow leaf
/// `dist_to_brick_exit` has NESTED `}` (the `[unroll] for { ... }` loop and the
/// `if (...) { ... }` skip), so the first `}` on its own line closes the loop, NOT the
/// function. Counting `{`/`}` from the signature's opening brace to its balanced close
/// extracts the whole function for any body (straight-line or control-flow). String/
/// comment braces do not occur in the generated bodies, so a raw brace count is exact.
fn extract_fn(src: &str, sig: &str) -> String {
    let start = src
        .find(sig)
        .unwrap_or_else(|| panic!("generated HLSL output is missing `{sig}`"));
    let after = &src[start..];
    let open = after
        .find('{')
        .expect("a generated function must have an opening brace");
    let mut depth = 0i32;
    for (i, ch) in after[open..].char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    // `open + i` is the matching close brace; include it.
                    return after[..open + i + 1].to_string();
                }
            }
            _ => {}
        }
    }
    panic!("unbalanced braces extracting `{sig}` — the function never closed");
}

#[test]
fn sdf_field_smin_smax_match_edsl_emit() {
    // Generate the HLSL field bodies from the eDSL (LF-normalized).
    let generated = boyko_shaderdsl::emit::emit_hlsl_field().replace("\r\n", "\n");
    let smin = extract_fn(&generated, "float smin(float a, float b, float k) {");
    let smax = extract_fn(&generated, "float smax(float a, float b, float k) {");

    // Read the committed header (LF-normalized so a CRLF checkout does not spuriously
    // mismatch the LF generator output).
    let header_path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/sdf_field.hlsli");
    let header = std::fs::read_to_string(header_path)
        .expect("invariant: shaders/sdf_field.hlsli must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        header.contains(&smin),
        "sdf_field.hlsli `smin` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the smin body between the GENERATED sentinels.\n\
         --- expected (eDSL-generated) ---\n{smin}"
    );
    assert!(
        header.contains(&smax),
        "sdf_field.hlsli `smax` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run the emit_field bin and re-splice the smax body \
         between the GENERATED sentinels.\n\
         --- expected (eDSL-generated) ---\n{smax}"
    );
}

#[test]
fn sdf_normal_matches_edsl_emit() {
    // The GPU surface-normal leaf `sdf_normal` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_normal()` (A1) from the SAME source whose `f32`
    // Eval backend is byte-identical to the host `boyko_sdf_math::sdf_edit_list_normal`.
    // A hand-edit of the committed body (which would silently diverge the GPU normal
    // from the host normal — the central-difference shading the AO/lighting reads)
    // fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_normal().replace("\r\n", "\n");
    let sdf_normal = extract_fn(&generated, "float3 sdf_normal(float3 p) {");

    let header_path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/sdf_field.hlsli");
    let header = std::fs::read_to_string(header_path)
        .expect("invariant: shaders/sdf_field.hlsli must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        header.contains(&sdf_normal),
        "sdf_field.hlsli `sdf_normal` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the sdf_normal body between the GENERATED NORMAL \
         sentinels.\n--- expected (eDSL-generated) ---\n{sdf_normal}"
    );
}

#[test]
fn m2_decode_matches_edsl_emit() {
    // The brick snorm decode SCALE leaf `m2_decode` (`n * band_half`) in
    // `sdf_gbuffer_composite.hlsl` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_decode_snorm8()` (A2) from the SAME source whose
    // `f32` Eval backend (the WHOLE `decode_snorm8`: byte → normalize → scale) is
    // byte-identical to the host `boyko_sdf_math::brick::decode_snorm8`. Only the SCALE
    // is shader code (the byte → normalize is the hardware R8_SNORM sampler), so this
    // pins the spliced scale body to the generator. A hand-edit — which would silently
    // diverge the GPU brick decode from the host oracle the trilinear fetch is golden-
    // compared against — fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_decode_snorm8().replace("\r\n", "\n");
    let m2_decode = extract_fn(&generated, "float m2_decode(float n, float band_half) {");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&m2_decode),
        "sdf_gbuffer_composite.hlsl `m2_decode` DRIFTED from boyko_shaderdsl::emit — the committed \
         body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the m2_decode body between the GENERATED decode_snorm8 \
         sentinels.\n--- expected (eDSL-generated) ---\n{m2_decode}"
    );
}

#[test]
fn m2_cubic_eval_matches_edsl_emit() {
    // The M2 cubic Horner leaf `m2_cubic_eval` in `sdf_gbuffer_composite.hlsl` is
    // GENERATED by `boyko_shaderdsl::emit::emit_hlsl_cubic_eval()` (A3) from the SAME
    // source whose `f32` Eval backend is byte-identical to the host
    // `boyko_sdf_math::brick::cubic_eval`. A hand-edit — which would silently drift the
    // GPU cubic eval from the host oracle that feeds the hit-`t` (where hit/miss is a
    // CLIFF, not a tolerance band) — fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_cubic_eval().replace("\r\n", "\n");
    let m2_cubic_eval = extract_fn(&generated, "float m2_cubic_eval(float4 c, float t) {");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&m2_cubic_eval),
        "sdf_gbuffer_composite.hlsl `m2_cubic_eval` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the m2_cubic_eval body between the \
         GENERATED m2_cubic_eval sentinels.\n--- expected (eDSL-generated) ---\n{m2_cubic_eval}"
    );
}

#[test]
fn m2_jcgt_cubic_coeffs_matches_edsl_emit() {
    // The M2 trilinear → cubic-coefficient fold `m2_jcgt_cubic_coeffs` in
    // `sdf_gbuffer_composite.hlsl` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_jcgt_cubic_coeffs()` (A3) from the SAME source
    // whose `f32` Eval backend is byte-identical to the host
    // `boyko_sdf_math::brick::jcgt_cubic_coeffs`. This is the HIGHEST-drift-value leaf
    // (the M2 crease bug lived in the cubic); a hand-edit fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_jcgt_cubic_coeffs().replace("\r\n", "\n");
    let m2_jcgt =
        extract_fn(&generated, "float4 m2_jcgt_cubic_coeffs(float s[8], float3 a, float3 b) {");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&m2_jcgt),
        "sdf_gbuffer_composite.hlsl `m2_jcgt_cubic_coeffs` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the m2_jcgt_cubic_coeffs body between the \
         GENERATED m2_jcgt_cubic_coeffs sentinels.\n--- expected (eDSL-generated) ---\n{m2_jcgt}"
    );
}

#[test]
fn dist_to_brick_exit_matches_edsl_emit() {
    // The brick-exit empty-skip MARCHER `dist_to_brick_exit` in `sdf_gbuffer_composite.hlsl`
    // is GENERATED by `boyko_shaderdsl::emit::emit_hlsl_dist_to_brick_exit()` (Increment 1 —
    // the first CONTROL-FLOW leaf: the `[unroll]` slab loop with the data-dependent
    // `continue` + the final progress-clamp ternary) from the SAME source whose `<f32,
    // EvalCf>` instantiation (`boyko_shaderdsl::brick::dist_to_brick_exit_body`) is the CPU
    // oracle. A hand-edit — which would silently diverge the GPU empty-skip step from the
    // single-source body — fails CI here. (The cmp-`.spv` gate proves the spliced text
    // re-DXCs byte-identical to the committed `.comp.spv`.)
    //
    // The host `boyko_sdf_math::brick::dist_to_brick_exit` stays HAND-WRITTEN (firewall
    // option B) and is intentionally NOT compared here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_dist_to_brick_exit().replace("\r\n", "\n");
    let dist = extract_fn(
        &generated,
        "float dist_to_brick_exit(float3 p, float3 rd, float3 cell_min, float bw) {",
    );

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&dist),
        "sdf_gbuffer_composite.hlsl `dist_to_brick_exit` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the dist_to_brick_exit body between the \
         GENERATED dist_to_brick_exit sentinels.\n--- expected (eDSL-generated) ---\n{dist}"
    );
}

#[test]
fn brick_cell_class_matches_edsl_emit() {
    // The brick-cell pointer-grid lookup MARCHER `brick_cell_class` in
    // `sdf_gbuffer_composite.hlsl` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_brick_cell_class()` (Increment 3 — the second
    // CONTROL-FLOW leaf: the two EARLY-RETURN guards, the `uint` index math, the
    // `StructuredBuffer<uint>` load, and the two `out float3 cell_min` writes) from the SAME
    // source whose `<EvalCf>` instantiation (`boyko_shaderdsl::brick::brick_cell_class_body`)
    // is the CPU oracle. A hand-edit — which would silently diverge the GPU pointer-grid
    // lookup from the single-source body — fails CI here. (The one-shot cmp-`.spv` proves the
    // spliced text re-DXCs byte-identical to the committed `.comp.spv`.)
    //
    // The host `host_brick_cell` (boyko_rhi_vulkan::compute) stays HAND-WRITTEN (firewall
    // option B) and is intentionally NOT compared here. The three call sites (PointerGrid/1/2)
    // are the function's CALLERS — the generator emits only the DEFINITION; the call sites are
    // untouched.
    let generated = boyko_shaderdsl::emit::emit_hlsl_brick_cell_class().replace("\r\n", "\n");
    // The signature is two lines; `extract_fn` matches the first line (its brace counter then
    // spans the whole body to the balanced close).
    let bcc = extract_fn(
        &generated,
        "uint brick_cell_class(StructuredBuffer<uint> grid, float3 origin, float bw, uint3 dims,",
    );

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&bcc),
        "sdf_gbuffer_composite.hlsl `brick_cell_class` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the brick_cell_class body between the \
         GENERATED brick_cell_class sentinels (the 3 call sites stay UNCHANGED).\n\
         --- expected (eDSL-generated) ---\n{bcc}"
    );
}

#[test]
fn m2_regula_falsi_matches_edsl_emit() {
    // The regula-falsi root-refinement MARCHER `m2_regula_falsi` in
    // `sdf_gbuffer_composite.hlsl` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_m2_regula_falsi()` (Increment 4a — the THIRD
    // CONTROL-FLOW leaf, the first with a genuine RUNTIME `[loop]` (an OpLoop): five
    // loop-carried Phi vars {lo,hi,f_lo,f_hi as suppressed-decl params + mid as a local},
    // an in-loop early return forwarded to the function IIFE, and a `m2_cubic_eval(c, mid)`
    // call site) from the SAME source whose `<EvalCf>` instantiation
    // (`boyko_shaderdsl::brick::m2_regula_falsi_body`) is the CPU oracle. A hand-edit —
    // which would silently diverge the GPU root refinement from the single-source body —
    // fails CI here. (The cmp-`.spv` proves the spliced text re-DXCs byte-identical to the
    // committed `.comp.spv`.)
    //
    // The host `boyko_sdf_math::brick::regula_falsi` stays HAND-WRITTEN (firewall option B)
    // and is intentionally NOT compared here (it uses `f32::MIN_POSITIVE`, the eDSL/GPU
    // shape uses `1.0e-30`). The two `m2_marmitt_root` call sites are the function's CALLERS
    // — the generator emits only the DEFINITION; the call sites are untouched.
    let generated = boyko_shaderdsl::emit::emit_hlsl_m2_regula_falsi().replace("\r\n", "\n");
    let rf = extract_fn(
        &generated,
        "float m2_regula_falsi(float4 c, float lo, float hi, float f_lo, float f_hi) {",
    );

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&rf),
        "sdf_gbuffer_composite.hlsl `m2_regula_falsi` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the m2_regula_falsi body between the \
         GENERATED m2_regula_falsi sentinels (the 2 call sites stay UNCHANGED).\n\
         --- expected (eDSL-generated) ---\n{rf}"
    );
}

#[test]
fn sdf_soft_shadow_matches_edsl_emit() {
    // The sdf_soft_shadow penumbra loop+tail span (Inc 4b — the runtime [loop] + brk + the
    // field_distance call1) is GENERATED by boyko_shaderdsl::emit::emit_hlsl_sdf_soft_shadow().
    // It is a SPAN, not a whole function: the dot/early-return preamble stays hand-written inline
    // (framing b), so this is a `.contains` of the emitted span (spliced between the GENERATED
    // sdf_soft_shadow sentinels), not an extract_fn. A hand-edit of the committed span fails CI
    // here. The cmp-.spv proves the spliced text re-DXCs byte-identical (R1: `t = t + max` ==
    // `t += max`); the host shadow march stays analytic (C1) and is not generated.
    let generated = boyko_shaderdsl::emit::emit_hlsl_sdf_soft_shadow().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `sdf_soft_shadow` span DRIFTED from boyko_shaderdsl::emit — the \
         committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED sdf_soft_shadow \
         sentinels (the dot preamble stays hand-written).\n--- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn sdf_soft_shadow_ranged_matches_edsl_emit() {
    // P6 R1: the `t_max`-RANGED soft-shadow leaf `sdf_soft_shadow_ranged(p,n,L,t_max)` —
    // consumed by the deferred RESOLVE (`deferred_pbr.hlsl`), NOT the marcher — is GENERATED
    // by boyko_shaderdsl::emit::emit_hlsl_sdf_soft_shadow_ranged(). It is a WHOLE function
    // (unlike the marcher's `sdf_soft_shadow` SPAN splice): the resolve calls it per extra
    // shadow caster. A hand-edit of the committed function fails CI here. The body is
    // statement-for-statement identical to `sdf_soft_shadow` EXCEPT the escape break spells
    // the PARAMETER `t_max` (B3 — option a, so the marcher's frozen `sdf_gbuffer_composite.
    // comp.spv` cannot move; `marcher_spv_byte_frozen` is the gate for that). The resolve
    // re-DXCs to `deferred_pbr.comp.spv`; the host shadow march mirror is
    // `host_soft_shadow_ranged` (compute.rs), consumer-side (±2/255).
    let generated = boyko_shaderdsl::emit::emit_hlsl_sdf_soft_shadow_ranged().replace("\r\n", "\n");

    let shader_path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/deferred_pbr.hlsl");
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/deferred_pbr.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "deferred_pbr.hlsl `sdf_soft_shadow_ranged` DRIFTED from boyko_shaderdsl::emit — the \
         committed function no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the sdf_soft_shadow_ranged function \
         between the GENERATED sdf_soft_shadow_ranged sentinels, then re-DXC deferred_pbr.comp.spv \
         (bump DEFERRED_PBR_SPV in compute.rs to the new size).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn m2_surface_hit_refine_matches_edsl_emit() {
    // The m2_surface_hit REFINE LOOP+TAIL span (Inc 4b.2 — the production analytic-residual
    // signed refine: the runtime [loop] sphere-trace onto the EXACT field, the converged-hit
    // `hit_t = rt; return true;`, the `rt < 0 || rt > T_MAX` break, the tail `return false;`) is
    // GENERATED by boyko_shaderdsl::emit::emit_hlsl_m2_surface_hit_refine(). It reuses the proven
    // runtime [loop] + brk + the field_distance call1, and adds a real OpTypeBool return
    // (`Cf::ret_b` — `return true`/`return false`, NOT uint 0/1) + an `out float hit_t` write
    // (`Cf::out_float_assign`), folded by the composite `Cf::if_hit_ret_b`. Like sdf_soft_shadow it
    // is a SPAN, not a whole function: the integer cell-addressing preamble + the
    // m2_brick_span/m2_brick_cubic_hit/select_level call sites stay hand-written inline (framing b),
    // so this is a `.contains` of the emitted span (spliced between the GENERATED
    // m2_surface_hit_refine sentinels), not an extract_fn. A hand-edit of the committed span fails
    // CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical (R1: `rt = rt + step` ==
    // `rt += step`); the host `host_m2_surface_hit` refine stays hand-written and is not generated.
    let generated = boyko_shaderdsl::emit::emit_hlsl_m2_surface_hit_refine().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `m2_surface_hit` refine span DRIFTED from boyko_shaderdsl::emit \
         — the committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED m2_surface_hit_refine \
         sentinels (the integer preamble + the 3 call sites stay hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn b1_accept_refine_matches_edsl_emit() {
    // The B1 over-relaxation ACCEPT-REFINE inner-loop span (Inc 4c — a near-CLONE of
    // m2_surface_hit_refine but STRICTLY SIMPLER: NO return facet — the only loop control is the
    // `abs(rd_) < EPS` `brk`; the field seam interns `sdf` (the ANALYTIC field, NOT
    // `field_distance`); the span prints at DEPTH 3 (the site nests main→`for (it)`→`if (d < EPS)`→
    // this refine loop)) is GENERATED by boyko_shaderdsl::emit::emit_hlsl_b1_accept_refine(). The
    // production B1 marcher's settle-onto-surface refine: the fixed-budget (`M2_REFINE_ITERS`)
    // SIGNED sphere-trace that corrects an over-relaxed accept off the surface
    // (`t = t + M2_REFINE_RELAX * sdf(...)`), accepting on `abs(rd_) < EPS`. Like sdf_soft_shadow it
    // is a SPAN, not a whole function: the enclosing over-relaxation marcher (the `hit = true;
    // exhausted = false;` accept block + the rationale comment + the outer marcher `break;`) stays
    // hand-written inline (framing b), so this is a `.contains` of the emitted span (spliced between
    // the GENERATED b1_accept_refine sentinels), not an extract_fn. A hand-edit of the committed span
    // fails CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical (R1: `t = t + step`
    // == `t += step` at this depth-3 site); the host B1 marcher stays hand-written and is not
    // generated.
    let generated = boyko_shaderdsl::emit::emit_hlsl_b1_accept_refine().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `b1_accept_refine` span DRIFTED from boyko_shaderdsl::emit — the \
         committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED b1_accept_refine \
         sentinels (the over-relaxation marcher + the outer break stay hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn b1_decl_hit_matches_edsl_emit() {
    // The B1 marcher's `bool hit = false;` preamble decl (Inc 4d — the FIRST rung of the
    // B1-marcher single-source ladder, the first TYPED `bool` decl facet via `Cf::decl_bool_var`)
    // is GENERATED by boyko_shaderdsl::emit::emit_hlsl_b1_decl_hit(). It is a single decl LINE
    // spliced between the `// === GENERATED b1_decl_hit BEGIN/END ===` sentinels at L1316 inside
    // the main B1 marcher; the 4 `float` decls + the BUG-B1-HOLE-3 comment that separate it from
    // the (non-contiguous) `exhausted` decl stay HAND-WRITTEN (framing b), so this is a `.contains`
    // of the emitted line (like the other span tests), not an extract_fn. A hand-edit of the
    // committed decl fails CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical.
    let generated = boyko_shaderdsl::emit::emit_hlsl_b1_decl_hit().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `b1_decl_hit` decl DRIFTED from boyko_shaderdsl::emit — the \
         committed line no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED b1_decl_hit \
         sentinels (the float decls + the BUG-B1-HOLE-3 comment stay hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn b1_decl_exhausted_matches_edsl_emit() {
    // The B1 marcher's `bool exhausted = true;` preamble decl (Inc 4d — the BUG-B1-HOLE-3
    // budget-exhaustion flag, init true, cleared by every in-loop break) is GENERATED by
    // boyko_shaderdsl::emit::emit_hlsl_b1_decl_exhausted(). It is a single decl LINE spliced
    // between the `// === GENERATED b1_decl_exhausted BEGIN/END ===` sentinels at L1327 inside the
    // main B1 marcher; the `hit` decl + the 4 `float` decls + the BUG-B1-HOLE-3 comment between the
    // two (non-contiguous) bool decls stay HAND-WRITTEN (framing b), so this is a `.contains` of
    // the emitted line. A hand-edit of the committed decl fails CI here. The cmp-.spv proves the
    // spliced text re-DXCs byte-identical.
    let generated = boyko_shaderdsl::emit::emit_hlsl_b1_decl_exhausted().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `b1_decl_exhausted` decl DRIFTED from boyko_shaderdsl::emit — \
         the committed line no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED b1_decl_exhausted \
         sentinels (the hit decl + the float decls + the BUG-B1-HOLE-3 comment stay hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn b1_exhaustion_remarch_matches_edsl_emit() {
    // The B1 EXHAUSTION RE-MARCH inner-loop span (Inc 4e — a near-CLONE of b1_accept_refine with 4
    // new facets: the FLOAT mesh guard `t >= t_mesh` (`FieldScalar::ge`), a NAMED `float3 p` temp
    // (`Cf::temp_vec3`), and the in-loop `hit = true;` (`Cf::set_bool_var`) carried by a
    // SUPPRESSED-DECL bool (`Cf::decl_bool_param`/`get_bool_var`)) is GENERATED by
    // boyko_shaderdsl::emit::emit_hlsl_b1_exhaustion_remarch(). The production B1 marcher's
    // BUG-B1-HOLE-3 budget-exhaustion recovery: the plain `omega == 1.0` sphere-trace from the
    // ORIGINAL seed (`t = t + sdf(p)`), run when the over-relaxed fast pass exhausted `MAX_IT`
    // mid-field, with the `t >= t_mesh` mesh-guard break, the `d < EPS` accept (`hit = true;
    // break;`), and the `t > T_MAX` miss break. Like the other refine spans it is a SPAN, not a
    // whole function: the enclosing `if (exhausted) { t = t_seed; hit = false; ... }` wrapper + the
    // BUG-B1-HOLE-3 rationale comment stay hand-written inline (framing b), so this is a `.contains`
    // of the emitted span (spliced between the GENERATED b1_exhaustion_remarch sentinels), not an
    // extract_fn. A hand-edit of the committed span fails CI here. The cmp-.spv proves the spliced
    // text re-DXCs byte-identical (R1: `t = t + d` == `t += d` at this depth-2 site); the host B1
    // marcher stays hand-written and is not generated.
    let generated = boyko_shaderdsl::emit::emit_hlsl_b1_exhaustion_remarch().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `b1_exhaustion_remarch` span DRIFTED from boyko_shaderdsl::emit \
         — the committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED b1_exhaustion_remarch \
         sentinels (the `if (exhausted)` re-seed wrapper + the BUG-B1-HOLE-3 comment stay \
         hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn b1_sor_retreat_matches_edsl_emit() {
    // The B1 over-relaxation SOR-FAIL-RETREAT STEP span (Inc 4f — the DEFENSIBLE TERMINUS of the
    // B1-marcher single-source ladder: the Keinert over-relaxed step + the Lipschitz-aware retreat-
    // to-plain + the `t > T_MAX` miss) is GENERATED by boyko_shaderdsl::emit::emit_hlsl_b1_sor_retreat().
    // The 4f facets vs the prior B1 rungs: the TWO-arm `if (omega > 1.0) { ... } else { ... }`
    // (`Cf::if_else`), a CAPTURED `uint` `it` read (the uint analogue of Inc4e's captured float
    // `t_mesh`), a `uint` `>` guard (`Cf::ugt`) joined by a logical `&&` (`Cf::and2`) to the
    // Lipschitz `<` with a bare `0u` (`Cf::uint_lit`), and the mid-body `continue` (`Cf::cont`).
    // `d` is the already-sampled field value (a float input — NO field call in this span). Like the
    // other refine spans it is a SPAN, not a whole function: the enclosing `for (uint it)` header,
    // the mesh-guard, the M1/M2 brick islands, `float d = sdf(p);`, the `d < EPS` accept block, and
    // ALL BUG-B1-HOLE rationale comments stay hand-written inline (framing b; the rationale travels
    // in the boyko_shaderdsl::sor module doc), so this is a `.contains` of the emitted span (spliced
    // between the GENERATED b1_sor_retreat sentinels — the SECOND generated sentinel inside that one
    // `for (uint it)` loop, after the accept-refine), not an extract_fn. A hand-edit of the committed
    // span fails CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical (R1: `t = t + …`
    // == `t += …` at this depth-2 site, BOTH arms — proven by the GO/NO-GO spike); the host B1
    // marcher stays hand-written and is not generated.
    let generated = boyko_shaderdsl::emit::emit_hlsl_b1_sor_retreat().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `b1_sor_retreat` span DRIFTED from boyko_shaderdsl::emit — the \
         committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED b1_sor_retreat \
         sentinels (the `for (uint it)` loop frame + the BUG-B1-HOLE comments stay hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn b1_marcher_mesh_p_matches_edsl_emit() {
    // The B1 main-marcher MESH-GUARD + PROBE-POINT glue span (Inc 4g-g1 SPAN A — literal
    // completeness: the production `for (uint it...)` loop's `if (t >= t_mesh) { exhausted = false;
    // break; }` mesh-occlusion guard + the `float3 p = ro + rd * t;` probe-point compute, contiguous
    // right after the loop header `{` and BEFORE the M1 brick island) is GENERATED by
    // boyko_shaderdsl::emit::emit_hlsl_b1_marcher_mesh_p(). Pure REUSE (ZERO new machinery): the
    // FLOAT mesh guard `t >= t_mesh` (`FieldScalar::ge`), the in-guard `exhausted = false;`
    // (`Cf::set_bool_var` over a SUPPRESSED-DECL bool `Cf::decl_bool_param`), the `brk`, and the NAMED
    // `float3 p` temp (`Cf::temp_vec3`). `p` is READ-ONLY in the loop, so a `temp_vec3` (a `float3 p =
    // ...;` DeclTemp), NOT a mutable `decl_var_vec3`; the hand-written M1/M2 islands + the fold span
    // read `p` by NAME (the cross-splice name-sharing). Like the other B1 rungs it is a SPAN, not a
    // whole function: the enclosing `for (uint it)` header + the M1/M2 brick islands + the accept
    // wrapper stay hand-written inline (framing b), so this is a `.contains` of the emitted span
    // (spliced between the GENERATED b1_marcher_mesh_p sentinels), not an extract_fn. A hand-edit of
    // the committed span fails CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical.
    let generated = boyko_shaderdsl::emit::emit_hlsl_b1_marcher_mesh_p().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `b1_marcher_mesh_p` span DRIFTED from boyko_shaderdsl::emit — the \
         committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED b1_marcher_mesh_p \
         sentinels (the `for (uint it)` loop frame + the M1/M2 brick islands stay hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn b1_marcher_fold_d_matches_edsl_emit() {
    // The B1 main-marcher ANALYTIC-FOLD DISTANCE glue span (Inc 4g-g1 SPAN B: the production
    // `for (uint it...)` loop's `float d = sdf(p);` analytic field sample, AFTER the M2 trilinear
    // brick island and BEFORE the `if (d < EPS)` accept wrapper) is GENERATED by
    // boyko_shaderdsl::emit::emit_hlsl_b1_marcher_fold_d(). Pure REUSE — the field-call seam
    // (`Cf::call1`, interned `"sdf"` — the ANALYTIC field, NOT `field_distance`) into a NAMED `float
    // d` temp (`Cf::temp_float`). `p` is a CAPTURED `float3` (SPAN A declared `float3 p = ...;` above;
    // each span is a fresh emit, so `p` re-seeds by name as a `Vec3Param`); the hand-written `if (d <
    // EPS)` accept wrapper reads `d` by NAME (the cross-splice name-sharing). Like the other B1 rungs
    // it is a SPAN, not a whole function: the loop header + the M1/M2 islands + the accept wrapper
    // (which nests the Inc-4c accept-refine span) stay hand-written inline (framing b), so this is a
    // `.contains` of the emitted span (spliced between the GENERATED b1_marcher_fold_d sentinels), not
    // an extract_fn. A hand-edit of the committed span fails CI here. The cmp-.spv proves the spliced
    // text re-DXCs byte-identical.
    let generated = boyko_shaderdsl::emit::emit_hlsl_b1_marcher_fold_d().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `b1_marcher_fold_d` span DRIFTED from boyko_shaderdsl::emit — the \
         committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED b1_marcher_fold_d \
         sentinels (the M2 brick island + the `if (d < EPS)` accept wrapper stay hand-written).\n\
         --- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn select_level_matches_edsl_emit() {
    // The M4 clip-map LEVEL-SELECTOR scan span (Inc 5a — the FIRST signed-int-returning leaf,
    // landing the signed-int subsystem: the `[unroll]` finest-first containment scan returning the
    // tightest enclosing LOD index (`return (int)L;` via `Cf::if_ret_i` + `Cf::int_from_uint`) or
    // `-1` (`return -1;` via `Cf::ret_i` + `Cf::int_lit_signed` — a BARE signed literal, NOT a
    // `<x>u`)) is GENERATED by boyko_shaderdsl::emit::emit_hlsl_select_level(). The new facets: the
    // signed-int return path (`EmitTy::Int` + `Node::IntLit`/`IntFromUint`), the `all(p >= o) &&
    // all(p < hi)` bool3 reduction (`Cf::all3_ge`/`all3_lt`), the `pc.brick_levels` push-constant
    // read (`Cf::pc_uint`), and the `M4Level` access-text reads (`Cf::level_field_vec3`/
    // `level_field_scalar` — `m2_levels[L].…`, the struct layout NOT modeled). The `[unroll]` loop
    // reuses `Cf::runtime_for` (attr `[unroll]`, the bound SYMBOL `BRICK_LEVELS`). Like the other
    // refine spans it is a SPAN, not a whole function: the hand-written `int select_level(float3 p)
    // {` signature + the closing `}` stay un-generated (framing b), so this is a `.contains` of the
    // emitted span (spliced between the GENERATED select_level sentinels), not an extract_fn. A
    // hand-edit of the committed span fails CI here. The cmp-.spv proves the spliced text re-DXCs
    // byte-identical to the committed `.comp.spv`.
    let generated = boyko_shaderdsl::emit::emit_hlsl_select_level().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `select_level` scan span DRIFTED from boyko_shaderdsl::emit — \
         the committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED select_level \
         sentinels (the `int select_level(float3 p) {{` signature + the closing `}}` stay \
         hand-written).\n--- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn m2_brick_span_matches_edsl_emit() {
    // The M2 brick-AABB ray-span clip body (Inc 5b — the first COMPUTED-bool-returning leaf: the
    // standard slab-method clip of the ray `p + rd·t` to ONE brick's `[cell_min, cell_min +
    // brick_world]` AABB, returning the `[t_enter, t_exit]` span through two `out float` params + a
    // COMPUTED `bool` (`return tmax > tmin;` via `Cf::ret_b_expr` — a Mask operand, vs the
    // `bool`-literal `Cf::ret_b`)) is GENERATED by boyko_shaderdsl::emit::emit_hlsl_m2_brick_span().
    // The three new facets: the COMPUTED-bool return, the TWO `out float` params (`t_enter`/`t_exit`,
    // both `Cf::out_float_assign`), and the FALL-THROUGH swap `if (t1 > t2) { ... }` (a `Cf::if_`
    // whose body returns `Flow::Continue(())`). The `[unroll]` axis loop reuses `Cf::runtime_for`
    // (attr `[unroll]`, the LITERAL bound `3u`) so the in-loop parallel-slab early `return false`
    // FORWARDS through it to the function IIFE. Like the other refine spans it is a BODY span, not a
    // whole function: the hand-written `bool m2_brick_span(...) {` signature + the closing `}` stay
    // un-generated (framing b), so this is a `.contains` of the emitted span (spliced between the
    // GENERATED m2_brick_span sentinels), not an extract_fn. A hand-edit of the committed body fails
    // CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical to the committed
    // `.comp.spv` (the dropped in-body comments + the single→multi-line splits are token-neutral).
    let generated = boyko_shaderdsl::emit::emit_hlsl_m2_brick_span().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `m2_brick_span` body span DRIFTED from boyko_shaderdsl::emit — \
         the committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED m2_brick_span \
         sentinels (the `bool m2_brick_span(...) {{` signature + the closing `}}` stay \
         hand-written).\n--- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn m2_brick_cubic_hit_matches_edsl_emit() {
    // The M2 brick 3D-DDA cubic-hit MARCHER body (Inc 5c — the LARGEST + FINAL brick called body: the
    // `[unroll]` per-axis DDA setup, the `[loop]` 3D-DDA march with the cell clamp, the 8 `m2_corner`
    // fetches, the cubic form+solve, the in-cell early `return seg_lo + local_t;`, the nearest-axis
    // nested-select advance, the `cell[axis] += step[axis]` `+=` step, and the DDA-exit guard) is
    // GENERATED by boyko_shaderdsl::emit::emit_hlsl_m2_brick_cubic_hit(). The four new FACET GROUPS:
    // (1) named local arrays (`int cell[3]`/`float s[8]` + the per-element get/set/`+=` — the `+=` a
    // DISTINCT statement per the R1 spike), (2) generalized heterogeneous call sites (`m2_corner` with
    // RESOURCE params, `m2_jcgt_cubic_coeffs(s,...)` with a by-name array arg, `m2_marmitt_root`,
    // `(int)m2_clamp_index(...)`), (3) int casts/arith (`(uint)max(...)`, `(float)(c0 + 1)`, `W - 2u`,
    // `step[axis] == 0`, `cell[axis] < 0`), and (4) misc (the nested `uint` axis-select, the dynamic
    // `rd_v[axis]` index, the `float3(...)` scalar ctor, the captured `uint W`). EMIT-ONLY: `m2_corner`
    // → `atlas.SampleLevel` cannot run on the CPU, so the body is never instantiated over `EvalCf` and
    // there is NO eval sweep — the cmp-`.spv` is the SOLE byte-identity oracle. Like the other refine
    // spans it is a BODY span, not a whole function: the hand-written signature, the `t_exit <=
    // t_enter` early-out, the `const uint W = M2_BRICK_ALLOC;` decl, and the closing `}` stay
    // un-generated (framing b), so this is a `.contains` of the emitted span (spliced between the
    // GENERATED m2_brick_cubic_hit sentinels), not an extract_fn. A hand-edit of the committed body
    // fails CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical to the committed
    // `.comp.spv` (the `else if`→`else { if }` reflow, the single-line `lo_g` ctor, and the dropped
    // in-body comments are all token-neutral).
    let generated = boyko_shaderdsl::emit::emit_hlsl_m2_brick_cubic_hit().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `m2_brick_cubic_hit` body span DRIFTED from boyko_shaderdsl::emit \
         — the committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED m2_brick_cubic_hit \
         sentinels (the signature, the `t_exit <= t_enter` early-out, the `const uint W` decl, and the \
         closing `}}` stay hand-written).\n--- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn pack_material_id_ba_matches_edsl_emit() {
    // The G-buffer MATERIAL-ID PACKER body (Track B Increment G1 — the FIRST `float2`-returning leaf,
    // landing the minimal `float2` axis + the bitwise `uint` `&`/`>>`): the 16-bit `uint id` →
    // low/high-byte split (`id & 255u` / `id >> 8u & 255u`) → `float2` UNORM pair
    // (`float2((float)lo / 255.0, (float)hi / 255.0)`) is GENERATED by
    // boyko_shaderdsl::emit::emit_hlsl_pack_material_id_ba(). The two new facets: the `float2` return
    // (`Cf::ret_vec2` + `Cf::vec2_from_scalars` — the `EmitTy::Float2` + `Node::Vec2FromScalars` axis)
    // and the bitwise `uint` `&`/`>>` (`Cf::and_u` / `Cf::shr_u` — the two DEAD `Node::And`/`Node::Shr`
    // nodes' methods, whose printer arms already existed). Like the other refine spans it is a BODY
    // span, not a whole function: the hand-written `float2 pack_material_id_ba(uint id) {` signature +
    // the closing `}` stay un-generated (framing b), so this is a `.contains` of the emitted span
    // (spliced between the GENERATED pack_material_id_ba sentinels), not an extract_fn. The committed
    // `0xFFu` / `(id >> 8) & 0xFFu` was re-spliced to the eDSL spelling `255u` / `id >> 8u & 255u` (the
    // hex→decimal + redundant-parens removal are both DXC byte-neutral, proven). A hand-edit of the
    // committed body fails CI here. The cmp-.spv proves the spliced text re-DXCs byte-identical to the
    // committed `.comp.spv`.
    let generated = boyko_shaderdsl::emit::emit_hlsl_pack_material_id_ba().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `pack_material_id_ba` body span DRIFTED from boyko_shaderdsl::emit \
         — the committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED pack_material_id_ba \
         sentinels (the `float2 pack_material_id_ba(uint id) {{` signature + the closing `}}` stay \
         hand-written).\n--- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn oct_encode_matches_edsl_emit() {
    // The G-buffer OCTAHEDRAL-NORMAL ENCODER body (Track B Increment G2 — the LAST G-buffer leaf,
    // landing the mutable `float3`/`float2` locals + the `float2` component ops): the unit normal `n` →
    // octahedral `[0,1]^2` fold (`n = n / (...)`, `float2 e = n.xy;`, the `if (n.z < 0.0)` lower-
    // hemisphere fold with the two `e.x >= 0.0 ? 1.0 : -1.0` sign-ternaries, the fused `return e * 0.5
    // + 0.5;`) is GENERATED by boyko_shaderdsl::emit::emit_hlsl_oct_encode(). The new facets: the
    // mutable `float3` SUPPRESSED-DECL param `n` (`Cf::decl_param_vec3` — the `n = n / ...;` R1 whole-
    // variable form), the mutable `float2` local `e` (`Cf::decl_var_vec2`), the REAL fall-through `if_`
    // (the `n.z < 0.0` branch — an OpBranchConditional+merge, NOT a branchless OpSelect), the bare
    // sign-ternaries (`Cf::select_bare` — un-parenthesized, DISTINCT from `Cf::select`'s wrapped form),
    // and the `float2` component ops (`Cf::vec3_xy`/`vec2_yx`/`vec2_x`/`vec2_y` swizzles + `vec2_abs`/
    // `vec2_mul`/`vec2_mul_scalar`/`vec2_add_scalar`/`vec2_rsub_scalar`). Like the other refine spans it
    // is a BODY span, not a whole function: the hand-written `float2 oct_encode(float3 n) {` signature +
    // the closing `}` stay un-generated (framing b), so this is a `.contains` of the emitted span
    // (spliced between the GENERATED oct_encode sentinels), not an extract_fn. The committed `n /= (...)`
    // was re-spliced to the eDSL spelling `n = n / (...)` (the `/=` → `= /` whole-variable form is DXC
    // byte-neutral, proven by the R1 spike). A hand-edit of the committed body fails CI here. The
    // cmp-.spv proves the spliced text re-DXCs byte-identical to the committed `.comp.spv`.
    let generated = boyko_shaderdsl::emit::emit_hlsl_oct_encode().replace("\r\n", "\n");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_gbuffer_composite.hlsl `oct_encode` body span DRIFTED from boyko_shaderdsl::emit \
         — the committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between the GENERATED oct_encode \
         sentinels (the `float2 oct_encode(float3 n) {{` signature + the closing `}}` stay \
         hand-written).\n--- expected (eDSL-generated) ---\n{generated}"
    );
}
