//! eDSL <-> HLSL SINGLE-SOURCE GUARD.
//!
//! `shaders/sdf_field.hlsli`'s `smin` / `smax` bodies are MACHINE-GENERATED by
//! `boyko_shaderdsl::emit` — the eDSL whose `Eval` backend (`impl FieldScalar for
//! f32`) IS the host field `boyko_sdf_math::sdf_edit_list`. Both the host (Eval) and
//! the generated HLSL (Emit) instantiate the SAME generic `boyko_shaderdsl::field`
//! body, so they cannot diverge BY CONSTRUCTION — UNLESS someone hand-edits the
//! spliced `smin`/`smax` in the header without re-emitting, which would silently
//! diverge the GPU field from the host field: exactly the by-hand drift (black
//! surfaces, AO craters) the eDSL was built to kill.
//!
//! This test re-runs the generator and asserts the committed header still contains
//! the EXACT generated `smin`/`smax` bodies, so that drift fails CI loudly. The fix
//! when it trips: re-run
//!     cargo run -p boyko_shaderdsl --features emit --bin emit_field
//! and re-splice the `smin`/`smax` bodies between the `// === GENERATED FIELD MATH
//! BEGIN/END ===` sentinels in `shaders/sdf_field.hlsli`.
//!
//! Scope: `smin`/`smax` only — `combine` is intentionally NOT eDSL-generated (its
//! lazy `(k>0)?smooth:hard` ternary lowers to `OpBranchConditional`/`OpPhi`, which
//! the eager `OpSelect` the `Emit` backend produces would fork; `combine` carries no
//! polynomial field math, only calls to the generated `smin`/`smax`). The Eval-side
//! byte-identity (Eval == the frozen host snapshot) is proven separately by
//! `boyko_shaderdsl`'s `eval_byte_identity` suite.

/// Extracts a `float NAME(...) { ... }` function — the signature line through the
/// closing brace on its own line — out of generated HLSL. The generated bodies end
/// each function with `    return tN;\n}` (a `}` alone on the next line), so the
/// first `\n}` after the signature is the function's close.
fn extract_fn(src: &str, sig: &str) -> String {
    let start = src
        .find(sig)
        .unwrap_or_else(|| panic!("emit_hlsl_field() output is missing `{sig}`"));
    let after = &src[start..];
    let close = after
        .find("\n}")
        .expect("a generated function body must close with `}` on its own line");
    after[..close + 2].to_string()
}

#[test]
fn sdf_field_smin_smax_match_edsl_emit() {
    // Generate the HLSL field bodies from the eDSL (LF-normalized).
    let generated = boyko_shaderdsl::emit::emit_hlsl_field().replace("\r\n", "\n");
    let smin = extract_fn(&generated, "float smin(float a, float b, float k) {");
    let smax = extract_fn(&generated, "float smax(float a, float b, float k) {");

    // Read the committed header (LF-normalized so a CRLF checkout does not spuriously
    // mismatch the LF generator output).
    let header_path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/sdf_field.hlsli");
    let header = std::fs::read_to_string(header_path)
        .expect("invariant: shaders/sdf_field.hlsli must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        header.contains(&smin),
        "sdf_field.hlsli `smin` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the smin body between the GENERATED sentinels.\n\
         --- expected (eDSL-generated) ---\n{smin}"
    );
    assert!(
        header.contains(&smax),
        "sdf_field.hlsli `smax` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run the emit_field bin and re-splice the smax body \
         between the GENERATED sentinels.\n\
         --- expected (eDSL-generated) ---\n{smax}"
    );
}

#[test]
fn sdf_normal_matches_edsl_emit() {
    // The GPU surface-normal leaf `sdf_normal` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_normal()` (A1) from the SAME source whose `f32`
    // Eval backend is byte-identical to the host `boyko_sdf_math::sdf_edit_list_normal`.
    // A hand-edit of the committed body (which would silently diverge the GPU normal
    // from the host normal — the central-difference shading the AO/lighting reads)
    // fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_normal().replace("\r\n", "\n");
    let sdf_normal = extract_fn(&generated, "float3 sdf_normal(float3 p) {");

    let header_path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/sdf_field.hlsli");
    let header = std::fs::read_to_string(header_path)
        .expect("invariant: shaders/sdf_field.hlsli must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        header.contains(&sdf_normal),
        "sdf_field.hlsli `sdf_normal` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the sdf_normal body between the GENERATED NORMAL \
         sentinels.\n--- expected (eDSL-generated) ---\n{sdf_normal}"
    );
}

#[test]
fn m2_decode_matches_edsl_emit() {
    // The brick snorm decode SCALE leaf `m2_decode` (`n * band_half`) in
    // `sdf_gbuffer_composite.hlsl` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_decode_snorm8()` (A2) from the SAME source whose
    // `f32` Eval backend (the WHOLE `decode_snorm8`: byte → normalize → scale) is
    // byte-identical to the host `boyko_sdf_math::brick::decode_snorm8`. Only the SCALE
    // is shader code (the byte → normalize is the hardware R8_SNORM sampler), so this
    // pins the spliced scale body to the generator. A hand-edit — which would silently
    // diverge the GPU brick decode from the host oracle the trilinear fetch is golden-
    // compared against — fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_decode_snorm8().replace("\r\n", "\n");
    let m2_decode = extract_fn(&generated, "float m2_decode(float n, float band_half) {");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&m2_decode),
        "sdf_gbuffer_composite.hlsl `m2_decode` DRIFTED from boyko_shaderdsl::emit — the committed \
         body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the m2_decode body between the GENERATED decode_snorm8 \
         sentinels.\n--- expected (eDSL-generated) ---\n{m2_decode}"
    );
}

#[test]
fn m2_cubic_eval_matches_edsl_emit() {
    // The M2 cubic Horner leaf `m2_cubic_eval` in `sdf_gbuffer_composite.hlsl` is
    // GENERATED by `boyko_shaderdsl::emit::emit_hlsl_cubic_eval()` (A3) from the SAME
    // source whose `f32` Eval backend is byte-identical to the host
    // `boyko_sdf_math::brick::cubic_eval`. A hand-edit — which would silently drift the
    // GPU cubic eval from the host oracle that feeds the hit-`t` (where hit/miss is a
    // CLIFF, not a tolerance band) — fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_cubic_eval().replace("\r\n", "\n");
    let m2_cubic_eval = extract_fn(&generated, "float m2_cubic_eval(float4 c, float t) {");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&m2_cubic_eval),
        "sdf_gbuffer_composite.hlsl `m2_cubic_eval` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the m2_cubic_eval body between the \
         GENERATED m2_cubic_eval sentinels.\n--- expected (eDSL-generated) ---\n{m2_cubic_eval}"
    );
}

#[test]
fn m2_jcgt_cubic_coeffs_matches_edsl_emit() {
    // The M2 trilinear → cubic-coefficient fold `m2_jcgt_cubic_coeffs` in
    // `sdf_gbuffer_composite.hlsl` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_jcgt_cubic_coeffs()` (A3) from the SAME source
    // whose `f32` Eval backend is byte-identical to the host
    // `boyko_sdf_math::brick::jcgt_cubic_coeffs`. This is the HIGHEST-drift-value leaf
    // (the M2 crease bug lived in the cubic); a hand-edit fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_jcgt_cubic_coeffs().replace("\r\n", "\n");
    let m2_jcgt =
        extract_fn(&generated, "float4 m2_jcgt_cubic_coeffs(float s[8], float3 a, float3 b) {");

    let shader_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/shaders/sdf_gbuffer_composite.hlsl"
    );
    let shader = std::fs::read_to_string(shader_path)
        .expect("invariant: shaders/sdf_gbuffer_composite.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&m2_jcgt),
        "sdf_gbuffer_composite.hlsl `m2_jcgt_cubic_coeffs` DRIFTED from boyko_shaderdsl::emit — the \
         committed body no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice the m2_jcgt_cubic_coeffs body between the \
         GENERATED m2_jcgt_cubic_coeffs sentinels.\n--- expected (eDSL-generated) ---\n{m2_jcgt}"
    );
}
