//! eDSL <-> HLSL SINGLE-SOURCE GUARD.
//!
//! `shaders/sdf_field.hlsli`'s `smin` / `smax` bodies are MACHINE-GENERATED by
//! `boyko_shaderdsl::emit` — the eDSL whose `Eval` backend (`impl FieldScalar for
//! f32`) IS the host field `boyko_sdf_math::sdf_edit_list`. Both the host (Eval) and
//! the generated HLSL (Emit) instantiate the SAME generic `boyko_shaderdsl::field`
//! body, so they cannot diverge BY CONSTRUCTION — UNLESS someone hand-edits the
//! spliced `smin`/`smax` in the header without re-emitting, which would silently
//! diverge the GPU field from the host field: exactly the by-hand drift (black
//! surfaces, AO craters) the eDSL was built to kill.
//!
//! This test re-runs the generator and asserts the committed header still contains
//! the EXACT generated `smin`/`smax` bodies, so that drift fails CI loudly. The fix
//! when it trips: re-run
//!     cargo run -p boyko_shaderdsl --features emit --bin emit_field
//! and re-splice the `smin`/`smax` bodies between the `// === GENERATED FIELD MATH
//! BEGIN/END ===` sentinels in `shaders/sdf_field.hlsli`.
//!
//! Scope: `smin`/`smax` only — `combine` is intentionally NOT eDSL-generated (its
//! lazy `(k>0)?smooth:hard` ternary lowers to `OpBranchConditional`/`OpPhi`, which
//! the eager `OpSelect` the `Emit` backend produces would fork; `combine` carries no
//! polynomial field math, only calls to the generated `smin`/`smax`). The Eval-side
//! byte-identity (Eval == the frozen host snapshot) is proven separately by
//! `boyko_shaderdsl`'s `eval_byte_identity` suite.

/// Extracts a `float NAME(...) { ... }` function — the signature line through the
/// closing brace on its own line — out of generated HLSL. The generated bodies end
/// each function with `    return tN;\n}` (a `}` alone on the next line), so the
/// first `\n}` after the signature is the function's close.
fn extract_fn(src: &str, sig: &str) -> String {
    let start = src
        .find(sig)
        .unwrap_or_else(|| panic!("emit_hlsl_field() output is missing `{sig}`"));
    let after = &src[start..];
    let close = after
        .find("\n}")
        .expect("a generated function body must close with `}` on its own line");
    after[..close + 2].to_string()
}

#[test]
fn sdf_field_smin_smax_match_edsl_emit() {
    // Generate the HLSL field bodies from the eDSL (LF-normalized).
    let generated = boyko_shaderdsl::emit::emit_hlsl_field().replace("\r\n", "\n");
    let smin = extract_fn(&generated, "float smin(float a, float b, float k) {");
    let smax = extract_fn(&generated, "float smax(float a, float b, float k) {");

    // Read the committed header (LF-normalized so a CRLF checkout does not spuriously
    // mismatch the LF generator output).
    let header_path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/sdf_field.hlsli");
    let header = std::fs::read_to_string(header_path)
        .expect("invariant: shaders/sdf_field.hlsli must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        header.contains(&smin),
        "sdf_field.hlsli `smin` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the smin body between the GENERATED sentinels.\n\
         --- expected (eDSL-generated) ---\n{smin}"
    );
    assert!(
        header.contains(&smax),
        "sdf_field.hlsli `smax` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run the emit_field bin and re-splice the smax body \
         between the GENERATED sentinels.\n\
         --- expected (eDSL-generated) ---\n{smax}"
    );
}

#[test]
fn sdf_normal_matches_edsl_emit() {
    // The GPU surface-normal leaf `sdf_normal` is GENERATED by
    // `boyko_shaderdsl::emit::emit_hlsl_normal()` (A1) from the SAME source whose `f32`
    // Eval backend is byte-identical to the host `boyko_sdf_math::sdf_edit_list_normal`.
    // A hand-edit of the committed body (which would silently diverge the GPU normal
    // from the host normal — the central-difference shading the AO/lighting reads)
    // fails CI here.
    let generated = boyko_shaderdsl::emit::emit_hlsl_normal().replace("\r\n", "\n");
    let sdf_normal = extract_fn(&generated, "float3 sdf_normal(float3 p) {");

    let header_path = concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/sdf_field.hlsli");
    let header = std::fs::read_to_string(header_path)
        .expect("invariant: shaders/sdf_field.hlsli must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        header.contains(&sdf_normal),
        "sdf_field.hlsli `sdf_normal` DRIFTED from boyko_shaderdsl::emit — the committed body no \
         longer matches the generator. Re-run `cargo run -p boyko_shaderdsl --features emit \
         --bin emit_field` and re-splice the sdf_normal body between the GENERATED NORMAL \
         sentinels.\n--- expected (eDSL-generated) ---\n{sdf_normal}"
    );
}
