//! eDSL <-> HLSL SINGLE-SOURCE GUARD for the Render P7 GROUP A SSAO shader.
//!
//! `shaders/sdf_ssao.comp.hlsl`'s horizon-step span (`delta = P' - P`, the squared-
//! distance `falloff` range gate, the `elev = max(dot(delta,N) / max(length(delta),
//! SSAO_EPS), 0)` elevation above the tangent plane, and the `hc = max(hc, elev * falloff)`
//! running horizon max) is MACHINE-GENERATED by `boyko_shaderdsl::emit::emit_hlsl_ssao()` — the eDSL whose
//! `<EvalCf>` instantiation (`boyko_shaderdsl::ssao::ssao_estimate_body`) is the host AO
//! oracle the golden gather calls. Both the host (Eval) and the generated HLSL (Emit)
//! instantiate the SAME generic horizon-step body, so they cannot diverge BY CONSTRUCTION
//! — UNLESS someone hand-edits the spliced span without re-emitting (the by-hand drift the
//! eDSL kills).
//!
//! Render P7-Q2 (Mechanism C) added the PRE-COMPILED SSAO quality variants
//! (`sdf_ssao_{low,medium,high}.comp.{hlsl,spv}`): one `.spv` per `boyko_shaderdsl::ssao::
//! SSAO_PRESETS` row, each BAKING that preset's `static const` tuning so every `[unroll]`
//! slice/step loop stays fully unrolled (the host selects a variant by binding its pipeline,
//! ZERO per-pixel runtime cost). The eDSL-generated horizon-step span is VARIANT-INDEPENDENT
//! (it spells `SSAO_RADIUS`/`SSAO_EPS` symbolically; the loop bounds are hand-written glue),
//! so the SAME span appears in the base + every variant, and only the `static const` header
//! differs between them.
//!
//! This file is the SSAO drift gate. Two file/byte tests (both now ITERATE the base + 3
//! variants) + two host-mirror tests:
//!   1. `ssao_horizon_step_matches_edsl_emit` — the `.contains` drift gate PER shader file
//!      (base + 3 variants): assert each still contains the EXACT generated span. The fix
//!      when it trips: re-run `cargo run -p boyko_shaderdsl --features emit --bin
//!      emit_ssao_variants` (the variants) and, for the base, re-splice between the `// ===
//!      GENERATED ssao_horizon_step BEGIN/END ===` sentinels (BOTH the `+dir` and `-dir`
//!      half-slice copies); then re-DXC the affected `.spv`.
//!   2. `ssao_spv_byte_identical` — the per-variant re-DXC byte-identity gate: for each
//!      variant, re-emit its `.hlsl` from the base (`ssao::variant_hlsl`), re-DXC with the
//!      EXACT recipe (`dxc -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3`, NO `-O`), and
//!      assert the bytes equal the committed variant `.spv`. The keystone no-op proof: the
//!      MEDIUM variant (== today's shipped consts) is byte-identical to the committed base
//!      `sdf_ssao.comp.{hlsl,spv}`. SKIPS (does not fail) when DXC is not on this host — the
//!      byte-identity claim cannot be evaluated without the compiler, and a missing SDK is an
//!      environment gap, not a shader regression.

use std::path::PathBuf;
use std::process::Command;

use boyko_shaderdsl::cf::EvalCf;
use boyko_shaderdsl::ssao::{self, SsaoQuality};

/// The shaders directory (`CARGO_MANIFEST_DIR/shaders`), where the committed `.hlsl` and
/// `.spv` live (and where DXC must run so its `#include "ray_gen.hlsli"` resolves).
fn shaders_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("shaders")
}

/// Locates the `dxc` executable: first the pinned Vulkan-SDK path (the repo's offline
/// recipe), then `$VULKAN_SDK/Bin`, then `PATH`. Returns `None` if none resolve (the
/// byte-identity test then SKIPS).
fn find_dxc() -> Option<PathBuf> {
    // The repo's pinned offline DXC (the recipe in every eDSL-generated shader's header).
    let pinned = PathBuf::from("C:/VulkanSDK/1.4.350.0/Bin/dxc.exe");
    if pinned.exists() {
        return Some(pinned);
    }
    // `$VULKAN_SDK/Bin/dxc`.
    let bare = if cfg!(windows) { "dxc.exe" } else { "dxc" };
    if let Ok(sdk) = std::env::var("VULKAN_SDK") {
        let candidate = PathBuf::from(sdk).join("Bin").join(bare);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    // A PATH-resolvable `dxc`.
    if Command::new(bare).arg("--version").output().is_ok() {
        return Some(PathBuf::from(bare));
    }
    None
}

#[test]
fn ssao_horizon_step_matches_edsl_emit() {
    // The SSAO horizon-step span (Render P7 GROUP A — HBAO-lite, no-trig: ONE forward
    // horizon tap's math) is GENERATED by `boyko_shaderdsl::emit::emit_hlsl_ssao()` from the
    // SAME source whose `<EvalCf>` instantiation (`ssao::ssao_estimate_body`) is the host AO
    // oracle. It is a SPAN, not a whole function: the forward neighbour reconstruct, the
    // `[unroll]` slice/step loops, the rotation-table direction, and the `occ → ao` fold stay
    // hand-written (framing b), so this is a `.contains` of the emitted span (spliced between
    // the GENERATED ssao_horizon_step sentinels — TWICE, the +dir and -dir half-slices), not
    // an extract_fn. A hand-edit of the committed span fails CI here.
    //
    // Render P7-Q2 (Mechanism C): the span is VARIANT-INDEPENDENT — it spells `SSAO_RADIUS`/
    // `SSAO_EPS` SYMBOLICALLY (the per-preset `static const` header carries the values), and
    // references neither slices nor steps (those are the hand-written `[unroll]` bounds). So
    // the SAME generated span must appear in the base `sdf_ssao.comp.hlsl` AND in every
    // pre-compiled variant `sdf_ssao_<quality>.comp.hlsl`. This loop pins one drift gate PER
    // shader file (the base + the 3 variants).
    //
    // ZERO new eDSL leaves: `dot` is inline component-reads + mul/add, `length =
    // sqrt(dot(d,d))`, the `ao*ao` power an integer self-mul — so the frozen marcher/field/
    // shadow/brick/resolve `.spv` cannot fork (proven by the existing `*_edsl_sync` suite,
    // which stays green).
    let generated = boyko_shaderdsl::emit::emit_hlsl_ssao().replace("\r\n", "\n");

    // The base shader + the 3 pre-compiled quality variants all carry the SAME span.
    let mut shader_files: Vec<String> = vec!["sdf_ssao.comp.hlsl".to_string()];
    shader_files.extend(
        SsaoQuality::ALL
            .iter()
            .map(|q| format!("sdf_ssao_{}.comp.hlsl", q.suffix())),
    );

    for file in &shader_files {
        let shader_path = shaders_dir().join(file);
        let shader = std::fs::read_to_string(&shader_path)
            .unwrap_or_else(|e| {
                panic!("invariant: shaders/{file} must exist next to this crate: {e}")
            })
            .replace("\r\n", "\n");

        assert!(
            shader.contains(&generated),
            "{file} `ssao_horizon_step` span DRIFTED from boyko_shaderdsl::emit — the \
             committed span no longer matches the generator. Re-run `cargo run -p \
             boyko_shaderdsl --features emit --bin emit_ssao_variants` (and re-splice the base \
             between BOTH GENERATED ssao_horizon_step sentinel pairs if it is the base), then \
             re-DXC the variant `.spv`. The span is variant-independent (it spells \
             SSAO_RADIUS/SSAO_EPS symbolically), so it must be IDENTICAL in every variant.\n\
             --- expected (eDSL-generated) ---\n{generated}"
        );
    }
}

/// Re-DXCs `hlsl_name` (relative to the shaders dir, so its `#include "ray_gen.hlsli"`
/// resolves) under the EXACT frozen recipe (`-spirv -T cs_6_0 -E main
/// -fspv-target-env=vulkan1.3`, NO `-O`) into a fresh temp `.spv`, and returns the bytes.
/// Never overwrites a committed artifact.
fn redxc_to_bytes(dxc: &PathBuf, dir: &PathBuf, hlsl_name: &str) -> Vec<u8> {
    let out_spv = std::env::temp_dir().join(format!("{hlsl_name}.redxc.spv"));
    let status = Command::new(dxc)
        .current_dir(dir)
        .args([
            "-spirv",
            "-T",
            "cs_6_0",
            "-E",
            "main",
            "-fspv-target-env=vulkan1.3",
            hlsl_name,
            "-Fo",
        ])
        .arg(&out_spv)
        .status()
        .expect("invariant: dxc was located and must run");
    assert!(
        status.success(),
        "dxc failed re-compiling {hlsl_name} under the frozen recipe"
    );
    let bytes = std::fs::read(&out_spv).expect("invariant: dxc wrote the re-DXC .spv");
    let _ = std::fs::remove_file(&out_spv); // best-effort tidy
    bytes
}

#[test]
fn ssao_spv_byte_identical() {
    // Render P7-Q2 (Mechanism C) per-variant byte-identity loop. Each pre-compiled SSAO
    // quality variant (`sdf_ssao_<quality>.comp.spv`) the engine loads must be the EXACT
    // re-DXC of its committed `.hlsl` under the frozen recipe — the byte-identity oracle that
    // the shipped variant `.spv` IS the single-sourced text, not a stale or hand-tweaked blob.
    //
    // Each variant `.hlsl` is itself re-derived from the base `sdf_ssao.comp.hlsl` by swapping
    // ONLY the `static const SSAO_*` tuning header (`ssao::variant_hlsl` — the same transform
    // the `emit_ssao_variants` bin runs), so this also pins the committed variant `.hlsl` to
    // its single source: the eDSL-generated span + the hand-written glue, with one baked preset.
    //
    // The keystone no-op proof: the MEDIUM variant (`SSAO_PRESETS[1]` == today's shipped
    // consts) must be byte-identical to (a) a fresh re-DXC of its own `.hlsl` (the per-variant
    // gate below, shared with Low/High) and (b) the committed base `sdf_ssao.comp.hlsl`. The
    // pre-Q2 redundant base `sdf_ssao.comp.spv` was RETIRED (the Medium variant `.spv` replaces it
    // as the byte-identity authority — the engine loads the per-variant `.spv`, not the base);
    // the byte-identity claim is now self-contained PER VARIANT (each variant's `.spv` == its own
    // re-DXC), so the base `.hlsl` (the single-source glue template) is all the base contributes.
    let Some(dxc) = find_dxc() else {
        eprintln!(
            "ssao_edsl_sync: dxc not found (no C:/VulkanSDK/.../dxc.exe, no $VULKAN_SDK/Bin, \
             not on PATH) — SKIPPING the SSAO per-variant re-DXC byte-identity check on this host."
        );
        return;
    };

    let dir = shaders_dir();

    // The single source of the variant glue body: the base shader text.
    let base_hlsl_path = dir.join("sdf_ssao.comp.hlsl");
    let base_hlsl = std::fs::read_to_string(&base_hlsl_path).unwrap_or_else(|e| {
        panic!(
            "missing committed base SSAO HLSL {}: {e}",
            base_hlsl_path.display()
        )
    });
    for quality in SsaoQuality::ALL {
        let stem = format!("sdf_ssao_{}.comp", quality.suffix());
        let hlsl_name = format!("{stem}.hlsl");
        let committed_hlsl_path = dir.join(&hlsl_name);
        let committed_spv_path = dir.join(format!("{stem}.spv"));

        // (1) The committed variant `.hlsl` must equal a fresh re-emit from the base
        //     (`variant_hlsl(base, preset)`) — the single-source `.hlsl` drift gate. Compare
        //     line-ending-normalized so a CRLF checkout does not false-fail.
        let committed_hlsl = std::fs::read_to_string(&committed_hlsl_path)
            .unwrap_or_else(|e| {
                panic!(
                    "missing committed variant HLSL {}: {e} (run `cargo run -p boyko_shaderdsl \
                     --features emit --bin emit_ssao_variants`)",
                    committed_hlsl_path.display()
                )
            })
            .replace("\r\n", "\n");
        let reemitted = ssao::variant_hlsl(&base_hlsl, quality.params()).replace("\r\n", "\n");
        assert_eq!(
            committed_hlsl, reemitted,
            "{hlsl_name} DRIFTED from a fresh `variant_hlsl(base, SSAO_PRESETS[{}])` re-emit — \
             the committed variant `.hlsl` is NOT the single-sourced text. Re-run \
             `cargo run -p boyko_shaderdsl --features emit --bin emit_ssao_variants`.",
            quality as usize
        );

        // (2) The MEDIUM `.hlsl` must equal the base `.hlsl` byte-for-byte (the no-op proof,
        //     `.hlsl` level): Medium bakes today's exact consts, so it is the base unchanged.
        if quality == SsaoQuality::Medium {
            assert_eq!(
                committed_hlsl,
                base_hlsl.replace("\r\n", "\n"),
                "MEDIUM variant `.hlsl` is NOT byte-identical to the base sdf_ssao.comp.hlsl — \
                 the Medium preset must equal today's shipped consts (the no-op proof). STOP \
                 and audit `SSAO_PRESETS[1]` / `ssao_glue_header`."
            );
        }

        // (3) The committed variant `.spv` must equal a fresh re-DXC of the variant `.hlsl`.
        let committed_spv = std::fs::read(&committed_spv_path).unwrap_or_else(|e| {
            panic!(
                "missing committed variant SPIR-V {}: {e} (DXC the variant with the frozen \
                 recipe and commit it)",
                committed_spv_path.display()
            )
        });
        let regenerated = redxc_to_bytes(&dxc, &dir, &hlsl_name);
        assert_eq!(
            regenerated,
            committed_spv,
            "{stem}.spv BYTE-DRIFTED from a fresh re-DXC of {hlsl_name} — the committed variant \
             .spv the engine loads is NOT the single-sourced text. Re-DXC with the frozen \
             recipe and re-commit. (regenerated = {} bytes, committed = {} bytes)",
            regenerated.len(),
            committed_spv.len()
        );

        // (4) The MEDIUM no-op proof, `.spv` level: the Medium variant `.spv` must be the EXACT
        //     re-DXC of the MEDIUM `.hlsl`, which (per step (2)) is byte-identical to the base
        //     `.hlsl`. Step (3) above already asserted `committed_spv == regenerated` for Medium,
        //     and `regenerated` is the re-DXC of a `.hlsl` proven equal to the base `.hlsl` — so
        //     `committed_spv` IS "today's pipeline end-to-end through DXC" from the base text. The
        //     pre-Q2 base `sdf_ssao.comp.spv` was retired, so there is no separate base blob to
        //     diff; the per-variant re-DXC + the `.hlsl`-equals-base proof carry the no-op claim.
        if quality == SsaoQuality::Medium {
            assert_eq!(
                committed_hlsl,
                base_hlsl.replace("\r\n", "\n"),
                "MEDIUM variant `.hlsl` must equal the base `.hlsl` for the `.spv`-level no-op \
                 proof to hold (its re-DXC at step (3) is the committed `.spv`). STOP and audit \
                 the parameterization."
            );
        }
    }
}

/// Re-DXCs `hlsl_name` (relative to the shaders dir) under the EXACT frozen recipe
/// (`-spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3`, NO `-O`) plus the given `-D`
/// defines, into a fresh temp `.spv` named by `out_tag` (distinct per variant so parallel
/// test binaries never collide), and returns the bytes. Never overwrites a committed
/// artifact. Mirrors [`redxc_to_bytes`] (which stays untouched — every existing call site and
/// assertion is unaffected) with the `marcher_spv_sync.rs::redxc_with_defines` shape, for the
/// `-D VB_THIN=1` re-DXC below.
fn redxc_with_defines(
    dxc: &PathBuf,
    dir: &PathBuf,
    hlsl_name: &str,
    defines: &[&str],
    out_tag: &str,
) -> Vec<u8> {
    let out_spv = std::env::temp_dir().join(format!("{out_tag}.redxc.spv"));
    let mut cmd = Command::new(dxc);
    cmd.current_dir(dir).args(["-spirv", "-T", "cs_6_0", "-E", "main"]);
    for d in defines {
        cmd.args(["-D", d]);
    }
    cmd.args(["-fspv-target-env=vulkan1.3", hlsl_name, "-Fo"]).arg(&out_spv);
    let status = cmd.status().expect("invariant: dxc was located and must run");
    assert!(
        status.success(),
        "dxc failed re-compiling {hlsl_name} {defines:?} under the frozen recipe"
    );
    let bytes = std::fs::read(&out_spv).expect("invariant: dxc wrote the re-DXC .spv");
    let _ = std::fs::remove_file(&out_spv); // best-effort tidy
    bytes
}

#[test]
fn ssao_vb_thin_spv_byte_identical() {
    // R9-VB-SPLIT-PLAN.md §5 (R9b): the `-D VB_THIN=1` SSAO-gather variant for the
    // VisibilityBuffer geo/shade split. Each `sdf_ssao_vb_<quality>.comp.spv` is compiled from
    // the SAME per-quality `.hlsl` [`ssao_spv_byte_identical`] already proves is single-sourced
    // from the base (`variant_hlsl(base, preset)`) — NO separate VB `.hlsl` file exists, only
    // the additional `-D VB_THIN=1` define. This loop is the byte-identity oracle for the 3 VB
    // `.spv` blobs: a fresh re-DXC of the committed (non-VB) variant `.hlsl` under `VB_THIN=1`
    // must equal the committed VB `.spv`. SKIPS (does not fail) when DXC is not on this host,
    // matching [`ssao_spv_byte_identical`]'s policy.
    let Some(dxc) = find_dxc() else {
        eprintln!(
            "ssao_edsl_sync: dxc not found (no C:/VulkanSDK/.../dxc.exe, no $VULKAN_SDK/Bin, \
             not on PATH) — SKIPPING the SSAO VB_THIN re-DXC byte-identity check on this host."
        );
        return;
    };
    let dir = shaders_dir();

    for quality in SsaoQuality::ALL {
        let hlsl_name = format!("sdf_ssao_{}.comp.hlsl", quality.suffix());
        let spv_name = format!("sdf_ssao_vb_{}.comp.spv", quality.suffix());
        let committed_spv_path = dir.join(&spv_name);

        let committed_spv = std::fs::read(&committed_spv_path).unwrap_or_else(|e| {
            panic!(
                "missing committed VB SSAO SPIR-V {}: {e}\n\
                 Compile it with (cwd = crates/boyko_rhi_vulkan/shaders, so the relative \
                 `#include \"ray_gen.hlsli\"` resolves):\n  \
                 C:\\VulkanSDK\\1.4.350.0\\Bin\\dxc.exe -spirv -T cs_6_0 -E main -D VB_THIN=1 \
                 -fspv-target-env=vulkan1.3 {hlsl_name} -Fo {spv_name}\n\
                 then commit the .spv next to the existing `sdf_ssao_{}.comp.spv`.",
                committed_spv_path.display(),
                quality.suffix(),
            )
        });
        let regenerated = redxc_with_defines(&dxc, &dir, &hlsl_name, &["VB_THIN=1"], &spv_name);
        assert_eq!(
            regenerated,
            committed_spv,
            "{spv_name} BYTE-DRIFTED from a fresh `-D VB_THIN=1` re-DXC of {hlsl_name} — the \
             committed VB SSAO .spv the engine loads is NOT the single-sourced text. Re-DXC \
             with `-D VB_THIN=1` under the frozen recipe and re-commit. (regenerated = {} bytes, \
             committed = {} bytes)",
            regenerated.len(),
            committed_spv.len()
        );
    }
}

#[test]
fn ssao_horizon_step_host_matches_edsl_eval() {
    // Render P7 GROUP B drift gate: the SHIPPED backend (`boyko_rhi_vulkan::compute`) re-derives
    // the SSAO per-tap horizon as PLAIN RUST (`compute::ssao_horizon_step`), because
    // `boyko_shaderdsl` is a DEV-dependency only — the lib must not link the eDSL. This test
    // (which HAS the dev-dep) is the single-source guard: it asserts the plain-Rust per-tap
    // horizon is BIT-EQUAL to the eDSL `<EvalCf>` Eval body
    // (`boyko_shaderdsl::ssao::ssao_horizon_step_body`) the GENERATED HLSL span is also traced
    // from — so the host oracle the pixel goldens trust cannot silently drift from the shader.
    //
    // The eDSL body order is `(p, pp, n, hc)`; the host re-derive's is `(hc, p, pp, n)` (the
    // running accumulator first, the established `host_ao`/`host_soft_shadow` shape). Both
    // compute the SAME `hc' = max(hc, max(dot(delta,N)/|delta|, 0) * falloff)` over the SAME
    // `f32` arithmetic. The third vector is now the CENTER SURFACE NORMAL `N`, not the screen
    // slice direction.
    let cases: [([f32; 3], [f32; 3], [f32; 3]); 6] = [
        // A neighbour rising above the tangent along +N within radius (a crevice tap): a
        // strong positive elevation.
        ([0.0, 0.0, 0.0], [0.0, 0.0, 0.12], [0.0, 0.0, 1.0]),
        // A neighbour IN the tangent plane (delta perpendicular to N): zero elevation.
        ([0.0, 0.0, 0.0], [0.1, 0.0, 0.0], [0.0, 0.0, 1.0]),
        // A neighbour BEYOND radius (open): falloff zeroes it.
        ([0.0, 0.0, 0.0], [0.0, 0.0, 0.9], [0.0, 0.0, 1.0]),
        // A degenerate Pp == P (a skipped seam tap): the SSAO_EPS guard, no NaN.
        ([1.0, -2.0, 3.0], [1.0, -2.0, 3.0], [0.0, 1.0, 0.0]),
        // An off-axis 3D normal with a partial alignment within radius (the exact `n` literal
        // is irrelevant — host + eDSL receive the SAME value, so bit-equality holds).
        ([0.5, 0.5, 0.5], [0.62, 0.58, 0.55], [0.6, 0.8, 0.0]),
        // A neighbour BELOW the tangent (negative elevation -> clamped to 0): the running `hc`
        // (already positive) wins.
        ([0.0, 0.0, 0.0], [0.0, 0.0, -0.1], [0.0, 0.0, 1.0]),
    ];
    for (i, (p, pp, n)) in cases.iter().enumerate() {
        // Feed hc = 0 (the half-slice accumulator's seed) AND a non-zero hc (a mid-march value)
        // to exercise both the `max(0, …)` and the `max(prev, …)` branches.
        for &hc_seed in &[0.0_f32, 0.37_f32] {
            // Render P7-Q2: the host tap now reads `params.radius`/`params.eps`; the eDSL Eval
            // body spells `SSAO_RADIUS`/`SSAO_EPS` (the module consts == the Medium row). Feed the
            // host the Medium params (`SsaoParams::default()`) so both read the SAME radius/eps and
            // the bit-equality holds (Medium == today's shipped consts == the eDSL Eval scalars).
            let host = boyko_rhi_vulkan::goldens::ssao_horizon_step(
                hc_seed,
                *p,
                *pp,
                *n,
                &boyko_rhi_vulkan::compute::SsaoParams::default(),
            );
            let edsl = ssao::ssao_horizon_step_body::<EvalCf>(*p, *pp, *n, hc_seed);
            assert_eq!(
                host.to_bits(),
                edsl.to_bits(),
                "case {i} (hc_seed = {hc_seed}): host compute::ssao_horizon_step DRIFTED from the \
                 eDSL ssao::ssao_horizon_step_body::<EvalCf> (host = {host}, eDSL = {edsl}) — the \
                 plain-Rust SSAO re-derive no longer matches the single-source eDSL body."
            );
        }
    }
}

#[test]
fn ssao_consts_host_match_edsl() {
    // The single-source const guard: the host SSAO tuning (`compute::SSAO_*`) must equal the
    // eDSL `pub const`s (`boyko_shaderdsl::ssao::SSAO_*`) the GENERATED HLSL span spells
    // SYMBOLICALLY. A host-only edit of a radius/strength/eps would silently fork the oracle
    // from the shader; this catches it host-side, before the GPU run.
    use boyko_rhi_vulkan::compute as host;
    assert_eq!(host::SSAO_RADIUS, ssao::SSAO_RADIUS, "SSAO_RADIUS host vs eDSL");
    assert_eq!(
        host::SSAO_SLICES as usize,
        ssao::SSAO_SLICES,
        "SSAO_SLICES host vs eDSL"
    );
    assert_eq!(
        host::SSAO_STEPS as usize,
        ssao::SSAO_STEPS,
        "SSAO_STEPS host vs eDSL"
    );
    assert_eq!(
        host::SSAO_STRENGTH,
        ssao::SSAO_STRENGTH,
        "SSAO_STRENGTH host vs eDSL"
    );
    assert_eq!(host::SSAO_EPS, ssao::SSAO_EPS, "SSAO_EPS host vs eDSL");
    // The float slice-divisor mirrors the eDSL's `SSAO_SLICES as f32` (the `occ / N` divisor).
    assert_eq!(
        host::SSAO_SLICES_F,
        ssao::SSAO_SLICES as f32,
        "SSAO_SLICES_F host vs eDSL slice count"
    );
}

#[test]
fn ssao_params_table_host_match_edsl() {
    // Render P7-Q2: the host quality-preset table (`compute::SSAO_PARAMS`, the AO oracle's variant
    // tuning) must equal the eDSL source of truth (`boyko_shaderdsl::ssao::SSAO_PRESETS`, the table
    // the pre-compiled `.spv` variants bake) ROW-FOR-ROW. A host-only edit of a variant's tap
    // budget / radius / strength would silently fork the oracle from the shipped variant `.spv`;
    // this catches it host-side, before any GPU run. The host `SsaoParams` cannot reference the
    // eDSL type (the lib has no dev-dep on it), so compare field-by-field.
    use boyko_rhi_vulkan::compute as host;
    assert_eq!(
        host::SSAO_PARAMS.len(),
        ssao::SSAO_PRESETS.len(),
        "SSAO_PARAMS row count host vs eDSL"
    );
    for (q, e) in host::SSAO_PARAMS.iter().zip(ssao::SSAO_PRESETS.iter()) {
        assert_eq!(q.radius, e.radius, "SSAO_PARAMS radius host vs eDSL");
        assert_eq!(q.slices, e.slices, "SSAO_PARAMS slices host vs eDSL");
        assert_eq!(q.steps, e.steps, "SSAO_PARAMS steps host vs eDSL");
        assert_eq!(q.strength, e.strength, "SSAO_PARAMS strength host vs eDSL");
        assert_eq!(q.eps, e.eps, "SSAO_PARAMS eps host vs eDSL");
    }
    // The MEDIUM row IS today's shipped module consts (the no-op proof, host-side).
    let medium = host::SSAO_PARAMS[host::SSAO_QUALITY_MEDIUM];
    assert_eq!(medium.radius, host::SSAO_RADIUS, "Medium radius == SSAO_RADIUS");
    assert_eq!(medium.slices, host::SSAO_SLICES, "Medium slices == SSAO_SLICES");
    assert_eq!(medium.steps, host::SSAO_STEPS, "Medium steps == SSAO_STEPS");
    assert_eq!(
        medium.strength,
        host::SSAO_STRENGTH,
        "Medium strength == SSAO_STRENGTH"
    );
    assert_eq!(medium.eps, host::SSAO_EPS, "Medium eps == SSAO_EPS");
    // `SsaoParams::default()` must BE the Medium row.
    assert_eq!(
        host::SsaoParams::default(),
        medium,
        "SsaoParams::default() must equal the Medium preset"
    );
}
