//! eDSL <-> HLSL SINGLE-SOURCE GUARD for the Render P7 GROUP A SSAO shader.
//!
//! `shaders/sdf_ssao.comp.hlsl`'s horizon-step span (`delta = P' - P`, the squared-
//! distance `falloff` range gate, the `elev = max(dot(delta,N) / max(length(delta),
//! SSAO_EPS), 0)` elevation above the tangent plane, and the `hc = max(hc, elev * falloff)`
//! running horizon max) is MACHINE-GENERATED by `boyko_shaderdsl::emit::emit_hlsl_ssao()` — the eDSL whose
//! `<EvalCf>` instantiation (`boyko_shaderdsl::ssao::ssao_estimate_body`) is the host AO
//! oracle the golden gather calls. Both the host (Eval) and the generated HLSL (Emit)
//! instantiate the SAME generic horizon-step body, so they cannot diverge BY CONSTRUCTION
//! — UNLESS someone hand-edits the spliced span without re-emitting (the by-hand drift the
//! eDSL kills).
//!
//! This file is the SSAO drift gate. Two tests:
//!   1. `ssao_horizon_step_matches_edsl_emit` — the `.contains` drift gate: assert the
//!      committed shader still contains the EXACT generated span. The fix when it trips:
//!      re-run `cargo run -p boyko_shaderdsl --features emit --bin emit_field` and re-splice
//!      between the `// === GENERATED ssao_horizon_step BEGIN/END ===` sentinels (BOTH the
//!      `+dir` and `-dir` half-slice copies), then re-DXC `sdf_ssao.comp.spv`.
//!   2. `ssao_spv_byte_identical` — the re-DXC byte-identity gate: re-compile the committed
//!      `.hlsl` with the EXACT recipe (`dxc -spirv -T cs_6_0 -E main
//!      -fspv-target-env=vulkan1.3`, NO `-O`) and assert the bytes equal the committed
//!      `sdf_ssao.comp.spv`. This proves the committed `.spv` the engine loads IS the
//!      spliced text + hand-written glue, end-to-end. SKIPS (does not fail) when DXC is not
//!      on this host — the byte-identity claim cannot be evaluated without the compiler, and
//!      a missing SDK is an environment gap, not a shader regression.

use std::path::PathBuf;
use std::process::Command;

use boyko_shaderdsl::cf::EvalCf;
use boyko_shaderdsl::ssao;

/// The shaders directory (`CARGO_MANIFEST_DIR/shaders`), where the committed `.hlsl` and
/// `.spv` live (and where DXC must run so its `#include "ray_gen.hlsli"` resolves).
fn shaders_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("shaders")
}

/// Locates the `dxc` executable: first the pinned Vulkan-SDK path (the repo's offline
/// recipe), then `$VULKAN_SDK/Bin`, then `PATH`. Returns `None` if none resolve (the
/// byte-identity test then SKIPS).
fn find_dxc() -> Option<PathBuf> {
    // The repo's pinned offline DXC (the recipe in every eDSL-generated shader's header).
    let pinned = PathBuf::from("C:/VulkanSDK/1.4.350.0/Bin/dxc.exe");
    if pinned.exists() {
        return Some(pinned);
    }
    // `$VULKAN_SDK/Bin/dxc`.
    let bare = if cfg!(windows) { "dxc.exe" } else { "dxc" };
    if let Ok(sdk) = std::env::var("VULKAN_SDK") {
        let candidate = PathBuf::from(sdk).join("Bin").join(bare);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    // A PATH-resolvable `dxc`.
    if Command::new(bare).arg("--version").output().is_ok() {
        return Some(PathBuf::from(bare));
    }
    None
}

#[test]
fn ssao_horizon_step_matches_edsl_emit() {
    // The SSAO horizon-step span (Render P7 GROUP A — HBAO-lite, no-trig: ONE forward
    // horizon tap's math) is GENERATED by `boyko_shaderdsl::emit::emit_hlsl_ssao()` from the
    // SAME source whose `<EvalCf>` instantiation (`ssao::ssao_estimate_body`) is the host AO
    // oracle. It is a SPAN, not a whole function: the forward neighbour reconstruct, the
    // `[unroll]` slice/step loops, the rotation-table direction, and the `occ → ao` fold stay
    // hand-written (framing b), so this is a `.contains` of the emitted span (spliced between
    // the GENERATED ssao_horizon_step sentinels — TWICE, the +dir and -dir half-slices), not
    // an extract_fn. A hand-edit of the committed span fails CI here. The cmp-.spv (the
    // companion `ssao_spv_byte_identical`) proves the spliced text re-DXCs byte-identical.
    //
    // ZERO new eDSL leaves: `dot` is inline component-reads + mul/add, `length =
    // sqrt(dot(d,d))`, the `ao*ao` power an integer self-mul — so the frozen marcher/field/
    // shadow/brick/resolve `.spv` cannot fork (proven by the existing `*_edsl_sync` suite,
    // which stays green).
    let generated = boyko_shaderdsl::emit::emit_hlsl_ssao().replace("\r\n", "\n");

    let shader_path = shaders_dir().join("sdf_ssao.comp.hlsl");
    let shader = std::fs::read_to_string(&shader_path)
        .expect("invariant: shaders/sdf_ssao.comp.hlsl must exist next to this crate")
        .replace("\r\n", "\n");

    assert!(
        shader.contains(&generated),
        "sdf_ssao.comp.hlsl `ssao_horizon_step` span DRIFTED from boyko_shaderdsl::emit — the \
         committed span no longer matches the generator. Re-run `cargo run -p boyko_shaderdsl \
         --features emit --bin emit_field` and re-splice between BOTH GENERATED \
         ssao_horizon_step sentinel pairs (the forward reconstruct + the slice/step loops + \
         the rotation direction + the occ→ao fold stay hand-written), then re-DXC \
         sdf_ssao.comp.spv.\n--- expected (eDSL-generated) ---\n{generated}"
    );
}

#[test]
fn ssao_spv_byte_identical() {
    // The committed `sdf_ssao.comp.spv` the engine loads must be the EXACT re-DXC of the
    // committed `sdf_ssao.comp.hlsl` (the spliced eDSL span + the hand-written glue) under the
    // frozen recipe `dxc -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3` (NO `-O`). This
    // is the byte-identity oracle: it proves the shipped `.spv` is the single-sourced text,
    // not a stale or hand-tweaked blob. A drift fails CI; the fix is to re-DXC and re-commit.
    let Some(dxc) = find_dxc() else {
        eprintln!(
            "ssao_edsl_sync: dxc not found (no C:/VulkanSDK/.../dxc.exe, no $VULKAN_SDK/Bin, \
             not on PATH) — SKIPPING the SSAO re-DXC byte-identity check on this host."
        );
        return;
    };

    let dir = shaders_dir();
    let hlsl = dir.join("sdf_ssao.comp.hlsl");
    let committed_spv = dir.join("sdf_ssao.comp.spv");
    assert!(
        hlsl.exists(),
        "missing committed SSAO HLSL: {} ",
        hlsl.display()
    );
    let committed = std::fs::read(&committed_spv).unwrap_or_else(|e| {
        panic!(
            "missing committed SSAO SPIR-V {} : {e} (compile sdf_ssao.comp.hlsl with the \
             frozen DXC recipe and commit it)",
            committed_spv.display()
        )
    });

    // Re-DXC to a temp `.spv` (NOT overwriting the committed one) under the EXACT recipe.
    // `current_dir(shaders_dir)` so the relative `#include "ray_gen.hlsli"` resolves.
    let out_spv = std::env::temp_dir().join("sdf_ssao.redxc.comp.spv");
    let status = Command::new(&dxc)
        .current_dir(&dir)
        .args([
            "-spirv",
            "-T",
            "cs_6_0",
            "-E",
            "main",
            "-fspv-target-env=vulkan1.3",
            "sdf_ssao.comp.hlsl",
            "-Fo",
        ])
        .arg(&out_spv)
        .status()
        .expect("invariant: dxc was located and must run");
    assert!(
        status.success(),
        "dxc failed re-compiling sdf_ssao.comp.hlsl under the frozen recipe"
    );

    let regenerated = std::fs::read(&out_spv).expect("invariant: dxc wrote the re-DXC .spv");
    // Tidy the temp artifact (best-effort).
    let _ = std::fs::remove_file(&out_spv);

    assert_eq!(
        regenerated,
        committed,
        "sdf_ssao.comp.spv BYTE-DRIFTED from a fresh re-DXC of sdf_ssao.comp.hlsl — the \
         committed .spv the engine loads is NOT the single-sourced text. Re-DXC with \
         `dxc -spirv -T cs_6_0 -E main -fspv-target-env=vulkan1.3 sdf_ssao.comp.hlsl \
         -Fo sdf_ssao.comp.spv` and re-commit. (regenerated = {} bytes, committed = {} bytes)",
        regenerated.len(),
        committed.len()
    );
}

#[test]
fn ssao_horizon_step_host_matches_edsl_eval() {
    // Render P7 GROUP B drift gate: the SHIPPED backend (`boyko_rhi_vulkan::compute`) re-derives
    // the SSAO per-tap horizon as PLAIN RUST (`compute::ssao_horizon_step`), because
    // `boyko_shaderdsl` is a DEV-dependency only — the lib must not link the eDSL. This test
    // (which HAS the dev-dep) is the single-source guard: it asserts the plain-Rust per-tap
    // horizon is BIT-EQUAL to the eDSL `<EvalCf>` Eval body
    // (`boyko_shaderdsl::ssao::ssao_horizon_step_body`) the GENERATED HLSL span is also traced
    // from — so the host oracle the pixel goldens trust cannot silently drift from the shader.
    //
    // The eDSL body order is `(p, pp, n, hc)`; the host re-derive's is `(hc, p, pp, n)` (the
    // running accumulator first, the established `host_ao`/`host_soft_shadow` shape). Both
    // compute the SAME `hc' = max(hc, max(dot(delta,N)/|delta|, 0) * falloff)` over the SAME
    // `f32` arithmetic. The third vector is now the CENTER SURFACE NORMAL `N`, not the screen
    // slice direction.
    let cases: [([f32; 3], [f32; 3], [f32; 3]); 6] = [
        // A neighbour rising above the tangent along +N within radius (a crevice tap): a
        // strong positive elevation.
        ([0.0, 0.0, 0.0], [0.0, 0.0, 0.12], [0.0, 0.0, 1.0]),
        // A neighbour IN the tangent plane (delta perpendicular to N): zero elevation.
        ([0.0, 0.0, 0.0], [0.1, 0.0, 0.0], [0.0, 0.0, 1.0]),
        // A neighbour BEYOND radius (open): falloff zeroes it.
        ([0.0, 0.0, 0.0], [0.0, 0.0, 0.9], [0.0, 0.0, 1.0]),
        // A degenerate Pp == P (a skipped seam tap): the SSAO_EPS guard, no NaN.
        ([1.0, -2.0, 3.0], [1.0, -2.0, 3.0], [0.0, 1.0, 0.0]),
        // An off-axis 3D normal with a partial alignment within radius (the exact `n` literal
        // is irrelevant — host + eDSL receive the SAME value, so bit-equality holds).
        ([0.5, 0.5, 0.5], [0.62, 0.58, 0.55], [0.6, 0.8, 0.0]),
        // A neighbour BELOW the tangent (negative elevation -> clamped to 0): the running `hc`
        // (already positive) wins.
        ([0.0, 0.0, 0.0], [0.0, 0.0, -0.1], [0.0, 0.0, 1.0]),
    ];
    for (i, (p, pp, n)) in cases.iter().enumerate() {
        // Feed hc = 0 (the half-slice accumulator's seed) AND a non-zero hc (a mid-march value)
        // to exercise both the `max(0, …)` and the `max(prev, …)` branches.
        for &hc_seed in &[0.0_f32, 0.37_f32] {
            let host = boyko_rhi_vulkan::compute::ssao_horizon_step(hc_seed, *p, *pp, *n);
            let edsl = ssao::ssao_horizon_step_body::<EvalCf>(*p, *pp, *n, hc_seed);
            assert_eq!(
                host.to_bits(),
                edsl.to_bits(),
                "case {i} (hc_seed = {hc_seed}): host compute::ssao_horizon_step DRIFTED from the \
                 eDSL ssao::ssao_horizon_step_body::<EvalCf> (host = {host}, eDSL = {edsl}) — the \
                 plain-Rust SSAO re-derive no longer matches the single-source eDSL body."
            );
        }
    }
}

#[test]
fn ssao_consts_host_match_edsl() {
    // The single-source const guard: the host SSAO tuning (`compute::SSAO_*`) must equal the
    // eDSL `pub const`s (`boyko_shaderdsl::ssao::SSAO_*`) the GENERATED HLSL span spells
    // SYMBOLICALLY. A host-only edit of a radius/strength/eps would silently fork the oracle
    // from the shader; this catches it host-side, before the GPU run.
    use boyko_rhi_vulkan::compute as host;
    assert_eq!(host::SSAO_RADIUS, ssao::SSAO_RADIUS, "SSAO_RADIUS host vs eDSL");
    assert_eq!(
        host::SSAO_SLICES as usize,
        ssao::SSAO_SLICES,
        "SSAO_SLICES host vs eDSL"
    );
    assert_eq!(
        host::SSAO_STEPS as usize,
        ssao::SSAO_STEPS,
        "SSAO_STEPS host vs eDSL"
    );
    assert_eq!(
        host::SSAO_STRENGTH,
        ssao::SSAO_STRENGTH,
        "SSAO_STRENGTH host vs eDSL"
    );
    assert_eq!(host::SSAO_EPS, ssao::SSAO_EPS, "SSAO_EPS host vs eDSL");
    // The float slice-divisor mirrors the eDSL's `SSAO_SLICES as f32` (the `occ / N` divisor).
    assert_eq!(
        host::SSAO_SLICES_F,
        ssao::SSAO_SLICES as f32,
        "SSAO_SLICES_F host vs eDSL slice count"
    );
}
